# GenAI Pipeline — Patents

LLM-based screening of patents for end product classification.
Uses Claude with structured output via the Anthropic Python SDK.

Adapted from the publications GenAI pipeline.

### 1. Imports and Configuration

In [24]:
import duckdb
import pandas as pd
import json
import random
import time
import anthropic
import os
from pathlib import Path
from dotenv import load_dotenv
from pydantic import BaseModel, Field, field_validator, create_model
from typing import Literal

load_dotenv("../../.env")

DB_PATH = "../../patents_training.db"
OUTPUT_DIR = Path(".")

### 2. Data Inspection

In [2]:
con = duckdb.connect(DB_PATH, read_only=True)
print("Tables:")
print(con.sql("SHOW TABLES").df())

df = con.sql("SELECT * FROM patents_raw").df()   # ← UPDATE: table name
con.close()

df = df[df['scope'] == 'in']
df['endproduct'] = df['endproduct'].fillna('Agnostic')

print(f"\nShape: {df.shape}")
print(f"\nColumns: {list(df.columns)}")
print(f"\nScope distribution:")
print(df["scope"].value_counts())
print(f"\nEnd product distribution:")
print(df["endproduct"].value_counts())
df.head()

Tables:
                 name
0  patents_embeddings
1         patents_raw

Shape: (1275, 15)

Columns: ['id', 'family_id', 'application_number', 'title', 'abstract', 'cpc', 'publication_year', 'jurisdiction', 'scope', 'pillar', 'subpillar', 'research_category', 'endproduct', 'ingredient', 'truncated']

Scope distribution:
scope
in    1275
Name: count, dtype: int64

End product distribution:
endproduct
Meat                                      516
Milk and milk proteins                    234
Agnostic                                  210
Cross-cutting                             110
Cheese                                     83
Yoghurt and fermented dairy                44
Eggs and egg proteins                      24
Chocolate, desserts, and confectionery     18
Cream and ice cream                        17
Fish and seafood                           15
Spreads, sauces, and condiments             4
Name: count, dtype: int64

,id,family_id,application_number,title,abstract,cpc,publication_year,jurisdiction,scope,pillar,subpillar,research_category,endproduct,ingredient,truncated
2,US-20170298457-A1,42829610,US15360298,LACTIC BACTERIUM WITH MODIFIED GALACTOKINASE E...,The present invention relates to a bacterial c...,"['A23C19/0323', 'C12N9/1205', 'A23C2220/206', ...",2017,US,in,PB,NaN,Strain development,Yoghurt and fermented dairy,NaN,False
3,EP-2473058-A1,42829610,EP10751643A,LACTIC BACTERIUM WITH MODIFIED GALACTOKINASE E...,The present invention relates to a bacterial c...,"['A23C19/0323', 'C12R2001/46', 'C12Y207/01006'...",2012,EP,in,PB,NaN,Strain development,Yoghurt and fermented dairy,NaN,False
28,EP-4424172-A3,52462090,EP24182765.8,A PROTEINACEOUS MEAT ANALOGUE HAVING AN IMPROV...,The invention concerns an extended shelf-life ...,"['A23V2002/00', 'A23V2200/20', 'A23J3/22', 'A2...",2025,EP,in,PB,NaN,End product formulation,Meat,NaN,False
29,US-11666069-B2,52462090,US17530304,Proteinaceous meat analogue having an improved...,An extended shelf-life proteinaceous meat anal...,"['A23J3/22', 'A23J3/18', 'A23V2200/20', 'A23V2...",2023,US,in,PB,NaN,End product formulation,Meat,NaN,False
32,EP-4627930-A3,52596486,EP25169128.3,VARIANTS OF CHYMOSIN WITH IMPROVED MILK-CLOTTI...,Variants of chymosin with improved milk-clotti...,"['A23C19/04', 'A23C19/041', 'C12N9/6483', 'A23...",2026,EP,in,PB,NaN,End product formulation,Cheese,NaN,False

### 3. Balanced Subset Creation

Two test sets with balanced representation across scope and pillar:
- `initial_test_data`: ~14 records (6 out, 2 PB, 2 F, 2 cultivated, 2 cross-cutting)
- `test_data_100`: ~110 records (40 out, 30 PB, 15 F, 15 cultivated, 10 cross-cutting)

Adjust counts to match the actual distribution in your patents dataset.

In [3]:
RANDOM_STATE=4

def create_balanced_sample(df, category_counts, random_state=RANDOM_STATE):
    """
    category_counts: dict mapping end product -> n, e.g.
        {"Meat": 5, "Cheese": 3, "Other": 2}
    Categories with no matching rows are skipped with a warning.
    If n exceeds available rows, all available rows are taken (with a warning).
    """
    samples = []
    for cat, n in category_counts.items():
        subset = df[df["endproduct"] == cat]
        available = len(subset)
        if available == 0:
            print(f"  Warning: '{cat}' — no rows found, skipping.")
            continue
        if n > available:
            print(f"  Warning: '{cat}' — requested {n} but only {available} available, taking all.")
            n = available
        samples.append(subset.sample(n=n, random_state=random_state))
    combined = pd.concat(samples, ignore_index=True)
    return combined.sample(frac=1, random_state=random_state).reset_index(drop=True)

In [4]:
test_data = create_balanced_sample(df, {
    'Yoghurt and fermented dairy': 10,
    'Meat': 10,
    'Cheese': 10,
    'Milk and milk proteins': 10,
    'Cross-cutting': 10,
    'Cream and ice cream': 10,
    'Chocolate, desserts, and confectionery': 10,
    'Eggs and egg proteins': 10,
    'Fish and seafood': 10,
    'Agnostic': 10,
    'Spreads, sauces, and condiments': 10,
}, random_state=RANDOM_STATE)
print(f"test_data: {test_data.shape}")

  Warning: 'Spreads, sauces, and condiments' — requested 10 but only 4 available, taking all.
test_data: (104, 15)

### 4. Save Subsets to Excel

In [ ]:
################################################################################################
# PLEASE CHANGE FILENAME TO THE RANDOM SEED USED IN create_balanced_sample() FOR REPRODUCIBILITY
################################################################################################
def save_subset(df, filename, output_dir=OUTPUT_DIR):
    path = output_dir / filename
    df.to_csv(path, index=False)
    print(f"Saved {len(df)} records to {path}")

#save_subset(test_data, f"endproduct_test_data_rand{RANDOM_STATE}.csv")

Saved 104 records to endproduct_test_data_rand4.csv

In [59]:
# Read subset data from file
test_data = pd.read_csv(f"endproduct_test_data_rand{RANDOM_STATE}.csv")

In [60]:
test_data.value_counts('endproduct')

endproduct
Cross-cutting                             15
Agnostic                                  14
Chocolate, desserts, and confectionery    10
Cream and ice cream                       10
Yoghurt and fermented dairy                9
Fish and seafood                           9
Meat                                       9
Eggs and egg proteins                      7
Cheese                                     7
Dairy                                      6
Milk and milk proteins                     4
Spreads, sauces, and condiments            4
Name: count, dtype: int64

### 5. Load Prompt and Select Dataset

In [61]:
PROMPT_PATH = "prompt_endproduct_patents_work.md"   # ← UPDATE: path to current prompt version
PROMPT_VERSION = "v3"

# ← CHANGE THIS to switch between datasets
# Options: initial_test_data (14 records), test_data_100 (110 records)
DATASET = test_data
DATASET_STR = "test_data"

In [62]:
def load_prompt(path=PROMPT_PATH):
    with open(path, "r", encoding="utf-8") as f:
        prompt_text = f.read()
    return prompt_text.strip()

system_prompt = load_prompt()
print(system_prompt)

You are an expert in alternative proteins and food technology.

Your task is to classify a patent on alternative proteins into an end product category based on its title and abstract.

Before assigning a category, identify the primary end product or application context that the patent is designed for. The specific categories below are reserved for patents that primarily target one type of alternative protein end product. Assign Cross-cutting, Dairy, or Agnostic only when the patent genuinely does not target a single specific product type.

IMPORTANT: Base your classification ONLY on what the title and abstract explicitly state about the intended end product application. Do NOT infer an end product from external knowledge about how an ingredient, organism, or technology is commonly used. Do NOT infer a product category from the physical form of an ingredient (beads, microcapsules, spheres, gels, pastes) — a delivery system or encapsulated ingredient with a flavoured filling is not automatically confectionery, and a paste or purée is not automatically a spread or condiment. If the abstract does not describe a specific product application, assign Agnostic or Cross-cutting — never assign a specific product category based on an assumed or inferred use.

Key decision rules:
- A patent for a meat analogue — including plant-based burgers, sausages, nuggets, chicken strips, minced meat, or whole-cut meat substitutes, regardless of whether it is plant-based, fermentation-derived, or cultivated — → Meat. Also includes bioreactors or methods producing cultured fat or marbling fat explicitly described for cultivated meat applications → Meat
- A patent for a fish or seafood analogue (plant-based tuna, shrimp, fish fillet substitute) → Fish and seafood. Note: algae or microalgae patents not explicitly described as fish/seafood substitutes should NOT be assigned Fish and seafood — assign Agnostic or Cross-cutting based on the product context stated
- A patent covering both meat AND fish/seafood analogues (or a coated meat-or-fish substitute) → Cross-cutting (not Meat or Fish and seafood separately)
- For dairy analogues, assign the most specific dairy subcategory that applies:
  → **Milk and milk proteins**: liquid milk alternatives (oat milk, almond milk, soy milk, rice milk, pea milk) and milk protein ingredients (concentrates, isolates) specifically described for liquid dairy or beverage applications
  → **Yoghurt and fermented dairy**: specifically fermented dairy analogues (non-dairy yogurt, kefir, labneh) and starter cultures or LAB strains specifically described for fermented plant-based dairy products
  → **Cheese**: cheese analogues and cheese-making technologies (rennet/chymosin replacers, proteolytic ripening enzymes, plant-based cheese products)
  → **Cream and ice cream**: plant-based cream, whipping cream alternatives, and frozen confections (ice cream, gelato, sorbet, frozen dessert products)
  → **Dairy**: clearly targets dairy analogues but the abstract does not allow confident assignment to one of the four subcategories above — assign Dairy when the patent is evidently about dairy products (milk, yoghurt, cheese, or cream analogues) but spans multiple dairy subcategories or the specific type is ambiguous from the abstract alone
- Assign Dairy only when the patent is exclusively about dairy-analogue products. If the abstract also mentions other AP product types alongside dairy (e.g. applicable to meat analogues, fish analogues, or described broadly across food categories) → Cross-cutting, not Dairy
- A patent for a product explicitly described for multiple dairy types (e.g. applicable to chocolate, ice cream, cheese, and yogurt) → Cross-cutting (not a dairy category)
- A patent for a chocolate product, dessert, or confectionery item that uses alternative protein ingredients → Chocolate, desserts, and confectionery; this is distinct from frozen desserts, which → Cream and ice cream. Also applies to dairy-free analogues of sweetened condensed milk → Chocolate, desserts, and confectionery (sweetened condensed milk is primarily a confectionery ingredient, not a direct dairy substitute)
- A patent for egg replacers, egg-free baking solutions, or alternative protein-derived egg proteins (ovalbumin, other egg proteins) → Eggs and egg proteins
- A patent for a plant-based butter, cooking fat, shortening, or other fat-phase food product → Spreads, sauces, and condiments; a patent for a water-continuous emulsion (mayonnaise, dressing, sauce) → also Spreads, sauces, and condiments. A fermented food or ingredient described only as a "paste" or "purée" is NOT Spreads unless the product is explicitly framed as a spread, condiment, or sauce
- A patent that explicitly names or applies to multiple distinct end product types → Cross-cutting. Also assign Cross-cutting for food ingredient COMPOSITION patents (textured proteins, food-use enzyme preparations such as deamidases, transglutaminases, or proteases; encapsulated food ingredients) described without any specific product type framing — these are food ingredients without a targeted application. Important distinction: an enzyme COMPOSITION patent (where the enzyme formulation itself is the claimed innovation) → Cross-cutting even if no food product is mentioned; a METHOD patent applying an enzyme or process to modify generic "food products" or "foods containing protein" without naming any specific product type → Agnostic
- A patent describing processing equipment, bioreactor systems, bacterial or fungal strains, extraction or fractionation methods, or bioproduction processes with no explicit food product application stated → Agnostic. Exception: processing equipment that explicitly names a specific food product application (e.g. a milk frothing or steaming device for milk/coffee applications, a cheese press) → assign the corresponding product category, not Agnostic

From the 12 end product categories defined below, identify the top 2 categories that best capture the primary end product application of the patent, ranked from most to least likely. Provide one extremely concise sentence of reasoning for your choice.

End Product Categories:
- Meat: Alternative protein products designed to replicate whole cuts, minced meat, burgers, patties, sausages, meatballs, nuggets, chicken strips, deli meat, or other meat-format products. Includes plant-based, fermentation-derived (mycoprotein, single-cell protein), and cultivated meat products targeting meat-specific applications. Also includes bioreactors or processes producing cultured fat explicitly for cultivated meat.
- Fish and seafood: Alternative protein products designed to replicate fish fillets, tuna, shrimp, crab, prawns, calamari, or other seafood products. Includes plant-based and fermentation-derived seafood analogues. Does not include algae or microalgae products that are not explicitly described as seafood substitutes.
- Milk and milk proteins: Liquid milk alternatives (oat milk, almond milk, soy milk, rice milk, pea milk, and similar plant-based milks) and milk protein ingredients (concentrates, isolates, dairy-analogue protein bases) specifically described for liquid dairy or beverage applications.
- Yoghurt and fermented dairy: Fermented dairy analogues specifically — non-dairy yogurt, kefir, labneh, and fermented plant-based milk products — and the microbial cultures (lactic acid bacteria strains, starter cultures) specifically described for producing fermented plant-based dairy. Assign only when the patent's primary end product is explicitly a fermented dairy analogue; a general LAB strain or fermentation technology not specifically described for dairy → Dairy or Cross-cutting.
- Cheese: Cheese analogues and cheese-making technologies — plant-based or fermentation-derived cheese products, rennet and chymosin replacers, proteolytic and lipolytic enzymes specifically described for cheese ripening, and cheese-specific coagulation methods. Assign when the primary end product application is explicitly cheese.
- Cream and ice cream: Plant-based cream, whipping cream alternatives, and frozen confections (ice cream, gelato, sorbet, frozen yogurt-style products). Assign for products explicitly described as replicating cream or delivering a frozen dairy-style dessert experience.
- Dairy: Patents clearly targeting dairy-analogue products where the specific dairy subcategory (Milk, Yoghurt, Cheese, or Cream and ice cream) cannot be determined from the abstract alone, or where the patent spans multiple dairy subcategories. Use as a fallback when the patent is evidently about dairy analogues but the abstract is ambiguous about the product type. Examples: a fermented dairy product described without specifying whether it is yoghurt, cheese, or a different dairy type; a technology described for "dairy products" generally; an ingredient described for improving texture across dairy products.
- Agnostic: Patents where no specific food product application is mentioned or implied — the patent describes processing equipment or systems (bioreactors, agglomeration systems, extrusion dies, cutting devices), biological entities (bacterial or fungal strains, microbial biomass) characterised without a food product framing, extraction or fractionation methods described without any downstream product context, bioproduction processes with no stated food application, or METHOD patents applying a process to a generic "food product" or "food product containing protein" without specifying any product type. Agnostic does not include food ingredient COMPOSITIONS (textured proteins, enzyme preparations such as deamidases or transglutaminases formulated for food use, encapsulated food ingredients) — those belong in Cross-cutting if no specific product is targeted. Exception: processing equipment that explicitly names a specific product application (a milk frothing device, a cheese press) → assign the corresponding product category instead.
- Chocolate, desserts, and confectionery: Alternative protein products or formulations targeting chocolate compositions (dairy-free or reduced-dairy chocolate, chocolate crumb, chocolate products made with plant-based milk alternatives), dessert items (puddings, custards, mousse, baked desserts), and confectionery (sweets, candies, gummies). Also includes dairy-free analogues of sweetened condensed milk and other confectionery base ingredients (sweetened condensed milk is primarily a confectionery ingredient — its plant-based substitute belongs here, not in a dairy category). Does not include ice cream and frozen desserts → Cream and ice cream.
- Eggs and egg proteins: Egg replacers, egg-free baking solutions, and functional egg-substituting products for cooking and baking. Also includes precision fermentation-derived egg proteins (ovalbumin and other egg proteins), and ingredients specifically developed to replicate egg functionality (emulsification, foaming, coagulation) in end product applications.
- Cross-cutting: Patent explicitly designed for, or claimed to work across, multiple distinct end product categories. Assign when the patent: (a) explicitly spans two or more named product types (e.g. applicable to meat and dairy; designed for "non-animal-derived protein products" in general; described for use across a range of food products); or (b) describes a food ingredient COMPOSITION — such as a textured protein, a food-use enzyme preparation (deamidases, transglutaminases, proteases, lipases formulated as food-processing aids — even when the abstract does not mention a specific food product), or an encapsulated food ingredient — that is intended as a food ingredient without targeting any specific product type. Note: this applies to enzyme COMPOSITION patents; METHOD patents that apply an enzyme or process to generic "food products" without specifying any product type → Agnostic. Cross-cutting is for patents that are clearly about food applications; use Agnostic for patents that are not about food products at all.
- Spreads, sauces, and condiments: Mayonnaise-like products, water-continuous emulsions, plant-based dressings, sauces, condiments, and fat-phase spreads (plant-based butter, margarine, cooking fat analogues). Assign for plant-based mayonnaise, emulsified dressings, sandwich spreads, and butter or fat substitutes. Note: a food product described as a "paste" or "purée" is NOT automatically a spread — only assign this category when the product is explicitly framed as a spread, condiment, sauce, or emulsified fat product.

### 6. API Call with Structured Output

In [63]:
# API config

# Anthropic model options — pricing as of 2026-06-10.
# Verify at https://www.anthropic.com/pricing if costs may have changed.
# Model                  Input $/1M   Output $/1M   Context
# claude-haiku-4-5         $1.00         $5.00       200K
# claude-sonnet-4-6        $3.00        $15.00       1M
# claude-opus-4-8          $5.00        $25.00       1M
MODELS = {
    "haiku":  "claude-haiku-4-5",
    "sonnet": "claude-sonnet-4-6",
    "opus":   "claude-opus-4-8",
}
MODEL = MODELS["sonnet"]  # ← change this to switch model
# If using Opus, comment out TEMPERATURE below

MAX_TOKENS = 512         # max tokens in response
TEMPERATURE = 0.0        # 0.0 = deterministic; raise to ~0.3 to sample variance
CALL_DELAY = 1.0         # seconds between API calls
REQUEST_TIMEOUT = 120    # seconds before giving up on a single API call
MAX_RETRIES = 6          # retry attempts on rate-limit / transient errors
RETRY_BASE_SECONDS = 5.0
RETRY_MAX_SECONDS = 90.0

REPETITIONS = 1          # number of full runs; increase to measure output variance

# ================================================================
# CHECKPOINT CONFIG
# ================================================================
CHECKPOINT_DIR = Path("checkpoints")
RESUME_INCOMPLETE = True

In [64]:
# ================================================================
# REASONING TOGGLE
# Keep True during testing — reasoning shows WHY the model decides
# as it does, which is essential for evaluating prompt quality.
# Set to False for production runs once the prompt is validated,
# to reduce token usage.
# ================================================================
INCLUDE_REASONING = True

END_PRODUCT_CATS = [
    "Meat",
    "Fish and seafood",
    "Milk and milk proteins",
    "Yoghurt and fermented dairy",
    "Cheese",
    "Cream and ice cream",
    "Agnostic",
    "Chocolate, desserts, and confectionery",
    "Eggs and egg proteins",
    "Cross-cutting",
    "Spreads, sauces, and condiments",
    "Dairy",
]

def make_schema(cats, include_reasoning):
    cats_map = {c.lower(): c for c in cats}
    cat_type = Literal[*cats]

    class _Base(BaseModel):
        @field_validator("primary", "secondary", mode="before", check_fields=False)
        @classmethod
        def normalise_case(cls, v):
            if isinstance(v, str):
                return cats_map.get(v.lower(), v)
            return v

    fields = {"primary": (cat_type, ...), "secondary": (cat_type, ...)}
    if include_reasoning:
        fields["reasoning"] = (str, ...)
    return create_model("ClassificationSchema", __base__=_Base, **fields)

ClassificationSchema = make_schema(END_PRODUCT_CATS, INCLUDE_REASONING)
print(f"Schema built: {END_PRODUCT_CATS}")

client = anthropic.Anthropic(api_key=os.getenv("CLAUDE_API_KEY"))

def classify_patent(title, abstract, system_prompt):
    user_message = f"Title: {title}\n\nAbstract: {abstract}"
    response = client.messages.parse(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        temperature=TEMPERATURE,
        timeout=REQUEST_TIMEOUT,
        system=[
            {
                "type": "text",
                "text": system_prompt,
                "cache_control": {"type": "ephemeral"}
            }
        ],
        messages=[
            {"role": "user", "content": user_message}
        ],
        output_format=ClassificationSchema,
    )
    return response.parsed_output

Schema built: ['Meat', 'Fish and seafood', 'Milk and milk proteins', 'Yoghurt and fermented dairy', 'Cheese', 'Cream and ice cream', 'Agnostic', 'Chocolate, desserts, and confectionery', 'Eggs and egg proteins', 'Cross-cutting', 'Spreads, sauces, and condiments', 'Dairy']

### 7. Error Handling with Retry

In [65]:
def is_retryable_error(exc: Exception) -> bool:
    markers = ["503", "UNAVAILABLE", "RESOURCE_EXHAUSTED", "429",
               "TIMEOUT", "TIMED OUT", "READTIMEOUT", "CONNECTTIMEOUT"]
    return any(m in str(exc).upper() for m in markers)

def retry_sleep_seconds(attempt: int) -> float:
    sleep = min(RETRY_MAX_SECONDS, RETRY_BASE_SECONDS * (2 ** attempt))
    jitter = random.uniform(0.0, min(3.0, sleep * 0.2))
    return sleep + jitter

In [66]:
def classify_with_error_handling(row, system_prompt):
    pat_id = row["id"]
    last_error = None
    for attempt in range(MAX_RETRIES + 1):
        try:
            result = classify_patent(row["title"], row["abstract"], system_prompt)
            if result is None:
                print(f"  Parse failed for {pat_id}: model returned no structured output")
                return {"id": pat_id, "status": "parse_error", "error": "no structured output"}
            output = {f"{k}_LLM": v for k, v in result.model_dump().items()}
            output["id"] = pat_id
            output["status"] = "ok"
            return output
        except anthropic.APIError as e:
            last_error = e
            if attempt >= MAX_RETRIES:
                break
            if is_retryable_error(e):
                sleep_s = retry_sleep_seconds(attempt)
                print(f"  Retryable error (attempt {attempt + 1}/{MAX_RETRIES}): {e}. Sleeping {sleep_s:.1f}s.")
                time.sleep(sleep_s)
            else:
                break
    print(f"  API error for {pat_id}: {last_error}")
    return {"id": pat_id, "status": "api_error", "error": str(last_error)}

### 8. Checkpoint Helpers

In [67]:
def get_checkpoint_path(run_idx: int) -> Path:
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    return CHECKPOINT_DIR / f"run_{run_idx}_checkpoint.json"

def save_checkpoint(run_idx: int, completed_results: list) -> None:
    path = get_checkpoint_path(run_idx)
    payload = {
        "run_idx": run_idx,
        "completed_ids": [r["id"] for r in completed_results],
        "results": completed_results,
    }
    path.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")

def load_checkpoint(run_idx: int):
    path = get_checkpoint_path(run_idx)
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None

def delete_checkpoint(run_idx: int) -> None:
    path = get_checkpoint_path(run_idx)
    if path.exists():
        path.unlink()

### 9. Run on Test Data

In [68]:
all_results = []

for rep in range(REPETITIONS):
    run_idx = rep + 1
    print(f"\n{'='*50}\nRun {run_idx} / {REPETITIONS}\n{'='*50}")

    checkpoint = load_checkpoint(run_idx) if RESUME_INCOMPLETE else None
    if checkpoint:
        completed_results = checkpoint["results"]
        completed_ids = set(checkpoint["completed_ids"])
        print(f"  Resuming: {len(completed_ids)} records already processed.")
    else:
        completed_results, completed_ids = [], set()

    remaining = DATASET[~DATASET["id"].isin(completed_ids)]
    total = len(DATASET)

    for _, row in remaining.iterrows():
        n_done = len(completed_results)
        print(f"  [{n_done + 1}/{total}] {row['id']}")
        result = classify_with_error_handling(row, system_prompt)
        result["run"] = run_idx
        completed_results.append(result)
        save_checkpoint(run_idx, completed_results)
        if n_done + 1 < total:
            time.sleep(CALL_DELAY)

    delete_checkpoint(run_idx)
    all_results.extend(completed_results)

results_df = pd.DataFrame(all_results)
print(f"\nCompleted: {len(results_df)} records across {REPETITIONS} run(s)")
print(f"Successful: {(results_df['status'] == 'ok').sum()}")
print(f"Errors: {(results_df['status'] != 'ok').sum()}")
results_df

==================================================
Run 1 / 1
==================================================
  [1/104] JP-2025522935-A
  [2/104] US-20250176578-A1
  [3/104] US-20250098715-A1
  [4/104] US-20250241331-A1
  [5/104] EP-4514142-A1
  [6/104] NL-2031656-B1
  [7/104] WO-2023099270-A1
  [8/104] EP-4333632-A1
  [9/104] EP-3599885-A1
  [10/104] CN-121532076-A
  [11/104] EP-4656060-A1
  [12/104] JP-2025519945-A
  [13/104] FI-131418-B1
  [14/104] EP-4754246-A1
  [15/104] US-20190110501-A1
  [16/104] US-20250331537-A1
  [17/104] CN-121908951-A
  [18/104] US-12635717-B2
  [19/104] WO-2023009007-A1
  [20/104] EP-4547033-A1
  [21/104] WO-2025262298-A1
  [22/104] EP-4753472-A1
  [23/104] EP-4529772-A3
  [24/104] WO-2025157817-A1
  [25/104] EP-4358738-A1
  [26/104] GB-2641787-A
  [27/104] EP-4482328-A1
  [28/104] JP-2025502978-A
  [29/104] EP-4593632-A1
  [30/104] JP-2022506260-A
  [31/104] WO-2025056708-A1
  [32/104] US-20240148016-A1
  [33/104] EP-4597070-A1
  [34/104] EP-4661693-A1
  [35/104] EP-4615237-A1
  [36/104] US-20250000117-A1
  [37/104] WO-2025233496-A1
  [38/104] EP-4444100-A1
  [39/104] WO-2025048644-A1
  [40/104] US-20230058413-A1
  [41/104] US-20210161163-A1
  [42/104] DE-102024104639-A1
  [43/104] US-20250072442-A1
  [44/104] US-12588687-B2
  [45/104] EP-4683518-A1
  [46/104] EP-4580425-A1
  [47/104] US-20250057176-A1
  [48/104] EP-4626253-A1
  [49/104] WO-2025027571-A1
  [50/104] US-20250313784-A1
  [51/104] EP-4670510-A3
  [52/104] CN-121772846-A
  [53/104] US-20250248414-A1
  [54/104] JP-2024504597-A
  [55/104] US-12213500-B2
  [56/104] WO-2025114224-A1
  [57/104] CN-121057508-A
  [58/104] WO-2025127935-A1
  [59/104] US-20250148390-A1
  [60/104] MX-2026003171-A
  [61/104] EP-4638705-A1
  [62/104] EP-4304373-A2
  [63/104] EP-4554407-A1
  [64/104] EP-4735574-A1
  [65/104] CN-121285307-A
  [66/104] WO-2025247989-A1
  [67/104] EP-4551612-A1
  [68/104] JP-2026502106-A
  [69/104] US-20250287980-A1
  [70/104] EP-4132295-A1
  [71/104] SE-547148-C2
  [72/104] JP-2024073533-A
  [73/104] PE-20260032-A1
  [74/104] US-12295386-B2
  [75/104] US-20250040562-A1
  [76/104] JP-2025508391-A
  [77/104] US-20250098695-A1
  [78/104] EP-4669123-A1
  [79/104] EP-4561359-A1
  [80/104] FR-3144161-B1
  [81/104] US-20230389568-A1
  [82/104] CN-120187307-A
  [83/104] CN-121241072-A
  [84/104] US-20250351856-A1
  [85/104] WO-2025046140-A1
  [86/104] EP-4468867-A1
  [87/104] EP-4629831-A1
  [88/104] US-20200288737-A1
  [89/104] US-20250194637-A1
  [90/104] WO-2026027746-A1
  [91/104] US-20240180356-A1
  [92/104] EP-4637372-A1
  [93/104] US-12600940-B2
  [94/104] GB-2635339-A
  [95/104] CN-121794375-A
  [96/104] CN-120813257-A
  [97/104] EP-4451891-A1
  [98/104] EP-4672976-A1
  [99/104] US-20230165287-A1
  [100/104] US-20250280859-A1
  [101/104] WO-2025233389-A1
  [102/104] EP-4633378-A1
  [103/104] EP-4498836-A1
  [104/104] EP-3780964-A1

Completed: 104 records across 1 run(s)
Successful: 104
Errors: 0

,primary_LLM,secondary_LLM,reasoning_LLM,id,status,run
0,Milk and milk proteins,Agnostic,The patent describes a bioreactor apparatus an...,JP-2025522935-A,ok,1
1,Yoghurt and fermented dairy,Dairy,The patent explicitly describes a process for ...,US-20250176578-A1,ok,1
2,"Spreads, sauces, and condiments",Agnostic,The patent explicitly targets oat-based savour...,US-20250098715-A1,ok,1
3,Dairy,Yoghurt and fermented dairy,The patent describes methods for producing ani...,US-20250241331-A1,ok,1
4,Fish and seafood,Agnostic,The patent explicitly describes gel compositio...,EP-4514142-A1,ok,1
...,...,...,...,...,...,...
99,Fish and seafood,Cross-cutting,The patent explicitly describes a method of ma...,US-20250280859-A1,ok,1
100,Cross-cutting,Agnostic,This patent describes a food-use enzyme compos...,WO-2025233389-A1,ok,1
101,"Chocolate, desserts, and confectionery",Milk and milk proteins,The patent explicitly describes a chocolate pr...,EP-4633378-A1,ok,1
102,Cream and ice cream,Dairy,The patent explicitly targets vegan/non-dairy ...,EP-4498836-A1,ok,1
103,Cross-cutting,Agnostic,The patent describes a food-grade emulsion as ...,EP-3780964-A1,ok,1

In [69]:
result_cols = ["id", "run", "primary_LLM", "secondary_LLM", "status"]
if INCLUDE_REASONING:
    result_cols.append("reasoning_LLM")

comparison = DATASET[["id", "title", "abstract", "pillar", "endproduct"]].merge(
    results_df[result_cols], on="id", how="left"
)

comparison["primary_correct"] = comparison["endproduct"] == comparison["primary_LLM"]
comparison["either_correct"]  = (
    (comparison["endproduct"] == comparison["primary_LLM"]) |
    (comparison["endproduct"] == comparison["secondary_LLM"])
)

# Overall metrics
n = len(comparison)
print(f"Top-1 accuracy (primary match):  {comparison['primary_correct'].mean():.0%}  (n={n})")
print(f"Top-2 accuracy (either match):   {comparison['either_correct'].mean():.0%}  (n={n})")

# Per-category breakdown
cat_stats = (
    comparison.groupby("endproduct")
    .agg(
        n=("primary_correct", "count"),
        primary_correct=("primary_correct", "sum"),
        top2_correct=("either_correct", "sum"),
    )
    .assign(
        primary_acc=lambda d: (d["primary_correct"] / d["n"]).map("{:.0%}".format),
        top2_acc=lambda d: (d["top2_correct"] / d["n"]).map("{:.0%}".format),
    )
)
display(cat_stats)

# Detail table
display_cols = ["id", "title", "abstract", "pillar", "endproduct",
                "primary_LLM", "secondary_LLM"]
if INCLUDE_REASONING:
    display_cols.append("reasoning_LLM")
display_cols += ["primary_correct", "either_correct"]
comparison[display_cols]

Top-1 accuracy (primary match):  93%  (n=104)
Top-2 accuracy (either match):   99%  (n=104)

,n,primary_correct,top2_correct,primary_acc,top2_acc
endproduct,,,,,
Agnostic,14,12,14,86%,100%
Cheese,7,7,7,100%,100%
"Chocolate, desserts, and confectionery",10,10,10,100%,100%
Cream and ice cream,10,10,10,100%,100%
Cross-cutting,15,11,15,73%,100%
Dairy,6,5,5,83%,83%
Eggs and egg proteins,7,7,7,100%,100%
Fish and seafood,9,9,9,100%,100%
Meat,9,9,9,100%,100%
Milk and milk proteins,4,4,4,100%,100%
"Spreads, sauces, and condiments",4,4,4,100%,100%
Yoghurt and fermented dairy,9,9,9,100%,100%

,id,title,abstract,pillar,endproduct,primary_LLM,secondary_LLM,reasoning_LLM,primary_correct,either_correct
0,JP-2025522935-A,Pulsatile flow culture of mammary cell types f...,The apparatus and method for in vitro milk pro...,CM,Milk and milk proteins,Milk and milk proteins,Agnostic,The patent describes a bioreactor apparatus an...,True,True
1,US-20250176578-A1,PROCESS FOR PREPARING FERMENTED DAIRY PRODUCT ...,The invention relates to a process for prepari...,CC,Yoghurt and fermented dairy,Yoghurt and fermented dairy,Dairy,The patent explicitly describes a process for ...,True,True
2,US-20250098715-A1,METHOD FOR PREPARING OAT-BASED CONDIMENTS,The present invention relates to a method for ...,PB,"Spreads, sauces, and condiments","Spreads, sauces, and condiments",Agnostic,The patent explicitly targets oat-based savour...,True,True
3,US-20250241331-A1,ANIMAL-FREE SUBSTITUTE DAIRY FOOD PRODUCTS AND...,Methods of producing substitute dairy food pro...,F,Dairy,Dairy,Yoghurt and fermented dairy,The patent describes methods for producing ani...,True,True
4,EP-4514142-A1,GEL COMPOSITIONS AND THEIR USE IN SEAFOOD ANAL...,The present disclosure relates generally to ge...,CC,Fish and seafood,Fish and seafood,Agnostic,The patent explicitly describes gel compositio...,True,True
...,...,...,...,...,...,...,...,...,...,...
99,US-20250280859-A1,METHOD OF MAKING A SEAFOOD ANALOGUE,The present invention relates to a method of m...,PB,Fish and seafood,Fish and seafood,Cross-cutting,The patent explicitly describes a method of ma...,True,True
100,WO-2025233389-A1,STABILIZED LIQUID DEAMIDASE COMPOSITIONS,The invention provides methods for stabilizing...,PB,Cross-cutting,Cross-cutting,Agnostic,This patent describes a food-use enzyme compos...,True,True
101,EP-4633378-A1,CHOCOLATE COMPOSITION COMPRISING OMEGA-3-FATTY...,The present invention relates to a chocolate p...,PB,"Chocolate, desserts, and confectionery","Chocolate, desserts, and confectionery",Milk and milk proteins,The patent explicitly describes a chocolate pr...,True,True
102,EP-4498836-A1,VEGAN CREAMS AND ICE CREAMS,"The present invention relates to a vegan, non-...",PB,Cream and ice cream,Cream and ice cream,Dairy,The patent explicitly targets vegan/non-dairy ...,True,True
103,EP-3780964-A1,EMULSION FOR MODULATING SENSORY PROPERTIES IN ...,The present invention relates to the flavour i...,PB,Cross-cutting,Cross-cutting,Agnostic,The patent describes a food-grade emulsion as ...,True,True

### 10. Save to Excel for Prompt Debugging

Order of working:
1. Create a new version folder in `1_prompt_debugging/`.
2. Copy in the previous prompt, label with the new version number, make updates.
3. Edit step 10 output directory and step 5 prompt/dataset selection.
4. Run steps 5–10.
5. Manually review results.
6. Document what changed and why. Repeat from step 1.

In [70]:
save_dir = Path(f"{PROMPT_VERSION}")
save_dir.mkdir(parents=True, exist_ok=True)

summary_df = pd.DataFrame([
    {"metric": "top1_accuracy", "value": f"{comparison['primary_correct'].mean():.0%}", "n": n},
    {"metric": "top2_accuracy", "value": f"{comparison['either_correct'].mean():.0%}",  "n": n},
])

out_path = save_dir / f"{PROMPT_VERSION}_{MODEL}_results.xlsx"
with pd.ExcelWriter(out_path) as writer:
    comparison[display_cols].to_excel(writer, sheet_name="results",     index=False)
    cat_stats.to_excel(             writer, sheet_name="by_category")
    summary_df.to_excel(            writer, sheet_name="summary",       index=False)

print(f"Saved to {out_path}")

Saved to v3\v3_claude-sonnet-4-6_results.xlsx

In [ ]:
# Create dataset of only rows where LLM got scope wrong, for re-run with modified prompt
incorrect_ids = comparison.loc[~comparison["correct_scope"], "id"]
incorrect_scope_data = DATASET[DATASET["id"].isin(incorrect_ids)].reset_index(drop=True)
incorrect_scope_data