# GenAI Pipeline — Testing Notebook

LLM-based screening of publications for research category classification.
Uses Claude with prompt caching via the Anthropic Python SDK.

### 1. Imports and Configuration

In [4]:
import duckdb
import pandas as pd
import json
import random
import time
import anthropic
import os
from pathlib import Path
from dotenv import load_dotenv
from pydantic import BaseModel, Field, field_validator
from typing import Literal
from pydantic import create_model

load_dotenv()

DB_PATH = "../../patents_training.db"
OUTPUT_DIR = Path(".")
RAW_SUBS_DIR = Path("raw_subsets")

### 2. Data Inspection

In [7]:
con = duckdb.connect(DB_PATH, read_only=True)
print("Tables:")
print(con.sql("SHOW TABLES").df())

df_raw = con.sql("SELECT * FROM patents_raw").df()   # ← UPDATE: table name
con.close()

Tables:
                 name
0  patents_embeddings
1         patents_raw

In [8]:
df = df_raw[
    (df_raw["scope"] == "in") &
    (df_raw["research_category"].notna()) &
    (df_raw["research_category"] != "")
].reset_index(drop=True)

print(f"Raw shape: {df_raw.shape}")
print(f"Filtered shape (scope=in, research_category not empty): {df.shape}")
print(f"\nColumns: {list(df.columns)}")
print(f"\nResearch category distribution:")
print(df["research_category"].value_counts())
df.head()

Raw shape: (2450, 15)
Filtered shape (scope=in, research_category not empty): (1275, 15)

Columns: ['id', 'family_id', 'application_number', 'title', 'abstract', 'cpc', 'publication_year', 'jurisdiction', 'scope', 'pillar', 'subpillar', 'research_category', 'endproduct', 'ingredient', 'truncated']

Research category distribution:
research_category
End product formulation      445
Ingredient optimisation      437
Texturization methods        114
Bioprocess design            114
Strain development            45
Cell line development         35
Scaffolding                   34
Target molecule selection     28
Cell culture media            21
Crop development               2
Name: count, dtype: int64

,id,family_id,application_number,title,abstract,cpc,publication_year,jurisdiction,scope,pillar,subpillar,research_category,endproduct,ingredient,truncated
0,US-20170298457-A1,42829610,US15360298,LACTIC BACTERIUM WITH MODIFIED GALACTOKINASE E...,The present invention relates to a bacterial c...,"['A23C19/0323', 'C12N9/1205', 'A23C2220/206', ...",2017,US,in,PB,NaN,Strain development,Yoghurt and fermented dairy,NaN,False
1,EP-2473058-A1,42829610,EP10751643A,LACTIC BACTERIUM WITH MODIFIED GALACTOKINASE E...,The present invention relates to a bacterial c...,"['A23C19/0323', 'C12R2001/46', 'C12Y207/01006'...",2012,EP,in,PB,NaN,Strain development,Yoghurt and fermented dairy,NaN,False
2,EP-4424172-A3,52462090,EP24182765.8,A PROTEINACEOUS MEAT ANALOGUE HAVING AN IMPROV...,The invention concerns an extended shelf-life ...,"['A23V2002/00', 'A23V2200/20', 'A23J3/22', 'A2...",2025,EP,in,PB,NaN,End product formulation,Meat,NaN,False
3,US-11666069-B2,52462090,US17530304,Proteinaceous meat analogue having an improved...,An extended shelf-life proteinaceous meat anal...,"['A23J3/22', 'A23J3/18', 'A23V2200/20', 'A23V2...",2023,US,in,PB,NaN,End product formulation,Meat,NaN,False
4,EP-4627930-A3,52596486,EP25169128.3,VARIANTS OF CHYMOSIN WITH IMPROVED MILK-CLOTTI...,Variants of chymosin with improved milk-clotti...,"['A23C19/04', 'A23C19/041', 'C12N9/6483', 'A23...",2026,EP,in,PB,NaN,End product formulation,Cheese,NaN,False

In [9]:
df_pb = df[df["pillar"] == "PB"].reset_index(drop=True)
df_f  = df[df["pillar"] == "F"].reset_index(drop=True)
df_cm = df[df["pillar"] == "CM"].reset_index(drop=True)
df_cc = df[df["pillar"] == "CC"].reset_index(drop=True)

all_categories = sorted(df["research_category"].dropna().unique())
breakdown = pd.DataFrame(
    {pillar: grp["research_category"].value_counts().reindex(all_categories, fill_value=0)
     for pillar, grp in [("PB", df_pb), ("F", df_f), ("CM", df_cm), ("CC", df_cc)]},
    index=all_categories,
)
breakdown.index.name = "research_category"
breakdown["Total"] = breakdown.sum(axis=1)
breakdown

                            PB   F  CM  CC  Total
research_category
Bioprocess design            0  40  66   8    114
Cell culture media           0   0  21   0     21
Cell line development        0   0  35   0     35
Crop development             2   0   0   0      2
End product formulation    359  21  14  51    445
Ingredient optimisation    343  65   0  29    437
Scaffolding                  0   0  34   0     34
Strain development          29  16   0   0     45
Target molecule selection    0  28   0   0     28
Texturization methods       99   1   2  12    114

### 3. Balanced Subset Creation

Just taking as many as 10 from each research category within each pillar.

In [213]:
RANDOM_STATE=4

def create_balanced_sample(df, category_counts, random_state=RANDOM_STATE):
    """
    category_counts: dict mapping research_category -> n, e.g.
        {"Ingredient optimisation": 5, "End product formulation": 3, "Other": 2}
    Categories with no matching rows are skipped with a warning.
    If n exceeds available rows, all available rows are taken (with a warning).
    """
    samples = []
    for cat, n in category_counts.items():
        subset = df[df["research_category"] == cat]
        available = len(subset)
        if available == 0:
            print(f"  Warning: '{cat}' — no rows found, skipping.")
            continue
        if n > available:
            print(f"  Warning: '{cat}' — requested {n} but only {available} available, taking all.")
            n = available
        samples.append(subset.sample(n=n, random_state=random_state))
    combined = pd.concat(samples, ignore_index=True)
    return combined.sample(frac=1, random_state=random_state).reset_index(drop=True)

In [215]:
test_data_PB = create_balanced_sample(df_pb, {
    "Bioprocess design": 10,
    "Cell culture media": 10,
    "Cell line development": 10,
    "Consumer & market research": 10,
    "Crop development": 10,
    "End product formulation": 10,
    "Feedstocks": 10,
    "Food safety & quality": 10,
    "Health & nutrition": 10,
    "Impact assessments": 10,
    "Ingredient optimisation": 10,
    "Other": 10,
    "Scaffolding": 10,
    "Strain development": 10,
    "Target molecule selection": 10,
    "Texturization methods": 10,
}, random_state=RANDOM_STATE)
print(f"test_data_PB: {test_data_PB.shape}")
# test_data_PB[["id", "title", "scope", "pillar"]]

  Warning: 'Bioprocess design' — no rows found, skipping.
  Warning: 'Cell culture media' — no rows found, skipping.
  Warning: 'Cell line development' — no rows found, skipping.
  Warning: 'Consumer & market research' — no rows found, skipping.
  Warning: 'Crop development' — no rows found, skipping.
  Warning: 'Feedstocks' — no rows found, skipping.
  Warning: 'Food safety & quality' — no rows found, skipping.
  Warning: 'Health & nutrition' — no rows found, skipping.
  Warning: 'Impact assessments' — no rows found, skipping.
  Warning: 'Other' — no rows found, skipping.
  Warning: 'Scaffolding' — no rows found, skipping.
  Warning: 'Target molecule selection' — no rows found, skipping.
test_data_PB: (40, 15)

In [214]:
test_data_F = create_balanced_sample(df_f, {
    "Bioprocess design": 10,
    "Cell culture media": 10,
    "Cell line development": 10,
    "Consumer & market research": 10,
    "Crop development": 10,
    "End product formulation": 10,
    "Feedstocks": 10,
    "Food safety & quality": 10,
    "Health & nutrition": 10,
    "Impact assessments": 10,
    "Ingredient optimisation": 10,
    "Other": 10,
    "Scaffolding": 10,
    "Strain development": 10,
    "Target molecule selection": 10,
    "Texturization methods": 10,
}, random_state=RANDOM_STATE)
print(f"test_data_F: {test_data_F.shape}")
# test_data_F[["id", "title", "scope", "pillar"]]

  Warning: 'Cell culture media' — no rows found, skipping.
  Warning: 'Cell line development' — no rows found, skipping.
  Warning: 'Consumer & market research' — no rows found, skipping.
  Warning: 'Crop development' — no rows found, skipping.
  Warning: 'Feedstocks' — no rows found, skipping.
  Warning: 'Food safety & quality' — no rows found, skipping.
  Warning: 'Health & nutrition' — no rows found, skipping.
  Warning: 'Impact assessments' — no rows found, skipping.
  Warning: 'Other' — no rows found, skipping.
  Warning: 'Scaffolding' — no rows found, skipping.
  Warning: 'Texturization methods' — requested 10 but only 1 available, taking all.
test_data_F: (51, 15)

In [216]:
test_data_CM = create_balanced_sample(df_cm, {
    "Bioprocess design": 10,
    "Cell culture media": 10,
    "Cell line development": 10,
    "Consumer & market research": 10,
    "Crop development": 10,
    "End product formulation": 10,
    "Feedstocks": 10,
    "Food safety & quality": 10,
    "Health & nutrition": 10,
    "Impact assessments": 10,
    "Ingredient optimisation": 10,
    "Other": 10,
    "Scaffolding": 10,
    "Strain development": 10,
    "Target molecule selection": 10,
    "Texturization methods": 10,
}, random_state=RANDOM_STATE)
print(f"test_data_CM: {test_data_CM.shape}")
# test_data_CM[["id", "title", "scope", "pillar"]]

  Warning: 'Cell line development' — no rows found, skipping.
  Warning: 'Consumer & market research' — no rows found, skipping.
  Warning: 'Crop development' — no rows found, skipping.
  Warning: 'Feedstocks' — no rows found, skipping.
  Warning: 'Food safety & quality' — no rows found, skipping.
  Warning: 'Health & nutrition' — no rows found, skipping.
  Warning: 'Impact assessments' — no rows found, skipping.
  Warning: 'Ingredient optimisation' — no rows found, skipping.
  Warning: 'Other' — no rows found, skipping.
  Warning: 'Strain development' — no rows found, skipping.
  Warning: 'Target molecule selection' — no rows found, skipping.
  Warning: 'Texturization methods' — requested 10 but only 2 available, taking all.
test_data_CM: (42, 15)

In [217]:
test_data_CC = create_balanced_sample(df_cc, {
    "Bioprocess design": 10,
    "Cell culture media": 10,
    "Cell line development": 10,
    "Consumer & market research": 10,
    "Crop development": 10,
    "End product formulation": 10,
    "Feedstocks": 10,
    "Food safety & quality": 10,
    "Health & nutrition": 10,
    "Impact assessments": 10,
    "Ingredient optimisation": 10,
    "Other": 10,
    "Scaffolding": 10,
    "Strain development": 10,
    "Target molecule selection": 10,
    "Texturization methods": 10,
}, random_state=3)
print(f"test_data_CC: {test_data_CC.shape}")
# test_data_CC[["id", "title", "scope", "pillar"]]

  Warning: 'Bioprocess design' — requested 10 but only 8 available, taking all.
  Warning: 'Cell culture media' — no rows found, skipping.
  Warning: 'Cell line development' — no rows found, skipping.
  Warning: 'Consumer & market research' — no rows found, skipping.
  Warning: 'Crop development' — no rows found, skipping.
  Warning: 'Feedstocks' — no rows found, skipping.
  Warning: 'Food safety & quality' — no rows found, skipping.
  Warning: 'Health & nutrition' — no rows found, skipping.
  Warning: 'Impact assessments' — no rows found, skipping.
  Warning: 'Other' — no rows found, skipping.
  Warning: 'Scaffolding' — no rows found, skipping.
  Warning: 'Strain development' — no rows found, skipping.
  Warning: 'Target molecule selection' — no rows found, skipping.
test_data_CC: (38, 15)

### 4. Save Subsets to Excel
Allows manual check of files selected. Consider whether those in the test sets are borderline cases or clear cut.

In [218]:
################################################################################################
# PLEASE CHANGE FILENAME TO THE RANDOM SEED USED IN create_balanced_sample() FOR REPRODUCIBILITY
################################################################################################
def save_subset(df, filename, output_dir=RAW_SUBS_DIR):
    path = output_dir / filename
    df.to_csv(path, index=False)
    print(f"Saved {len(df)} records to {path}")

#save_subset(initial_test_data, "initial_test_data_rand3.xlsx")
save_subset(test_data_PB, f"rescat_test_data_PB_rand{RANDOM_STATE}.csv")
save_subset(test_data_CM, f"rescat_test_data_CM_rand{RANDOM_STATE}.csv")
save_subset(test_data_CC, f"rescat_test_data_CC_rand{RANDOM_STATE}.csv")
save_subset(test_data_F, f"rescat_test_data_F_rand{RANDOM_STATE}.csv")

Saved 40 records to raw_subsets\rescat_test_data_PB_rand4.csv
Saved 42 records to raw_subsets\rescat_test_data_CM_rand4.csv
Saved 38 records to raw_subsets\rescat_test_data_CC_rand4.csv
Saved 51 records to raw_subsets\rescat_test_data_F_rand4.csv

### 5. Load Prompt and Select Dataset

In [220]:
AP_PILLAR = "F"  # ← CHANGE THIS: "PB", "F", "CM", "CC"

# Read subset data from file
test_data_PB = pd.read_csv(f"raw_subsets/rescat_test_data_PB_rand{RANDOM_STATE}.csv")
test_data_F = pd.read_csv(f"raw_subsets/rescat_test_data_F_rand{RANDOM_STATE}.csv")
test_data_CM = pd.read_csv(f"raw_subsets/rescat_test_data_CM_rand{RANDOM_STATE}.csv")
test_data_CC = pd.read_csv(f"raw_subsets/rescat_test_data_CC_rand{RANDOM_STATE}.csv")

DATASETS = {
    "PB": test_data_PB,
    "F":  test_data_F,
    "CM": test_data_CM,
    "CC": test_data_CC,
}
DATASET = DATASETS[AP_PILLAR]
print(f"Pillar: {AP_PILLAR} | Dataset: {DATASET.shape[0]} records")

# ONLY USED AS REQUIRED FOR RE-RUN SPECIFIC PUBLICATIONS
#ids_to_test = ['pub.1190984789', 'pub.1196086614']
#DATASET = DATASET[DATASET["id"].isin(ids_to_test)]
#DATASET = incorrect_rescat_data

Pillar: F | Dataset: 51 records

In [221]:
PROMPT_VERSION = "v4"  # ← CHANGE THIS to switch prompt version
PROMPT_PATH = f"{AP_PILLAR}/{PROMPT_VERSION}/prompt_rescat_patents_{AP_PILLAR}_{PROMPT_VERSION}.md"

In [222]:
def load_prompt(path=PROMPT_PATH):
    with open(path, "r", encoding="utf-8") as f:
        prompt_text = f.read()
    return prompt_text.strip()

system_prompt = load_prompt()
print(system_prompt)

You are an expert in alternative proteins and food technology.

Your task is to classify a patent on fermentation-based alternative proteins into a research category based on its title and abstract.

Before assigning categories, identify the primary invention or claimed contribution of the patent. The 9 specific categories below (everything except Other) are reserved for patents where that topic is the primary claimed or described contribution. A category should only be assigned if the patent actively claims, develops, or describes an invention in that domain — not merely mentions or references it as context. For example:
- A patent claiming or disclosing a novel microbial strain or culture for biomass fermentation → Strain development (the strain is the invention, even if it produces a specific ingredient)
- A patent claiming expression of a recombinant food protein in a microbial host, or characterising a novel enzyme or functional protein for its specific molecular properties → Target molecule selection (the molecule or enzyme itself is the primary novelty, even if a production method is described alongside it)
- A patent where the PRIMARY NOVELTY is the PRODUCTION STEPS or PROCESS PROTOCOL — e.g. a specific heat treatment, fermentation protocol, or downstream processing sequence — rather than the molecule being produced → Bioprocess design (apply this when novel process steps are the invention, not merely the fact that a protein is produced recombinantly)
- A patent describing a novel waste stream or low-cost input as a fermentation substrate → Feedstocks
- A patent claiming a novel extrusion apparatus or process for a textured finished product → Texturization methods
- A patent describing a method applied to a single fermentation ingredient to improve its functional properties → Ingredient optimisation
- A patent where a specific ingredient has texturisation as its primary stated function (e.g. a protein extract for coagulation or gelling) → Texturization methods (not Ingredient optimisation)
- A patent describing a process where microbial or mycelial growth provides structural or scaffolding function → Bioprocess design (Scaffolding is not a separate category for fermentation patents)
- A patent claiming a finished product COMPOSITION (where texture or structure is a property of the formula) → End product formulation (not Texturization methods — reserve Texturization methods for patents whose primary claimed contribution is a PROCESS or APPARATUS for creating texture, not a product formula)

Never assign Other when a specific category clearly applies. Other is a last resort for patents where no specific category fits.

From the 10 research categories defined below, identify the top 2 categories that best capture the primary invention or claimed contribution of the patent, ranked from most to least central. Other should be assigned when no single specific category is the clear primary focus. Provide one extremely concise sentence of reasoning for your choice.

Research Categories:
- Feedstocks: Inventions for novel or alternative fermentation media and nutrient supply, including novel or alternative feedstocks (e.g. agricultural and industrial byproducts, waste streams, low-cost carbon and nitrogen sources, or flue gas, biogas, or syngas) to achieve higher efficiency, greater scalability, and reduced costs. Assign Feedstocks over Bioprocess Design when the primary novelty is the input material alone and no significant process design innovation is described alongside it — if both a novel feedstock and a production process are central to the patent, prefer Bioprocess design. Assign Feedstocks over Ingredient Optimisation when characterisation is conducted specifically to validate whether a novel feedstock produces acceptable quality output.
- Target molecule selection: Inventions for the identification and expression of specific proteins, enzymes, or other functional molecules for production via precision fermentation. Includes: engineering of host microbial strains to express a target molecule; identification and characterisation of naturally-occurring or wild-type enzymes and functional proteins (e.g. lipases, proteases, peptidases) where the enzyme's specific molecular properties (substrate selectivity, activity profile, specificity) are the primary claimed contribution; and recombinant expression of food proteins (e.g. collagen, caseins, whey proteins) where the molecule itself is the novelty. Assign this category when the target molecule or enzyme itself is the primary invention, regardless of whether a production method is also described. Does not include engineering aimed at improving cell growth or biomass properties, which is Strain development. When the primary novelty is the production STEPS or PROCESS PROTOCOL rather than the molecule, prefer Bioprocess design.
- Strain development: Inventions where a novel microbial strain or culture — including bacterial, yeast, or fungal strains — is the primary claimed or described contribution. Includes disclosure of novel or modified strains, methods for screening, selecting, and engineering strains to alter cell growth and functional properties (e.g. proliferation, stress tolerance, biomass composition, toxin reduction or elimination) via directed evolution, genetic engineering, or systematic screening across a library or population of candidates. The key marker is that the STRAIN OR CULTURE ITSELF is the primary innovation — its genetic makeup, properties, or selection from a population — regardless of its downstream application (e.g. producing an ingredient, controlling contaminants, improving fermented food products). Requires active modification of the organism itself or deliberate screening across multiple candidate strains. Does not include use of existing strains without modification. Does not include engineering to produce a specific recombinant molecule, which is Target Molecule Selection.
- Bioprocess design: Inventions in bioreactor design and fermentation process engineering aimed at improving the yield, efficiency, or scalability of production. Includes reactor architecture, aeration and mass transfer, monitoring and control systems, scale-up strategies, and downstream processing such as harvesting and purification. Also includes novel process protocols — such as solid-state fermentation methods, co-culture strategies, sequential fermentation protocols, and production pipeline steps (e.g. heat or enzymatic treatment in a production process) — where the primary innovation is the METHOD or PROCESS of production rather than the properties of the resulting ingredient. Also includes processes where microbial or mycelial growth is used as a structuring or scaffolding method. Assign Bioprocess design when the primary novelty is HOW the fermentation or production is conducted, even when the output is a specific molecule or ingredient. Does not include variation of cultivation conditions or nutrient regimes where the primary goal is improving ingredient properties, which is Ingredient Optimisation. Does not include improvements to media formulations or testing of novel feedstocks, which is Feedstocks.
- Ingredient optimisation: Inventions for the improvement of individual alternative protein ingredients — including single-cell proteins, mycoprotein, fermentation biomass, and recombinantly expressed proteins, lipids, and other functional components — through any upstream (cultivation conditions, nutrient regimes) or downstream (fractionation, processing, enzymatic treatment) approach where the primary goal is improving ingredient properties, not production yield or efficiency. Covers improvements to functional properties, sensory qualities, nutritional profile, and digestibility. Prefer over End Product Formulation when a single ingredient is the primary object of the invention. Does not cover production methods where the primary novelty is the process itself, which is Bioprocess design.
- End product formulation: Inventions for the design and assembly of finished alternative protein products, focused on product composition and properties. Covers multi-ingredient formulation decisions, fat integration, shelf-life and stability, and whole-product nutritional targets and fortification. Prefer this category over Ingredient Optimisation when a finished formulation is the primary object of the invention. A patent that claims a product COMPOSITION — where texture is one property of the claimed formula rather than the primary process innovation — belongs here, not in Texturization methods.
- Texturization methods: Inventions for process innovations or apparatus aimed at improving the texture of finished alternative protein products, including but not limited to extrusion, electrospinning, 3D printing, and enzymatic processing. Also includes ingredients specifically extracted or processed where the primary stated function is texturization (e.g. a protein extract for coagulation or gelling) — prefer Texturization methods over Ingredient optimisation when texturizing function is the primary purpose of the ingredient. Does not include methods for studying or modifying individual ingredients for non-texture purposes, which is Ingredient Optimisation.
- Food safety & quality: Inventions for improving or ensuring the safety and quality of fermentation-derived alternative protein ingredients and products, including novel preservation methods, antimicrobial treatments, allergen detection or reduction methods, and novel analytical methods or assays for quality or regulatory compliance. Does not include the assessment of process safety, occupational safety, or environmental safety of manufacturing facilities, cleaning protocols, or equipment maintenance.
- Health & nutrition: Inventions specifically designed to improve the nutritional composition, digestibility, or health-relevant properties of fermentation-derived alternative protein ingredients or products — such as novel processes to reduce anti-nutritional factors, increase protein digestibility or bioavailability, enhance micronutrient content, or achieve specific nutritional targets. Does not include general nutritional characterisation or profiling conducted as part of ingredient or product development, which belongs in Ingredient Optimisation or End Product Formulation.
- Other: Catch-all for patents that do not cleanly fit into the specific categories above, including: patents spanning multiple categories without a clear dominant focus; patents describing general fermentation or manufacturing infrastructure not specific to alternative protein production; patents covering packaging, distribution, or storage of alternative protein products; and inventions not covered by the other categories.

### 6. API Call with Prompt Caching

In [223]:
# API config

# Anthropic model options — pricing as of 2026-06-10.
# Verify at https://www.anthropic.com/pricing if costs may have changed.
# Model                  Input $/1M   Output $/1M   Context
# claude-haiku-4-5         $1.00         $5.00       200K
# claude-sonnet-4-6        $3.00        $15.00       1M
# claude-opus-4-8          $5.00        $25.00       1M
MODELS = {
    "haiku":  "claude-haiku-4-5",
    "sonnet": "claude-sonnet-4-6",
    "opus":   "claude-opus-4-8",
}
MODEL = MODELS["sonnet"]  # ← change this to switch model

MAX_TOKENS = 512         # max tokens in response; adjust based on expected reasoning length and cost tolerance
TEMPERATURE = 0.0        # 0.0 = deterministic; raise to ~0.3 to sample variance across REPETITIONS
CALL_DELAY = 1.0         # seconds between API calls
REQUEST_TIMEOUT = 120    # seconds before giving up on a single API call
MAX_RETRIES = 6          # retry attempts on rate-limit / transient errors
RETRY_BASE_SECONDS = 5.0  # exponential backoff base
RETRY_MAX_SECONDS = 90.0  # cap on backoff sleep

REPETITIONS = 1  # number of full runs; increase to measure output variance across runs

# ================================================================
# CHECKPOINT CONFIG
# Saves progress after each record; a run interrupted mid-way can
# be resumed without re-processing completed records.
# Set RESUME_INCOMPLETE = False to always start from scratch.
# ================================================================
CHECKPOINT_DIR = Path("checkpoints")
RESUME_INCOMPLETE = True

In [224]:
# ================================================================
# REASONING TOGGLE
# Keep True during testing — reasoning shows WHY the model decides
# as it does, which is essential for evaluating prompt quality.
# Set to False for production runs once the prompt is validated,
# to reduce token usage.
# ================================================================
INCLUDE_REASONING = True

PB_CATS = ["Crop development", "Strain development", "Ingredient optimisation", "End product formulation", "Texturization methods", "Food safety & quality", "Health & nutrition", "Other"]
F_CATS  = ["Feedstocks", "Target molecule selection", "Strain development", "Bioprocess design", "Ingredient optimisation", "End product formulation", "Texturization methods", "Food safety & quality", "Health & nutrition", "Other"]
CM_CATS = ["Cell line development", "Cell culture media", "Bioprocess design", "Scaffolding", "End product formulation", "Food safety & quality", "Health & nutrition", "Other"]
CC_CATS = ["Bioprocess design", "Scaffolding", "Ingredient optimisation", "End product formulation", "Texturization methods", "Food safety & quality", "Health & nutrition", "Other"]

PILLAR_CATS = {"PB": PB_CATS, "F": F_CATS, "CM": CM_CATS, "CC": CC_CATS}

def make_schema(cats, include_reasoning):
    # The LLM sometimes returns title-case values (e.g. "Health & Nutrition") while
    # our Literal expects sentence case. cats_map allows case-insensitive lookup so
    # the field_validator can normalise the value before Pydantic validates it.
    cats_map = {c.lower(): c for c in cats}
    cat_type = Literal[*cats]

    class _Base(BaseModel):
        # check_fields=False because "primary"/"secondary" are added by create_model, not defined here
        @field_validator("primary", "secondary", mode="before", check_fields=False)
        @classmethod
        def normalise_case(cls, v):
            if isinstance(v, str):
                return cats_map.get(v.lower(), v)
            return v

    fields = {"primary": (cat_type, ...), "secondary": (cat_type, ...)}
    if include_reasoning:
        fields["reasoning"] = (str, ...)
    return create_model("ClassificationSchema", __base__=_Base, **fields)

ClassificationSchema = make_schema(PILLAR_CATS[AP_PILLAR], INCLUDE_REASONING)
print(f"Schema built for {AP_PILLAR}: {list(PILLAR_CATS[AP_PILLAR])}")

client = anthropic.Anthropic(api_key=os.getenv("CLAUDE_API_KEY"))

def classify_publication(title, abstract, system_prompt):
    user_message = f"Title: {title}\n\nAbstract: {abstract}"
    response = client.messages.parse(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        temperature=TEMPERATURE,
        timeout=REQUEST_TIMEOUT,
        system=[
            {
                "type": "text",
                "text": system_prompt,
                "cache_control": {"type": "ephemeral"}
            }
        ],
        messages=[
            {"role": "user", "content": user_message}
        ],
        output_format=ClassificationSchema,
    )
    return response.parsed_output

Schema built for F: ['Feedstocks', 'Target molecule selection', 'Strain development', 'Bioprocess design', 'Ingredient optimisation', 'End product formulation', 'Texturization methods', 'Food safety & quality', 'Health & nutrition', 'Other']

In [225]:
def is_retryable_error(exc: Exception) -> bool:
    markers = ["503", "UNAVAILABLE", "RESOURCE_EXHAUSTED", "429",
               "TIMEOUT", "TIMED OUT", "READTIMEOUT", "CONNECTTIMEOUT"]
    return any(m in str(exc).upper() for m in markers)

def retry_sleep_seconds(attempt: int) -> float:
    sleep = min(RETRY_MAX_SECONDS, RETRY_BASE_SECONDS * (2 ** attempt))
    jitter = random.uniform(0.0, min(3.0, sleep * 0.2))
    return sleep + jitter

### 7. Error Handling with Retry

In [226]:
def classify_with_error_handling(row, system_prompt):
    pub_id = row["id"]
    last_error = None
    for attempt in range(MAX_RETRIES + 1):
        try:
            result = classify_publication(row["title"], row["abstract"], system_prompt)
            if result is None:
                print(f"  Parse failed for {pub_id}: model returned no structured output")
                return {"id": pub_id, "status": "parse_error", "error": "no structured output"}
            output = {f"{k}_LLM": v for k, v in result.model_dump().items()} # rename columns / keys to indicate LLM output
            output["id"] = pub_id
            output["status"] = "ok"
            return output
        except anthropic.APIError as e:
            last_error = e
            if attempt >= MAX_RETRIES:
                break
            if is_retryable_error(e):
                sleep_s = retry_sleep_seconds(attempt)
                print(f"  Retryable error (attempt {attempt + 1}/{MAX_RETRIES}): {e}. Sleeping {sleep_s:.1f}s.")
                time.sleep(sleep_s)
            else:
                break
    print(f"  API error for {pub_id}: {last_error}")
    return {"id": pub_id, "status": "api_error", "error": str(last_error)}

### 8. Checkpoint Helpers

In [227]:
def get_checkpoint_path(run_idx: int) -> Path:
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    return CHECKPOINT_DIR / f"run_{run_idx}_checkpoint.json"

def save_checkpoint(run_idx: int, completed_results: list) -> None:
    path = get_checkpoint_path(run_idx)
    payload = {
        "run_idx": run_idx,
        "completed_ids": [r["id"] for r in completed_results],
        "results": completed_results,
    }
    path.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")

def load_checkpoint(run_idx: int):
    path = get_checkpoint_path(run_idx)
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None

def delete_checkpoint(run_idx: int) -> None:
    path = get_checkpoint_path(run_idx)
    if path.exists():
        path.unlink()

### 9. Run on Test Data

In [228]:
all_results = []

for rep in range(REPETITIONS):
    run_idx = rep + 1
    print(f"\n{'='*50}\nRun {run_idx} / {REPETITIONS}\n{'='*50}")

    checkpoint = load_checkpoint(run_idx) if RESUME_INCOMPLETE else None
    if checkpoint:
        completed_results = checkpoint["results"]
        completed_ids = set(checkpoint["completed_ids"])
        print(f"  Resuming: {len(completed_ids)} records already processed.")
    else:
        completed_results, completed_ids = [], set()

    remaining = DATASET[~DATASET["id"].isin(completed_ids)]
    total = len(DATASET)

    for _, row in remaining.iterrows():
        n_done = len(completed_results)
        print(f"  [{n_done + 1}/{total}] {row['id']}")
        result = classify_with_error_handling(row, system_prompt)
        result["run"] = run_idx
        completed_results.append(result)
        save_checkpoint(run_idx, completed_results)
        if n_done + 1 < total:
            time.sleep(CALL_DELAY)

    delete_checkpoint(run_idx)
    all_results.extend(completed_results)

results_df = pd.DataFrame(all_results)
print(f"\nCompleted: {len(results_df)} records across {REPETITIONS} run(s)")
print(f"Successful: {(results_df['status'] == 'ok').sum()}")
print(f"Errors: {(results_df['status'] != 'ok').sum()}")
results_df

==================================================
Run 1 / 1
==================================================
  [1/51] AR-130716-A1
  [2/51] BE-1031980-B1
  [3/51] FR-3158214-A1
  [4/51] GB-2603227-A
  [5/51] EP-3897693-A1
  [6/51] ES-2975155-A1
  [7/51] WO-2025073700-A1
  [8/51] EP-4533954-A1
  [9/51] GB-2641787-A
  [10/51] EP-4451897-A1
  [11/51] KR-20250012647-A
  [12/51] CL-2026000434-A1
  [13/51] JP-2025533662-A
  [14/51] WO-2025252839-A1
  [15/51] US-20250134121-A1
  [16/51] EP-4754234-A1
  [17/51] US-12495812-B2
  [18/51] US-20250241331-A1
  [19/51] SE-2430062-A1
  [20/51] JP-2026513110-A
  [21/51] EP-4368027-A1
  [22/51] US-11673940-B2
  [23/51] US-20230080653-A1
  [24/51] FR-3158212-A1
  [25/51] WO-2025229303-A1
  [26/51] US-12600940-B2
  [27/51] US-20250027033-A1
  [28/51] EP-4507513-A1
  [29/51] US-20250340825-A1
  [30/51] GB-2595643-A
  [31/51] EP-4298912-A1
  [32/51] JP-2026501609-A
  [33/51] EP-4476349-A2
  [34/51] US-20240247227-A1
  [35/51] US-20250206792-A1
  [36/51] EP-4642904-A1
  [37/51] US-12588687-B2
  [38/51] GB-2634922-A
  [39/51] EP-4276170-A1
  [40/51] WO-2025229117-A1
  [41/51] EP-4626251-A1
  [42/51] NL-2037130-B1
  [43/51] FI-131623-B1
  [44/51] EP-4658754-A1
  [45/51] EP-4456738-A1
  [46/51] EP-4522722-A1
  [47/51] EP-4637363-A1
  [48/51] WO-2025181163-A1
  [49/51] DE-102023125145-A1
  [50/51] DE-102022201682-B4
  [51/51] WO-2025133158-A3

Completed: 51 records across 1 run(s)
Successful: 51
Errors: 0

,primary_LLM,secondary_LLM,reasoning_LLM,id,status,run
0,Target molecule selection,Ingredient optimisation,The patent's primary novelty is the recombinan...,AR-130716-A1,ok,1
1,Bioprocess design,End product formulation,The patent's primary contribution is a novel m...,BE-1031980-B1,ok,1
2,End product formulation,Bioprocess design,The patent centers on a new food product based...,FR-3158214-A1,ok,1
3,Bioprocess design,Feedstocks,The patent's primary contribution is a system ...,GB-2603227-A,ok,1
4,Target molecule selection,Health & nutrition,The patent's primary contribution is the ident...,EP-3897693-A1,ok,1
5,End product formulation,Health & nutrition,The patent claims a finished meat analogue pro...,ES-2975155-A1,ok,1
6,Texturization methods,Target molecule selection,The patent's primary contribution is a cold-ge...,WO-2025073700-A1,ok,1
7,Target molecule selection,Bioprocess design,The patent centers on producing casein (a spec...,EP-4533954-A1,ok,1
8,End product formulation,Bioprocess design,The patent primarily claims a finished vegan y...,GB-2641787-A,ok,1
9,End product formulation,Texturization methods,The patent claims a specific composition of te...,EP-4451897-A1,ok,1
10,End product formulation,Texturization methods,The patent claims a whole-cut mycelial substit...,KR-20250012647-A,ok,1
11,Ingredient optimisation,Feedstocks,The patent claims a yeast SCP composition with...,CL-2026000434-A1,ok,1
12,Target molecule selection,Ingredient optimisation,The patent centers on Ogataea polymorpha as a ...,JP-2025533662-A,ok,1
13,End product formulation,Texturization methods,The patent describes a method for preparing a ...,WO-2025252839-A1,ok,1
14,Strain development,Food safety & quality,The patent discloses novel Lactiplantibacillus...,US-20250134121-A1,ok,1
15,Strain development,Target molecule selection,The patent's primary contribution is a novel M...,EP-4754234-A1,ok,1
16,Target molecule selection,End product formulation,The patent's primary contribution is the ident...,US-12495812-B2,ok,1
17,End product formulation,Target molecule selection,The patent describes methods for producing ani...,US-20250241331-A1,ok,1
18,Bioprocess design,Target molecule selection,The primary invention is a novel multi-step pr...,SE-2430062-A1,ok,1
19,Ingredient optimisation,Bioprocess design,The patent describes a method for obtaining ye...,JP-2026513110-A,ok,1
20,Bioprocess design,Feedstocks,The primary invention is a fermentation proces...,EP-4368027-A1,ok,1
21,Target molecule selection,Bioprocess design,The patent centers on recombinant production o...,US-11673940-B2,ok,1
22,End product formulation,Texturization methods,The patent describes a finished edible formula...,US-20230080653-A1,ok,1
23,End product formulation,Bioprocess design,The patent centers on a new food product based...,FR-3158212-A1,ok,1
24,End product formulation,Texturization methods,The patent claims a finished vegan mozzarella-...,WO-2025229303-A1,ok,1
25,Strain development,Bioprocess design,The patent discloses a novel deposited bacteri...,US-12600940-B2,ok,1
26,Strain development,Ingredient optimisation,The patent's primary contribution is novel mod...,US-20250027033-A1,ok,1
27,Texturization methods,Ingredient optimisation,The patent's primary contribution is a process...,EP-4507513-A1,ok,1
28,Ingredient optimisation,Bioprocess design,The patent focuses on improving the mechanical...,US-20250340825-A1,ok,1
29,Strain development,Ingredient optimisation,The patent's primary contribution is novel mod...,GB-2595643-A,ok,1
30,End product formulation,Ingredient optimisation,The patent claims a finished milk/cream substi...,EP-4298912-A1,ok,1
31,Target molecule selection,Strain development,The patent's primary contribution is engineeri...,JP-2026501609-A,ok,1
32,Target molecule selection,End product formulation,The patent's primary novelty is the recombinan...,EP-4476349-A2,ok,1
33,Bioprocess design,Ingredient optimisation,The patent's primary contribution is a solid-s...,US-20240247227-A1,ok,1
34,Target molecule selection,Bioprocess design,The patent's primary contribution is the recom...,US-20250206792-A1,ok,1
35,Target molecule selection,Bioprocess design,The patent's primary contribution is the ident...,EP-4642904-A1,ok,1
36,Ingredient optimisation,Texturization methods,The patent describes a downstream processing m...,US-12588687-B2,ok,1
37,Bioprocess design,Feedstocks,The patent's primary contribution is a solid-s...,GB-2634922-A,ok,1
38,Bioprocess design,Strain development,The patent's primary contribution is a novel p...,EP-4276170-A1,ok,1
39,Strain development,Target molecule selection,The patent's primary contribution is a modifie...,WO-2025229117-A1,ok,1
40,Strain development,Bioprocess design,The patent centers on a specific fungal biomas...,EP-4626251-A1,ok,1
41,Ingredient optimisation,Strain development,The patent claims a microbial lipid compositio...,NL-2037130-B1,ok,1
42,Strain development,Bioprocess design,The patent centers on a specific fungal biomas...,FI-131623-B1,ok,1
43,Strain development,Ingredient optimisation,The patent's primary contribution is a novel C...,EP-4658754-A1,ok,1
44,Bioprocess design,End product formulation,The patent's primary contribution is a solid-s...,EP-4456738-A1,ok,1
45,Feedstocks,Bioprocess design,The primary invention is the use of brewer's s...,EP-4522722-A1,ok,1
46,Strain development,End product formulation,The patent centers on engineering a fungal org...,EP-4637363-A1,ok,1
47,Ingredient optimisation,Strain development,The patent claims a microbial lipid compositio...,WO-2025181163-A1,ok,1
48,Bioprocess design,Ingredient optimisation,The patent's primary contribution is a novel f...,DE-102023125145-A1,ok,1
49,Bioprocess design,End product formulation,The patent's primary novelty is a multi-step p...,DE-102022201682-B4,ok,1
50,Target molecule selection,Bioprocess design,The patent's primary contribution is the recom...,WO-2025133158-A3,ok,1

In [229]:
result_cols = ["id", "run", "primary_LLM", "secondary_LLM", "status"]
if INCLUDE_REASONING:
    result_cols.append("reasoning_LLM")

comparison = DATASET[["id", "title", "abstract", "pillar", "research_category"]].merge(
    results_df[result_cols], on="id", how="left"
)

comparison["primary_correct"] = comparison["research_category"] == comparison["primary_LLM"]
comparison["either_correct"]  = (
    (comparison["research_category"] == comparison["primary_LLM"]) |
    (comparison["research_category"] == comparison["secondary_LLM"])
)

# Overall metrics
n = len(comparison)
print(f"Top-1 accuracy (primary match):  {comparison['primary_correct'].mean():.0%}  (n={n})")
print(f"Top-2 accuracy (either match):   {comparison['either_correct'].mean():.0%}  (n={n})")

# Per-category breakdown
cat_stats = (
    comparison.groupby("research_category")
    .agg(
        n=("primary_correct", "count"),
        primary_correct=("primary_correct", "sum"),
        top2_correct=("either_correct", "sum"),
    )
    .assign(
        primary_acc=lambda d: (d["primary_correct"] / d["n"]).map("{:.0%}".format),
        top2_acc=lambda d: (d["top2_correct"] / d["n"]).map("{:.0%}".format),
    )
)
display(cat_stats)

# Detail table
display_cols = ["id", "title", "abstract", "pillar", "research_category",
                "primary_LLM", "secondary_LLM"]
if INCLUDE_REASONING:
    display_cols.append("reasoning_LLM")
display_cols += ["primary_correct", "either_correct"]
comparison[display_cols]

Top-1 accuracy (primary match):  76%  (n=51)
Top-2 accuracy (either match):   84%  (n=51)

,n,primary_correct,top2_correct,primary_acc,top2_acc
research_category,,,,,
Bioprocess design,10,8,10,80%,100%
End product formulation,10,10,10,100%,100%
Ingredient optimisation,10,4,5,40%,50%
Strain development,10,9,9,90%,90%
Target molecule selection,10,7,8,70%,80%
Texturization methods,1,1,1,100%,100%

,id,title,abstract,pillar,research_category,primary_LLM,secondary_LLM,reasoning_LLM,primary_correct,either_correct
0,AR-130716-A1,COMPOSITIONS AND APPLICATIONS DERIVED FROM OGA...,The disclosure provided herein relates to the ...,F,Ingredient optimisation,Target molecule selection,Ingredient optimisation,The patent's primary novelty is the recombinan...,False,True
1,BE-1031980-B1,FERMENTED FOOD PRODUCT AND PRODUCTION METHODS,"The invention relates to fermented foods, more...",F,Bioprocess design,Bioprocess design,End product formulation,The patent's primary contribution is a novel m...,True,True
2,FR-3158214-A1,FOOD PRODUCT BASED ON MICROALGAE,The invention relates to the production of a n...,F,Ingredient optimisation,End product formulation,Bioprocess design,The patent centers on a new food product based...,False,False
3,GB-2603227-A,System and method for cultivating and harvesti...,Disclosed is a system 100 for cultivating and ...,F,Bioprocess design,Bioprocess design,Feedstocks,The patent's primary contribution is a system ...,True,True
4,EP-3897693-A1,SYNTHETIC AND RECOMBINANT COLLAGEN PEPTIDES HA...,The invention relates to a synthetic or recomb...,F,Target molecule selection,Target molecule selection,Health & nutrition,The patent's primary contribution is the ident...,True,True
5,ES-2975155-A1,MEAT ANALOGUE FOOD COMPRISING MYCOPROTEINS AND...,Meat analogue food that includes mycoproteins ...,F,End product formulation,End product formulation,Health & nutrition,The patent claims a finished meat analogue pro...,True,True
6,WO-2025073700-A1,COLD GELLABLE RECOMBINANT BETA-LACTOGLOBULIN A...,The present invention relates to a method for ...,F,Ingredient optimisation,Texturization methods,Target molecule selection,The patent's primary contribution is a cold-ge...,False,False
7,EP-4533954-A1,METHOD FOR PRODUCING CASEIN AND USES THEREOF,The invention pertains to the food industry an...,F,Bioprocess design,Target molecule selection,Bioprocess design,The patent centers on producing casein (a spec...,False,True
8,GB-2641787-A,Foodstuff,A vegan yoghurt comprises a filamentous fungus...,F,End product formulation,End product formulation,Bioprocess design,The patent primarily claims a finished vegan y...,True,True
9,EP-4451897-A1,COMPOSITION COMPRISING TEXTURED FUNGAL PROTEIN...,The present invention relates to a composition...,F,End product formulation,End product formulation,Texturization methods,The patent claims a specific composition of te...,True,True
10,KR-20250012647-A,Mycelial substitute food and method for produc...,The present invention relates to a method for ...,F,End product formulation,End product formulation,Texturization methods,The patent claims a whole-cut mycelial substit...,True,True
11,CL-2026000434-A1,Single-cell protein products containing low le...,The present invention relates to a composition...,F,Ingredient optimisation,Ingredient optimisation,Feedstocks,The patent claims a yeast SCP composition with...,True,True
12,JP-2025533662-A,Compositions and additives derived from Ogatae...,[Problem] To provide a food composition that u...,F,Strain development,Target molecule selection,Ingredient optimisation,The patent centers on Ogataea polymorpha as a ...,False,False
13,WO-2025252839-A1,FOOD OR FEED PRODUCT,The present invention relates to a method for ...,F,End product formulation,End product formulation,Texturization methods,The patent describes a method for preparing a ...,True,True
14,US-20250134121-A1,PROTECTIVE CULTURES COMBINATION,The present invention relates to novel strains...,F,Strain development,Strain development,Food safety & quality,The patent discloses novel Lactiplantibacillus...,True,True
15,EP-4754234-A1,A NOVEL STRAIN OF METSCHNIKOWIA PULCHERRIMA AN...,The present invention provides novel strain of...,F,Strain development,Strain development,Target molecule selection,The patent's primary contribution is a novel M...,True,True
16,US-12495812-B2,"Lipases, compositions, methods and uses thereof","The present invention relates to a wild-type, ...",F,Ingredient optimisation,Target molecule selection,End product formulation,The patent's primary contribution is the ident...,False,False
17,US-20250241331-A1,ANIMAL-FREE SUBSTITUTE DAIRY FOOD PRODUCTS AND...,Methods of producing substitute dairy food pro...,F,End product formulation,End product formulation,Target molecule selection,The patent describes methods for producing ani...,True,True
18,SE-2430062-A1,Efficient production of recombinant casein,The present invention relates to a method for ...,F,Target molecule selection,Bioprocess design,Target molecule selection,The primary invention is a novel multi-step pr...,False,True
19,JP-2026513110-A,High-protein yeast products,This disclosure relates to a method for obtain...,F,Ingredient optimisation,Ingredient optimisation,Bioprocess design,The patent describes a method for obtaining ye...,True,True
20,EP-4368027-A1,PROCESS FOR THE MANUFACTURE OF FOOD PRODUCTS W...,The present invention refers to a process for ...,F,Ingredient optimisation,Bioprocess design,Feedstocks,The primary invention is a fermentation proces...,False,False
21,US-11673940-B2,Recombinant production of a collagen peptide p...,The present invention relates to a method for ...,F,Target molecule selection,Target molecule selection,Bioprocess design,The patent centers on recombinant production o...,True,True
22,US-20230080653-A1,MEAT SUBSTITUTE,"Described herein is an edible formulation, sui...",F,End product formulation,End product formulation,Texturization methods,The patent describes a finished edible formula...,True,True
23,FR-3158212-A1,FOOD PRODUCT BASED ON MICROALGAE,The invention relates to the production of a n...,F,End product formulation,End product formulation,Bioprocess design,The patent centers on a new food product based...,True,True
24,WO-2025229303-A1,VEGAN MOZZARELLA-LIKE CHEESE,"A foodstuff, for example a vegan, mozzarella-l...",F,End product formulation,End product formulation,Texturization methods,The patent claims a finished vegan mozzarella-...,True,True
25,US-12600940-B2,Strains and processes for single cell protein ...,A bacterial strain of the genus Xanthobacter a...,F,Strain development,Strain development,Bioprocess design,The patent discloses a novel deposited bacteri...,True,True
26,US-20250027033-A1,MODIFIED STRAINS OF CHLORELLA VULGARIS AND MET...,Disclosed are modified strains of Chlorella vu...,F,Strain development,Strain development,Ingredient optimisation,The patent's primary contribution is novel mod...,True,True
27,EP-4507513-A1,PROCESS FOR OBTAINING A TEXTURISING PROTEIN EX...,The present invention relates to a process for...,F,Texturization methods,Texturization methods,Ingredient optimisation,The patent's primary contribution is a process...,True,True
28,US-20250340825-A1,ENHANCED FUNGAL MATERIAL,The invention relates to enhanced fungal mats ...,F,Ingredient optimisation,Ingredient optimisation,Bioprocess design,The patent focuses on improving the mechanical...,True,True
29,GB-2595643-A,Modified strains of chlorella vulgaris and met...,Disclosed are modified strains of Chlorella vu...,F,Strain development,Strain development,Ingredient optimisation,The patent's primary contribution is novel mod...,True,True
30,EP-4298912-A1,FUNGAL MYCELIUM-BASED MILK OR CREAM SUBSTITUTE,[The present invention relates to a milk or cr...,F,End product formulation,End product formulation,Ingredient optimisation,The patent claims a finished milk/cream substi...,True,True
31,JP-2026501609-A,"Proteins, methods and systems for subcellular ...","The present disclosure provides proteins, meth...",F,Target molecule selection,Target molecule selection,Strain development,The patent's primary contribution is engineeri...,True,True
32,EP-4476349-A2,METHODS FOR PRODUCTION OF ANIMAL-FREE HONEY AN...,"Royal jelly honey produced by nurse bees, hone...",F,Target molecule selection,Target molecule selection,End product formulation,The patent's primary novelty is the recombinan...,True,True
33,US-20240247227-A1,A METHOD AND A SYSTEM FOR MANUFACTURING A PROT...,The present invention relates to a method for ...,F,Bioprocess design,Bioprocess design,Ingredient optimisation,The patent's primary contribution is a solid-s...,True,True
34,US-20250206792-A1,METHOD TO PRODUCE PHOSPHORYLATED MILK PROTEINS...,The present disclosure relates to methods for ...,F,Target molecule selection,Target molecule selection,Bioprocess design,The patent's primary contribution is the recom...,True,True
35,EP-4642904-A1,"PROTEINS, METHODS, AND SYSTEMS FOR SUBCELLULAR...","The present disclosure provides for proteins, ...",F,Target molecule selection,Target molecule selection,Bioprocess design,The patent's primary contribution is the ident...,True,True
36,US-12588687-B2,"Microbial cell product, method for obtaining s...",The present invention relates to a method for ...,F,Ingredient optimisation,Ingredient optimisation,Texturization methods,The patent describes a downstream processing m...,True,True
37,GB-2634922-A,Protein production method,A method suitable for producing a protein suit...,F,Bioprocess design,Bioprocess design,Feedstocks,The patent's primary contribution is a solid-s...,True,True
38,EP-4276170-A1,PSEUDO-SOLID STATE FERMENTATION OF FILAMENTOUS...,The present invention relates to methods of as...,F,Bioprocess design,Bioprocess design,Strain development,The patent's primary contribution is a novel p...,True,True
39,WO-2025229117-A1,YEAST FOR INCREASED LIPID PRODUCTION,The present invention relates to a Yarrowia li...,F,Strain development,Strain development,Target molecule selection,The patent's primary contribution is a modifie...,True,True
40,EP-4626251-A1,"FUNGAL BIOMASS, METHOD FOR THE PREPARATION AND...",Disclosed is a fungal biomass comprising one o...,F,Strain development,Strain development,Bioprocess design,The patent centers on a specific fungal biomas...,True,True
41,NL-2037130-B1,MICROBIAL LIPID COMPOSITION,MICROBIAL LIPID COMPOSITION ABSTRACT The curre...,F,Target molecule selection,Ingredient optimisation,Strain development,The patent claims a microbial lipid compositio...,False,False
42,FI-131623-B1,"FUNGAL BIOMASS, METHOD FOR THE PREPARATION AND...",Disclosed is a fungal biomass comprising one o...,F,Strain development,Strain development,Bioprocess design,The patent centers on a specific fungal biomas...,True,True
43,EP-4658754-A1,ALGAE BIOMASS,The invention relates to an algae biomass havi...,F,Strain development,Strain development,Ingredient optimisation,The patent's primary contribution is a novel C...,True,True
44,EP-4456738-A1,EDIBLE MYCELIATED COMPOSITION,The invention relates to a process for the pre...,F,Bioprocess design,Bioprocess design,End product formulation,The patent's primary contribution is a solid-s...,True,True
45,EP-4522722-A1,PRODUCTION OF A FUNGAL FERMENTATION MEDIUM FRO...,The present invention relates to a method for ...,F,Bioprocess design,Feedstocks,Bioprocess design,The primary invention is the use of brewer's s...,False,True
46,EP-4637363-A1,USE OF A FUNGAL PROTEIN COMPRISING AN OVER EXP...,The present invention relates to the use of a ...,F,Ingredient optimisation,Strain development,End product formulation,The patent centers on engineering a fungal org...,False,False
47,WO-2025181163-A1,MICROBIAL LIPID COMPOSITION,The current invention relates to a microbial l...,F,Target molecule selection,Ingredient optimisation,Strain development,The patent claims a microbial lipid compositio...,False,False
48,DE-102023125145-A1,Process for the fermentation of biomass,The present invention relates to a process for...,F,Bioprocess design,Bioprocess design,Ingredient optimisation,The patent's primary contribution is a novel f...,True,True
49,DE-102022201682-B4,Methods for producing food from fermented by-p...,A method for producing foodstuffs comprising t...,F,Bioprocess design,Bioprocess design,End product formulation,The patent's primary novelty is a multi-step p...,True,True
50,WO-2025133158-A3,METHOD TO PRODUCE PHOSPHORYLATED MILK PROTEINS...,The present disclosure relates to methods for ...,F,Target molecule selection,Target molecule selection,Bioprocess design,The patent's primary contribution is the recom...,True,True

### 10. Save to Excel for Prompt Debugging
To assess how well the prompt does at getting the LLM to assign scope and pillar, I need to save the comparison data, then manually review what went wrong and adjust the prompt.
None of this will make it into the final workflow.

Order of working:
1. Create a new version folder in the 1_prompt_debugging folder.
2. Copy in the previous prompt. Label it with the new version number. Make updates as required based on step 6.
3. Edit Step 10 output directory (this step) and Step 5 prompt selection and input data.
4. Run the script from steps 5-10.
5. Manually review the results. Includes both metrics and 
6. Write a text document about v1 results and what changes you want to make to the prompt. Repeat from step 1.

In [230]:
save_dir = Path(f"{AP_PILLAR}/{PROMPT_VERSION}")
save_dir.mkdir(parents=True, exist_ok=True)

summary_df = pd.DataFrame([
    {"metric": "top1_accuracy", "value": f"{comparison['primary_correct'].mean():.0%}", "n": n},
    {"metric": "top2_accuracy", "value": f"{comparison['either_correct'].mean():.0%}",  "n": n},
])

out_path = save_dir / f"{AP_PILLAR}_{PROMPT_VERSION}_{MODEL}_results.xlsx"
with pd.ExcelWriter(out_path) as writer:
    comparison[display_cols].to_excel(writer, sheet_name="results",     index=False)
    cat_stats.to_excel(             writer, sheet_name="by_category")
    summary_df.to_excel(            writer, sheet_name="summary",       index=False)

print(f"Saved to {out_path}")

Saved to F\v4\F_v4_claude-sonnet-4-6_results.xlsx

In [231]:
# Records where primary_LLM did not match research_category — for re-run with modified prompt
incorrect_ids = comparison.loc[~comparison["primary_correct"], "id"]
incorrect_rescat_data = DATASET[DATASET["id"].isin(incorrect_ids)].reset_index(drop=True)
incorrect_rescat_data

,id,family_id,application_number,title,abstract,cpc,publication_year,jurisdiction,scope,pillar,subpillar,research_category,endproduct,ingredient,truncated
0,AR-130716-A1,94475360,ARP230102694,COMPOSITIONS AND APPLICATIONS DERIVED FROM OGA...,The disclosure provided herein relates to the ...,NaN,2025,AR,in,F,PF,Ingredient optimisation,Meat,Flavours and aromas,True
1,FR-3158214-A1,94384205,FR2500414,FOOD PRODUCT BASED ON MICROALGAE,The invention relates to the production of a n...,"['A23K10/16', 'A23J3/20', 'A21D2/267', 'A23J3/...",2025,FR,in,F,BF,Ingredient optimisation,Meat,NaN,False
2,WO-2025073700-A1,88373939,EP2024/077614,COLD GELLABLE RECOMBINANT BETA-LACTOGLOBULIN A...,The present invention relates to a method for ...,"['A23C21/08', 'A23C21/00', 'A23C1/12', 'A23J1/...",2025,WO,in,F,PF,Ingredient optimisation,Milk and milk proteins,"Emulsions, gels, and binders",False
3,EP-4533954-A1,88600542,EP23306702.4,METHOD FOR PRODUCING CASEIN AND USES THEREOF,The invention pertains to the food industry an...,"['A23C20/00', 'A23J1/008', 'C07K14/4732', 'C12...",2025,EP,in,F,PF,Bioprocess design,Milk and milk proteins,NaN,False
4,JP-2025533662-A,88412235,JP2025519952,Compositions and additives derived from Ogatae...,[Problem] To provide a food composition that u...,"['A23L23/00', 'A23J3/04', 'A61K2236/53', 'A61K...",2025,JP,in,F,PF,Strain development,Meat,Flavours and aromas,False
5,US-12495812-B2,74673249,US17798153,"Lipases, compositions, methods and uses thereof","The present invention relates to a wild-type, ...","['A23C13/16', 'A23C9/1216', 'A23C19/0328', 'A2...",2025,US,in,F,PF,Ingredient optimisation,Cheese,NaN,False
6,SE-2430062-A1,94688059,SE2430062A,Efficient production of recombinant casein,The present invention relates to a method for ...,"['A23J1/202', 'A23J3/20', 'A23V2002/00', 'A23J...",2025,SE,in,F,PF,Target molecule selection,Milk and milk proteins,NaN,False
7,EP-4368027-A1,84369630,EP22383070.4,PROCESS FOR THE MANUFACTURE OF FOOD PRODUCTS W...,The present invention refers to a process for ...,"['C12N1/16', 'C12R2001/72', 'A23J1/001', 'C12R...",2024,EP,in,F,BF,Ingredient optimisation,Cross-cutting,NaN,False
8,NL-2037130-B1,90362923,NL2037130,MICROBIAL LIPID COMPOSITION,MICROBIAL LIPID COMPOSITION ABSTRACT The curre...,"['A23D9/007', 'C12N1/16', 'C11B1/10', 'A23L33/...",2025,NL,in,F,PF,Target molecule selection,Cross-cutting,Fats and oils,False
9,EP-4522722-A1,82742590,EP23738438.3,PRODUCTION OF A FUNGAL FERMENTATION MEDIUM FRO...,The present invention relates to a method for ...,"['C12N1/22', 'C12R2001/645', 'C12N1/14', 'A23J...",2025,EP,in,F,NaN,Bioprocess design,Cross-cutting,NaN,False
10,EP-4637363-A1,89620117,EP23841475.9,USE OF A FUNGAL PROTEIN COMPRISING AN OVER EXP...,The present invention relates to the use of a ...,"['A23L33/195', 'A21D2/267', 'C12R2001/885', 'A...",2025,EP,in,F,PF,Ingredient optimisation,Meat,"Emulsions, gels, and binders",False
11,WO-2025181163-A1,90362923,EP2025/055207,MICROBIAL LIPID COMPOSITION,The current invention relates to a microbial l...,"['C12P7/6409', 'A23L29/04', 'C12P7/6458', 'C12...",2025,WO,in,F,PF,Target molecule selection,Cross-cutting,Fats and oils,False