# GenAI Pipeline — Testing Notebook

LLM-based screening of publications for alternative protein relevance and pillar classification.
Uses Claude with prompt caching via the Anthropic Python SDK.

### 1. Imports and Configuration

In [1]:
import duckdb
import pandas as pd
import json
import random
import time
import anthropic
import os
from pathlib import Path
from dotenv import load_dotenv
from pydantic import BaseModel, Field, field_validator
from typing import Literal
from pydantic import create_model

load_dotenv()

DB_PATH = "../publications.db"
OUTPUT_DIR = Path(".")
RAW_SUBS_DIR = Path("raw_subsets")

### 2. Data Inspection

In [2]:
EXCEL_PATH = Path("raw_subsets/batch_test_50outML_corr_rand3.xlsx")
df_raw = pd.read_excel(EXCEL_PATH)
df_raw["research_category"] = df_raw["research_category"].str.strip()

df = df_raw[
    (df_raw["scope"] == "in") &
    df_raw["research_category"].notna() &
    (df_raw["research_category"] != "")
].reset_index(drop=True)

print(f"Raw shape: {df_raw.shape}")
print(f"Filtered shape (scope=in, research_category not empty): {df.shape}")
print(f"\nColumns: {list(df.columns)}")
print(f"\nResearch category distribution:")
print(df["research_category"].value_counts())
df.head()

Raw shape: (2928, 10)
Filtered shape (scope=in, research_category not empty): (1014, 10)

Columns: ['id', 'title', 'abstract', 'year', 'scope', 'pillar', 'research_category', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']

Research category distribution:
research_category
Ingredient optimisation       339
End product formulation       138
Consumer & market research    129
Texturization methods          65
Health & nutrition             60
Other                          52
Food safety & quality          42
Crop development               34
Impact assessments             34
Bioprocess design              33
Feedstocks                     28
Strain development             27
Scaffolding                    14
Cell culture media              8
Cell line development           7
Target molecule selection       4
Name: count, dtype: int64

,id,title,abstract,year,scope,pillar,research_category,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,pub.1192230359,Effect of Plant Protein Ingredients at a Range...,"Hybrid plant and meat (HPM) products, in which...",2025,in,PB,End product formulation,NaN,NaN,End product formulation
1,pub.1183225808,Do ingredients matter? Exploring consumer pref...,It is widely accepted that reducing the consum...,2025,in,PB,Consumer & market research,NaN,NaN,Other
2,pub.1192380853,Low–intensity pulsed electromagnetic field sti...,Pulsed electromagnetic field (PEMF) stimulatio...,2025,in,CM,Texturization methods,NaN,NaN,Crop development
3,pub.1186213778,"Drivers, Barriers, and Innovations in Sustaina...",Sustainable food consumption is crucial for mi...,2025,in,CC,Other,NaN,NaN,Cell culture media
4,pub.1188996314,Temperature-dependent growth kinetics of Lacti...,Abstract Microbial growth responses of probio...,2025,in,PB,Strain development,NaN,NaN,Health & nutrition

In [19]:
df_pb = df[df["pillar"] == "PB"].reset_index(drop=True)
df_f  = df[df["pillar"] == "F"].reset_index(drop=True)
df_cm = df[df["pillar"] == "CM"].reset_index(drop=True)
df_cc = df[df["pillar"] == "CC"].reset_index(drop=True)

all_categories = sorted(df["research_category"].dropna().unique())
breakdown = pd.DataFrame(
    {pillar: grp["research_category"].value_counts().reindex(all_categories, fill_value=0)
     for pillar, grp in [("PB", df_pb), ("F", df_f), ("CM", df_cm), ("CC", df_cc)]},
    index=all_categories,
)
breakdown.index.name = "research_category"
breakdown["Total"] = breakdown.sum(axis=1)
breakdown

                             PB   F  CM  CC  Total
research_category
Bioprocess design             0  23   9   1     33
Cell culture media            0   0   8   0      8
Cell line development         0   0   7   0      7
Consumer & market research   64   1  32  32    129
Crop development             34   0   0   0     34
End product formulation     126   5   2   5    138
Feedstocks                    0  28   0   0     28
Food safety & quality        30   2   3   7     42
Health & nutrition           43  10   0   7     60
Impact assessments           18   6   5   5     34
Ingredient optimisation     279  43   0  17    339
Other                        10  10  13  19     52
Scaffolding                   0   0  14   0     14
Strain development           11  16   0   0     27
Target molecule selection     0   4   0   0      4
Texturization methods        58   1   3   3     65

### 3. Balanced Subset Creation

Just taking as many as 10 from each research category within each pillar.

In [20]:
RANDOM_STATE=3

def create_balanced_sample(df, category_counts, random_state=RANDOM_STATE):
    """
    category_counts: dict mapping research_category -> n, e.g.
        {"Ingredient optimisation": 5, "End product formulation": 3, "Other": 2}
    Categories with no matching rows are skipped with a warning.
    If n exceeds available rows, all available rows are taken (with a warning).
    """
    samples = []
    for cat, n in category_counts.items():
        subset = df[df["research_category"] == cat]
        available = len(subset)
        if available == 0:
            print(f"  Warning: '{cat}' — no rows found, skipping.")
            continue
        if n > available:
            print(f"  Warning: '{cat}' — requested {n} but only {available} available, taking all.")
            n = available
        samples.append(subset.sample(n=n, random_state=random_state))
    combined = pd.concat(samples, ignore_index=True)
    return combined.sample(frac=1, random_state=random_state).reset_index(drop=True)

In [21]:
test_data_PB = create_balanced_sample(df_pb, {
    "Bioprocess design": 10,
    "Cell culture media": 10,
    "Cell line development": 10,
    "Consumer & market research": 10,
    "Crop development": 10,
    "End product formulation": 10,
    "Feedstocks": 10,
    "Food safety & quality": 10,
    "Health & nutrition": 10,
    "Impact assessments": 10,
    "Ingredient optimisation": 10,
    "Other": 10,
    "Scaffolding": 10,
    "Strain development": 10,
    "Target molecule selection": 10,
    "Texturization methods": 10,
}, random_state=3)
print(f"test_data_PB: {test_data_PB.shape}")
# test_data_PB[["id", "title", "scope", "pillar"]]

  Warning: 'Bioprocess design' — no rows found, skipping.
  Warning: 'Cell culture media' — no rows found, skipping.
  Warning: 'Cell line development' — no rows found, skipping.
  Warning: 'Feedstocks' — no rows found, skipping.
  Warning: 'Scaffolding' — no rows found, skipping.
  Warning: 'Target molecule selection' — no rows found, skipping.
test_data_PB: (100, 10)

In [22]:
test_data_F = create_balanced_sample(df_f, {
    "Bioprocess design": 10,
    "Cell culture media": 10,
    "Cell line development": 10,
    "Consumer & market research": 10,
    "Crop development": 10,
    "End product formulation": 10,
    "Feedstocks": 10,
    "Food safety & quality": 10,
    "Health & nutrition": 10,
    "Impact assessments": 10,
    "Ingredient optimisation": 10,
    "Other": 10,
    "Scaffolding": 10,
    "Strain development": 10,
    "Target molecule selection": 10,
    "Texturization methods": 10,
}, random_state=3)
print(f"test_data_F: {test_data_F.shape}")
# test_data_F[["id", "title", "scope", "pillar"]]

  Warning: 'Cell culture media' — no rows found, skipping.
  Warning: 'Cell line development' — no rows found, skipping.
  Warning: 'Consumer & market research' — requested 10 but only 1 available, taking all.
  Warning: 'Crop development' — no rows found, skipping.
  Warning: 'End product formulation' — requested 10 but only 5 available, taking all.
  Warning: 'Food safety & quality' — requested 10 but only 2 available, taking all.
  Warning: 'Impact assessments' — requested 10 but only 6 available, taking all.
  Warning: 'Scaffolding' — no rows found, skipping.
  Warning: 'Target molecule selection' — requested 10 but only 4 available, taking all.
  Warning: 'Texturization methods' — requested 10 but only 1 available, taking all.
test_data_F: (79, 10)

In [23]:
test_data_CM = create_balanced_sample(df_cm, {
    "Bioprocess design": 10,
    "Cell culture media": 10,
    "Cell line development": 10,
    "Consumer & market research": 10,
    "Crop development": 10,
    "End product formulation": 10,
    "Feedstocks": 10,
    "Food safety & quality": 10,
    "Health & nutrition": 10,
    "Impact assessments": 10,
    "Ingredient optimisation": 10,
    "Other": 10,
    "Scaffolding": 10,
    "Strain development": 10,
    "Target molecule selection": 10,
    "Texturization methods": 10,
}, random_state=3)
print(f"test_data_CM: {test_data_CM.shape}")
# test_data_CM[["id", "title", "scope", "pillar"]]

  Warning: 'Bioprocess design' — requested 10 but only 9 available, taking all.
  Warning: 'Cell culture media' — requested 10 but only 8 available, taking all.
  Warning: 'Cell line development' — requested 10 but only 7 available, taking all.
  Warning: 'Crop development' — no rows found, skipping.
  Warning: 'End product formulation' — requested 10 but only 2 available, taking all.
  Warning: 'Feedstocks' — no rows found, skipping.
  Warning: 'Food safety & quality' — requested 10 but only 3 available, taking all.
  Warning: 'Health & nutrition' — no rows found, skipping.
  Warning: 'Impact assessments' — requested 10 but only 5 available, taking all.
  Warning: 'Ingredient optimisation' — no rows found, skipping.
  Warning: 'Strain development' — no rows found, skipping.
  Warning: 'Target molecule selection' — no rows found, skipping.
  Warning: 'Texturization methods' — requested 10 but only 3 available, taking all.
test_data_CM: (67, 10)

In [24]:
test_data_CC = create_balanced_sample(df_cc, {
    "Bioprocess design": 10,
    "Cell culture media": 10,
    "Cell line development": 10,
    "Consumer & market research": 10,
    "Crop development": 10,
    "End product formulation": 10,
    "Feedstocks": 10,
    "Food safety & quality": 10,
    "Health & nutrition": 10,
    "Impact assessments": 10,
    "Ingredient optimisation": 10,
    "Other": 10,
    "Scaffolding": 10,
    "Strain development": 10,
    "Target molecule selection": 10,
    "Texturization methods": 10,
}, random_state=3)
print(f"test_data_CC: {test_data_CC.shape}")
# test_data_CC[["id", "title", "scope", "pillar"]]

  Warning: 'Bioprocess design' — requested 10 but only 1 available, taking all.
  Warning: 'Cell culture media' — no rows found, skipping.
  Warning: 'Cell line development' — no rows found, skipping.
  Warning: 'Crop development' — no rows found, skipping.
  Warning: 'End product formulation' — requested 10 but only 5 available, taking all.
  Warning: 'Feedstocks' — no rows found, skipping.
  Warning: 'Food safety & quality' — requested 10 but only 7 available, taking all.
  Warning: 'Health & nutrition' — requested 10 but only 7 available, taking all.
  Warning: 'Impact assessments' — requested 10 but only 5 available, taking all.
  Warning: 'Scaffolding' — no rows found, skipping.
  Warning: 'Strain development' — no rows found, skipping.
  Warning: 'Target molecule selection' — no rows found, skipping.
  Warning: 'Texturization methods' — requested 10 but only 3 available, taking all.
test_data_CC: (58, 10)

### 4. Save Subsets to Excel
Allows manual check of files selected. Consider whether those in the test sets are borderline cases or clear cut.

In [39]:
################################################################################################
# PLEASE CHANGE FILENAME TO THE RANDOM SEED USED IN create_balanced_sample() FOR REPRODUCIBILITY
################################################################################################
def save_subset(df, filename, output_dir=RAW_SUBS_DIR):
    path = output_dir / filename
    df.to_excel(path, index=False)
    print(f"Saved {len(df)} records to {path}")

#save_subset(initial_test_data, "initial_test_data_rand3.xlsx")
save_subset(test_data_PB, f"rescat_test_data_PB_rand{RANDOM_STATE}.xlsx")
save_subset(test_data_CM, f"rescat_test_data_CM_rand{RANDOM_STATE}.xlsx")
save_subset(test_data_CC, f"rescat_test_data_CC_rand{RANDOM_STATE}.xlsx")
save_subset(test_data_F, f"rescat_test_data_F_rand{RANDOM_STATE}.xlsx")

Saved 100 records to raw_subsets\rescat_test_data_PB_rand3.xlsx
Saved 67 records to raw_subsets\rescat_test_data_CM_rand3.xlsx
Saved 58 records to raw_subsets\rescat_test_data_CC_rand3.xlsx
Saved 79 records to raw_subsets\rescat_test_data_F_rand3.xlsx

### 5. Load Prompt and Select Dataset

In [367]:
AP_PILLAR = "CC"  # ← CHANGE THIS: "PB", "F", "CM", "CC"

DATASETS = {
    "PB": test_data_PB,
    "F":  test_data_F,
    "CM": test_data_CM,
    "CC": test_data_CC,
}
DATASET = DATASETS[AP_PILLAR]
print(f"Pillar: {AP_PILLAR} | Dataset: {DATASET.shape[0]} records")

# ONLY USED AS REQUIRED FOR RE-RUN SPECIFIC PUBLICATIONS
#ids_to_test = ['pub.1190984789', 'pub.1196086614']
#DATASET = DATASET[DATASET["id"].isin(ids_to_test)]
#DATASET = incorrect_rescat_data

Pillar: CC | Dataset: 58 records

In [ ]:
### OPTIONAL: apply corrections to research_category from a spreadsheet of corrections

#CORRECTIONS_PATH = "2_research_category/PB_v5/PB_v5_claude-sonnet-4-6_results_only-v2-haiku-incorrect.xlsx"
#CORRECTIONS_PATH = "2_research_category/F_v5/F_v5_claude-sonnet-4-6_results_D.xlsx" 
#CORRECTIONS_PATH = "2_research_category/CM_v1/CM_v1_claude-sonnet-4-6_results.xlsx" 
#CORRECTIONS_PATH = "2_research_category/CC_v3/CC_v3_claude-sonnet-4-6_results_C.xlsx" 


#corrections = (
#    pd.read_excel(CORRECTIONS_PATH, usecols=["id", "corrected"])
#    .pipe(lambda d: d[d["corrected"].notna() & (d["corrected"].str.strip() != "")])
#    .set_index("id")["corrected"]
#    .str.strip()
#)

DATASET = DATASET.copy()
mask = DATASET["id"].isin(corrections.index)
DATASET.loc[mask, "research_category"] = DATASET.loc[mask, "id"].map(corrections)

print(f"Loaded {len(corrections)} corrections, {mask.sum()} rows updated in DATASET")

Loaded 4 corrections, 4 rows updated in DATASET

In [370]:
PROMPT_VERSION = "v3"  # ← CHANGE THIS to switch prompt version
PROMPT_PATH = f"2_research_category/{AP_PILLAR}_{PROMPT_VERSION}/prompt_rescat_pubs_{AP_PILLAR}_{PROMPT_VERSION}.md"

In [371]:
def load_prompt(path=PROMPT_PATH):
    with open(path, "r", encoding="utf-8") as f:
        prompt_text = f.read()
    return prompt_text.strip()

system_prompt = load_prompt()
print(system_prompt)

You are an expert in alternative proteins and food science research.

Your task is to classify a publication on alternative proteins into a research category based on its title and abstract.

Before assigning categories, identify the novel contribution or primary focus of the paper. The 8 specific categories below (everything except Other) are reserved for publications where that topic is the novel contribution or primary focus of the paper. A category should only be assigned if the paper actively investigates, develops, measures, or reviews something within that domain. For example:
- A paper comparing sensory properties of plant-based, mycoprotein, and cultivated meat products → End product formulation
- A systematic review of extrusion and 3D printing technologies for meat analogues → Texturisation methods
- A paper measuring consumer acceptance of plant-based and cultivated meat products → Consumer & market research
- A paper analysing novel food regulatory frameworks for alternative proteins → Food safety & quality
- A review focused primarily on ingredient modification methods that also mentions health and sustainability → Ingredient Optimisation
- A review covering ingredient modification, health effects, consumer acceptance, and environmental impacts equally → Other

From the 9 research categories defined below, identify the top 2 categories that best capture the novel contribution and primary focus of the paper, ranked from most to least central. Provide one extremely concise sentence of reasoning for your choice.

Review articles receive Other only when they span multiple research categories without a clear dominant focus. If a review is organised around a single topic (e.g. fermentation as a method for improving ingredient properties, or consumer acceptance of alternative proteins) assign that category even if other topics are
touched on.

Research Categories:
- Bioprocess design: Innovations in bioreactor design, process engineering, and alteration of the physical cell growth environment aimed at improving the yield, efficiency, sustainability, or scalability of production. Includes reactor architecture, co-culture systems, aeration and mass transfer, monitoring and control systems, scale-up strategies, and downstream processing such as harvesting and purification.
- Scaffolding: Development and characterisation of biomaterials, scaffold architectures, and bioprinting systems (including 3D bioprinting and bioinks) that support adherence, proliferation, and differentiation of plant, microbial, or animal cells to replicate the complex three-dimensional structure of animal muscle tissue, including edible and food-grade scaffold materials from plant, fungal, or synthetic sources.
- Ingredient optimisation: Improvement of individual alternative protein ingredients — including plant proteins, single-cell proteins, mycoprotein, fermentation biomass, and other functional components — through any upstream (cultivation conditions, nutrient regimes) or downstream (fractionation, processing, enzymatic treatment) approach where the primary goal is improving ingredient properties, not production yield or efficiency. Covers improvements to functional properties, sensory qualities, nutritional profile, and in vitro digestibility when used alongside other characterisation metrics. Prefer over End Product Formulation when a single ingredient is the primary object of study.
- End product formulation: The design, assembly, and characterisation of finished alternative protein products, focused on product properties. Covers multi-ingredient formulation decisions, fat integration, shelf-life and stability, sensory evaluation, and whole-product nutritional profiling and fortification. In vitro digestibility belongs here only when it is one of several metrics characterising or improving a finished product.
- Texturization methods: Process innovations for product manufacturing aiming to improve the texture of finished alternative protein products, including extrusion, electrospinning, 3D printing, and enzymatic processing. Does not include extrusion, enzymatic processing, or other methods used to study or modify individual ingredients prior to product assembly, which is Ingredient Optimisation. Prefer Texturization methods over End product formulation when the focus is more on product manufacturing, processing methods, and texture.
- Food safety & quality: Analysis and review of novel food regulation and policy, and microbial, toxicological, and chemical safety assessments of alternative protein ingredients and finished products — including microbial community profiling, contaminant detection, allergenicity assessments, and the development or validation of analytical methods and assays for regulatory compliance. Does not include general reviews of regulatory compliance technologies or assisting technologies, which belong in Other. Does not include the assessment of process safety, occupational safety, or environmental safety of manufacturing facilities, cleaning protocols, or equipment maintenance, which belong in Other.
- Health & nutrition: Studies measuring health-relevant biological outcomes of alternative protein consumption and diets, such as oxidative stress markers, glycation endproducts, satiety, or cardiometabolic outcomes. Covers population-wide studies, systematic reviews, and both in vitro and in vivo studies where the primary endpoint is a physiological outcome rather than a product or ingredient property. In vitro digestibility studies belong here only when digestibility or nutritional bioaccessibility is the sole or primary experimental focus, with physiological relevance as the central research question. Does not include general mention of antioxidants, anti-inflammatory, or other properties of ingredients if not measured.
- Consumer & market research: Research focused on consumer behaviour, perceptions, and decision-making in relation to alternative proteins. Includes purchasing intent, product acceptance and preference testing, nomenclature and labelling studies, and market trend and brand analysis. Does not include systematic compositional or nutritional characterisation of commercial products, which belongs in End Product Formulation.
- Impact assessments: Quantitative or structured assessments of alternative protein system-level impacts, including life cycle analysis (LCA), techno-economic analysis (TEA), environmental impact assessments, broad sustainability analysis, carbon or water footprinting, and broader social/geopolitical/policy impact analyses. Does not include novel food regulation and policy, which belongs in Food safety & quality. Does not include qualitative systematic literature reviews applying conceptual frameworks (e.g. value chain analysis, entrepreneurial ecosystem frameworks), which belong in Other.
- Other: Broad catch-all for research where no single category is the clear primary focus, including: review articles spanning multiple categories without a dominant theme; topics not covered by the other research categories described here, including discussions on the religious, political, ethical, or philosophical implications of alternative protein or the protein transition; methodologically unusual publications such as case studies, workshop reports, or practitioner-facing guidance; recipe development using existing commercial alternative protein products as ingredients; research on general manufacturing practices, such as cleaning and equipment maintenance; safety assessments of process, occupational, environmental, and other non-food aspects of manufacturing.

### 6. API Call with Prompt Caching

In [372]:
# API config

# Anthropic model options — pricing as of 2026-06-10.
# Verify at https://www.anthropic.com/pricing if costs may have changed.
# Model                  Input $/1M   Output $/1M   Context
# claude-haiku-4-5         $1.00         $5.00       200K
# claude-sonnet-4-6        $3.00        $15.00       1M
# claude-opus-4-8          $5.00        $25.00       1M
MODELS = {
    "haiku":  "claude-haiku-4-5",
    "sonnet": "claude-sonnet-4-6",
    "opus":   "claude-opus-4-8",
}
MODEL = MODELS["sonnet"]  # ← change this to switch model

MAX_TOKENS = 512         # max tokens in response; adjust based on expected reasoning length and cost tolerance
TEMPERATURE = 0.0        # 0.0 = deterministic; raise to ~0.3 to sample variance across REPETITIONS
CALL_DELAY = 1.0         # seconds between API calls
REQUEST_TIMEOUT = 120    # seconds before giving up on a single API call
MAX_RETRIES = 6          # retry attempts on rate-limit / transient errors
RETRY_BASE_SECONDS = 5.0  # exponential backoff base
RETRY_MAX_SECONDS = 90.0  # cap on backoff sleep

REPETITIONS = 1  # number of full runs; increase to measure output variance across runs

# ================================================================
# CHECKPOINT CONFIG
# Saves progress after each record; a run interrupted mid-way can
# be resumed without re-processing completed records.
# Set RESUME_INCOMPLETE = False to always start from scratch.
# ================================================================
CHECKPOINT_DIR = Path("checkpoints")
RESUME_INCOMPLETE = True

In [ ]:
# ================================================================
# REASONING TOGGLE
# Keep True during testing — reasoning shows WHY the model decides
# as it does, which is essential for evaluating prompt quality.
# Set to False for production runs once the prompt is validated,
# to reduce token usage.
# ================================================================
INCLUDE_REASONING = True

PB_CATS = ["Crop development", "Strain development", "Ingredient optimisation", "End product formulation", "Texturization methods", "Food safety & quality", "Health & nutrition", "Consumer & market research", "Impact assessments", "Other"]
F_CATS  = ["Feedstocks", "Target molecule selection", "Strain development", "Bioprocess design", "Ingredient optimisation", "End product formulation", "Texturization methods", "Food safety & quality", "Health & nutrition", "Consumer & market research", "Impact assessments", "Other"]
CM_CATS = ["Cell line development", "Cell culture media", "Bioprocess design", "Scaffolding", "End product formulation", "Food safety & quality", "Health & nutrition", "Consumer & market research", "Impact assessments", "Other"]
CC_CATS = ["Bioprocess design", "Scaffolding", "Ingredient optimisation", "End product formulation", "Texturization methods", "Food safety & quality", "Health & nutrition", "Consumer & market research", "Impact assessments", "Other"]

PILLAR_CATS = {"PB": PB_CATS, "F": F_CATS, "CM": CM_CATS, "CC": CC_CATS}

def make_schema(cats, include_reasoning):
    # The LLM sometimes returns title-case values (e.g. "Health & Nutrition") while
    # our Literal expects sentence case. cats_map allows case-insensitive lookup so
    # the field_validator can normalise the value before Pydantic validates it.
    cats_map = {c.lower(): c for c in cats}
    cat_type = Literal[*cats]

    class _Base(BaseModel):
        # check_fields=False because "primary"/"secondary" are added by create_model, not defined here
        @field_validator("primary", "secondary", mode="before", check_fields=False)
        @classmethod
        def normalise_case(cls, v):
            if isinstance(v, str):
                return cats_map.get(v.lower(), v)
            return v

    fields = {"primary": (cat_type, ...), "secondary": (cat_type, ...)}
    if include_reasoning:
        fields["reasoning"] = (str, ...)
    return create_model("ClassificationSchema", __base__=_Base, **fields)

ClassificationSchema = make_schema(PILLAR_CATS[AP_PILLAR], INCLUDE_REASONING)
print(f"Schema built for {AP_PILLAR}: {list(PILLAR_CATS[AP_PILLAR])}")

client = anthropic.Anthropic(api_key=os.getenv("CLAUDE_API_KEY"))

def classify_publication(title, abstract, system_prompt):
    user_message = f"Title: {title}\n\nAbstract: {abstract}"
    response = client.messages.parse(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        temperature=TEMPERATURE,
        timeout=REQUEST_TIMEOUT,
        system=[
            {
                "type": "text",
                "text": system_prompt,
                "cache_control": {"type": "ephemeral"}
            }
        ],
        messages=[
            {"role": "user", "content": user_message}
        ],
        output_format=ClassificationSchema,
    )
    return response.parsed_output

Schema built for CC: ['Bioprocess design', 'Scaffolding', 'Ingredient optimisation', 'End product formulation', 'Texturization methods', 'Food safety & quality', 'Health & nutrition', 'Consumer & market research', 'Impact assessments', 'Other']

In [374]:
def is_retryable_error(exc: Exception) -> bool:
    markers = ["503", "UNAVAILABLE", "RESOURCE_EXHAUSTED", "429",
               "TIMEOUT", "TIMED OUT", "READTIMEOUT", "CONNECTTIMEOUT"]
    return any(m in str(exc).upper() for m in markers)

def retry_sleep_seconds(attempt: int) -> float:
    sleep = min(RETRY_MAX_SECONDS, RETRY_BASE_SECONDS * (2 ** attempt))
    jitter = random.uniform(0.0, min(3.0, sleep * 0.2))
    return sleep + jitter

### 7. Error Handling with Retry

In [375]:
def classify_with_error_handling(row, system_prompt):
    pub_id = row["id"]
    last_error = None
    for attempt in range(MAX_RETRIES + 1):
        try:
            result = classify_publication(row["title"], row["abstract"], system_prompt)
            if result is None:
                print(f"  Parse failed for {pub_id}: model returned no structured output")
                return {"id": pub_id, "status": "parse_error", "error": "no structured output"}
            output = {f"{k}_LLM": v for k, v in result.model_dump().items()} # rename columns / keys to indicate LLM output
            output["id"] = pub_id
            output["status"] = "ok"
            return output
        except anthropic.APIError as e:
            last_error = e
            if attempt >= MAX_RETRIES:
                break
            if is_retryable_error(e):
                sleep_s = retry_sleep_seconds(attempt)
                print(f"  Retryable error (attempt {attempt + 1}/{MAX_RETRIES}): {e}. Sleeping {sleep_s:.1f}s.")
                time.sleep(sleep_s)
            else:
                break
    print(f"  API error for {pub_id}: {last_error}")
    return {"id": pub_id, "status": "api_error", "error": str(last_error)}

### 8. Checkpoint Helpers

In [376]:
def get_checkpoint_path(run_idx: int) -> Path:
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    return CHECKPOINT_DIR / f"run_{run_idx}_checkpoint.json"

def save_checkpoint(run_idx: int, completed_results: list) -> None:
    path = get_checkpoint_path(run_idx)
    payload = {
        "run_idx": run_idx,
        "completed_ids": [r["id"] for r in completed_results],
        "results": completed_results,
    }
    path.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")

def load_checkpoint(run_idx: int):
    path = get_checkpoint_path(run_idx)
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None

def delete_checkpoint(run_idx: int) -> None:
    path = get_checkpoint_path(run_idx)
    if path.exists():
        path.unlink()

### 9. Run on Test Data

In [377]:
all_results = []

for rep in range(REPETITIONS):
    run_idx = rep + 1
    print(f"\n{'='*50}\nRun {run_idx} / {REPETITIONS}\n{'='*50}")

    checkpoint = load_checkpoint(run_idx) if RESUME_INCOMPLETE else None
    if checkpoint:
        completed_results = checkpoint["results"]
        completed_ids = set(checkpoint["completed_ids"])
        print(f"  Resuming: {len(completed_ids)} records already processed.")
    else:
        completed_results, completed_ids = [], set()

    remaining = DATASET[~DATASET["id"].isin(completed_ids)]
    total = len(DATASET)

    for _, row in remaining.iterrows():
        n_done = len(completed_results)
        print(f"  [{n_done + 1}/{total}] {row['id']}")
        result = classify_with_error_handling(row, system_prompt)
        result["run"] = run_idx
        completed_results.append(result)
        save_checkpoint(run_idx, completed_results)
        if n_done + 1 < total:
            time.sleep(CALL_DELAY)

    delete_checkpoint(run_idx)
    all_results.extend(completed_results)

results_df = pd.DataFrame(all_results)
print(f"\nCompleted: {len(results_df)} records across {REPETITIONS} run(s)")
print(f"Successful: {(results_df['status'] == 'ok').sum()}")
print(f"Errors: {(results_df['status'] != 'ok').sum()}")
results_df

==================================================
Run 1 / 1
==================================================
  [1/58] pub.1190543844
  [2/58] pub.1174613325
  [3/58] pub.1194906364
  [4/58] pub.1184597489
  [5/58] pub.1191849859
  [6/58] pub.1195111619
  [7/58] pub.1194354565
  [8/58] pub.1187276166
  [9/58] pub.1187295059
  [10/58] pub.1196060665
  [11/58] pub.1195609701
  [12/58] pub.1187052760
  [13/58] pub.1193643289
  [14/58] pub.1191284655
  [15/58] pub.1190518754
  [16/58] pub.1187677686
  [17/58] pub.1191637476
  [18/58] pub.1185255386
  [19/58] pub.1194074326
  [20/58] pub.1182396222
  [21/58] pub.1186478980
  [22/58] pub.1194329838
  [23/58] pub.1189349384
  [24/58] pub.1184131962
  [25/58] pub.1184676351
  [26/58] pub.1192359115
  [27/58] pub.1188715770
  [28/58] pub.1189679969
  [29/58] pub.1191584911
  [30/58] pub.1184151966
  [31/58] pub.1187075423
  [32/58] pub.1188616435
  [33/58] pub.1188817720
  [34/58] pub.1191993918
  [35/58] pub.1175608755
  [36/58] pub.1194557570
  [37/58] pub.1186732451
  [38/58] pub.1187944871
  [39/58] pub.1195194673
  [40/58] pub.1184274752
  [41/58] pub.1191954992
  [42/58] pub.1195166812
  [43/58] pub.1189355597
  [44/58] pub.1191996975
  [45/58] pub.1189656211
  [46/58] pub.1189269329
  [47/58] pub.1189232977
  [48/58] pub.1184282447
  [49/58] pub.1196201594
  [50/58] pub.1192451356
  [51/58] pub.1195165724
  [52/58] pub.1191240521
  [53/58] pub.1185588959
  [54/58] pub.1185641099
  [55/58] pub.1185301096
  [56/58] pub.1196344309
  [57/58] pub.1193442920
  [58/58] pub.1193813897

Completed: 58 records across 1 run(s)
Successful: 58
Errors: 0

,primary_LLM,secondary_LLM,reasoning_LLM,id,status,run
0,Other,Consumer & market research,This paper is primarily a philosophical and co...,pub.1190543844,ok,1
1,End product formulation,Scaffolding,The paper characterises mechanical and textura...,pub.1174613325,ok,1
2,Texturization methods,End product formulation,The review focuses on 3D food printing as a ma...,pub.1194906364,ok,1
3,End product formulation,Health & nutrition,This review systematically compares the nutrit...,pub.1184597489,ok,1
4,Consumer & market research,Other,This paper uses survey data to study consumer ...,pub.1191849859,ok,1
5,Ingredient optimisation,Other,The review focuses primarily on how processing...,pub.1195111619,ok,1
6,Food safety & quality,Other,This review focuses on protein safety assessme...,pub.1194354565,ok,1
7,Other,Health & nutrition,This broad review spans multiple categories (s...,pub.1187276166,ok,1
8,Health & nutrition,Impact assessments,The paper primarily evaluates and compares the...,pub.1187295059,ok,1
9,Health & nutrition,End product formulation,The review's primary focus is on nutrient bioa...,pub.1196060665,ok,1
10,Impact assessments,Health & nutrition,The paper quantitatively assesses environmenta...,pub.1195609701,ok,1
11,Other,Health & nutrition,This review spans multiple categories equally ...,pub.1187052760,ok,1
12,Consumer & market research,Other,The study investigates determinants of consump...,pub.1193643289,ok,1
13,Consumer & market research,Impact assessments,The paper models consumer dietary behavior cha...,pub.1191284655,ok,1
14,Consumer & market research,Impact assessments,The study investigates psychological and attit...,pub.1190518754,ok,1
15,Other,Food safety & quality,"This commentary focuses on religious, ethical,...",pub.1187677686,ok,1
16,Consumer & market research,Impact assessments,The paper synthesises global literature on con...,pub.1191637476,ok,1
17,Texturization methods,End product formulation,The review systematically examines processing ...,pub.1185255386,ok,1
18,Other,Impact assessments,This review spans multiple categories equally ...,pub.1194074326,ok,1
19,Impact assessments,Other,The paper conducts a structured quantitative a...,pub.1182396222,ok,1
20,Food safety & quality,Other,The paper's primary focus is a comparative leg...,pub.1186478980,ok,1
21,End product formulation,Consumer & market research,The paper systematically characterises the nut...,pub.1194329838,ok,1
22,Health & nutrition,Ingredient optimisation,The review's primary focus is on protein diges...,pub.1189349384,ok,1
23,End product formulation,Other,The review's dominant focus is on the incorpor...,pub.1184131962,ok,1
24,Ingredient optimisation,Health & nutrition,The paper focuses on improving functional prop...,pub.1184676351,ok,1
25,Consumer & market research,Impact assessments,The paper investigates retailer strategies and...,pub.1192359115,ok,1
26,Texturization methods,Ingredient optimisation,The paper investigates oscillatory flow-induce...,pub.1188715770,ok,1
27,Other,Impact assessments,This broad review spans multiple categories eq...,pub.1189679969,ok,1
28,Impact assessments,Other,The paper conducts life cycle assessments (LCA...,pub.1191584911,ok,1
29,Impact assessments,Other,The paper discusses environmental and socio-ec...,pub.1184151966,ok,1
30,Other,Consumer & market research,This is a bibliometric/systematic mapping stud...,pub.1187075423,ok,1
31,Consumer & market research,Other,The study directly measures consumer willingne...,pub.1188616435,ok,1
32,Ingredient optimisation,Other,This review focuses on deep eutectic solvents ...,pub.1188817720,ok,1
33,Consumer & market research,Other,The study directly investigates consumer behav...,pub.1191993918,ok,1
34,Ingredient optimisation,End product formulation,The paper primarily investigates the molecular...,pub.1175608755,ok,1
35,Consumer & market research,Health & nutrition,The study uses a survey to investigate consume...,pub.1194557570,ok,1
36,Food safety & quality,Ingredient optimisation,The paper primarily reviews allergenicity risk...,pub.1186732451,ok,1
37,Other,Food safety & quality,This paper is a policy-oriented discussion pap...,pub.1187944871,ok,1
38,Food safety & quality,Health & nutrition,The paper focuses on applying New Approach Met...,pub.1195194673,ok,1
39,Health & nutrition,Consumer & market research,The paper focuses on postprandial amino acid k...,pub.1184274752,ok,1
40,Ingredient optimisation,End product formulation,The study primarily focuses on improving micro...,pub.1191954992,ok,1
41,Ingredient optimisation,Health & nutrition,The review is primarily organised around impro...,pub.1195166812,ok,1
42,Health & nutrition,Ingredient optimisation,The study's primary focus is on protein fermen...,pub.1189355597,ok,1
43,Food safety & quality,Health & nutrition,The paper performs allergenicity and immunogen...,pub.1191996975,ok,1
44,Impact assessments,Consumer & market research,The paper quantitatively assesses the environm...,pub.1189656211,ok,1
45,Ingredient optimisation,Texturization methods,The review's dominant focus is on molecular an...,pub.1189269329,ok,1
46,Ingredient optimisation,Health & nutrition,This review focuses primarily on how fermentat...,pub.1189232977,ok,1
47,Other,Consumer & market research,This paper is a philosophical analysis of the ...,pub.1184282447,ok,1
48,Ingredient optimisation,Other,The review's dominant focus is on modification...,pub.1196201594,ok,1
49,Health & nutrition,Ingredient optimisation,The review's dominant focus is on the physiolo...,pub.1192451356,ok,1
50,Consumer & market research,Health & nutrition,The study primarily investigates consumer atti...,pub.1195165724,ok,1
51,Food safety & quality,Health & nutrition,The review's primary focus is on allergenicity...,pub.1191240521,ok,1
52,Food safety & quality,Impact assessments,The paper primarily analyzes the EU Novel Food...,pub.1185588959,ok,1
53,Bioprocess design,Ingredient optimisation,The paper presents the engineering design and ...,pub.1185641099,ok,1
54,Consumer & market research,Other,This qualitative study using focus groups and ...,pub.1185301096,ok,1
55,Consumer & market research,Impact assessments,The study uses survey data and PLS-SEM to inve...,pub.1196344309,ok,1
56,Health & nutrition,Consumer & market research,This review focuses on the health-relevant bio...,pub.1193442920,ok,1
57,Ingredient optimisation,Health & nutrition,This review is primarily focused on how fermen...,pub.1193813897,ok,1

In [378]:
result_cols = ["id", "run", "primary_LLM", "secondary_LLM", "status"]
if INCLUDE_REASONING:
    result_cols.append("reasoning_LLM")

comparison = DATASET[["id", "title", "abstract", "pillar", "research_category"]].merge(
    results_df[result_cols], on="id", how="left"
)

comparison["primary_correct"] = comparison["research_category"] == comparison["primary_LLM"]
comparison["either_correct"]  = (
    (comparison["research_category"] == comparison["primary_LLM"]) |
    (comparison["research_category"] == comparison["secondary_LLM"])
)

# Overall metrics
n = len(comparison)
print(f"Top-1 accuracy (primary match):  {comparison['primary_correct'].mean():.0%}  (n={n})")
print(f"Top-2 accuracy (either match):   {comparison['either_correct'].mean():.0%}  (n={n})")

# Per-category breakdown
cat_stats = (
    comparison.groupby("research_category")
    .agg(
        n=("primary_correct", "count"),
        primary_correct=("primary_correct", "sum"),
        top2_correct=("either_correct", "sum"),
    )
    .assign(
        primary_acc=lambda d: (d["primary_correct"] / d["n"]).map("{:.0%}".format),
        top2_acc=lambda d: (d["top2_correct"] / d["n"]).map("{:.0%}".format),
    )
)
display(cat_stats)

# Detail table
display_cols = ["id", "title", "abstract", "pillar", "research_category",
                "primary_LLM", "secondary_LLM"]
if INCLUDE_REASONING:
    display_cols.append("reasoning_LLM")
display_cols += ["primary_correct", "either_correct"]
comparison[display_cols]

Top-1 accuracy (primary match):  91%  (n=58)
Top-2 accuracy (either match):   95%  (n=58)

,n,primary_correct,top2_correct,primary_acc,top2_acc
research_category,,,,,
Bioprocess design,1,1,1,100%,100%
Consumer & market research,10,10,10,100%,100%
End product formulation,4,4,4,100%,100%
Food safety & quality,7,7,7,100%,100%
Health & nutrition,6,6,6,100%,100%
Impact assessments,5,4,5,80%,100%
Ingredient optimisation,9,9,9,100%,100%
Other,13,9,10,69%,77%
Texturization methods,3,3,3,100%,100%

,id,title,abstract,pillar,research_category,primary_LLM,secondary_LLM,reasoning_LLM,primary_correct,either_correct
0,pub.1190543844,Disruptive technologies and intra-value confli...,Synthetic biology is a highly disruptive techn...,CC,Other,Other,Consumer & market research,This paper is primarily a philosophical and co...,True,True
1,pub.1174613325,Mechanical properties and texture profile anal...,"Cultivated meat, or cultured meat, is lab-grow...",CC,End product formulation,End product formulation,Scaffolding,The paper characterises mechanical and textura...,True,True
2,pub.1194906364,Recent Advances in Inks for 3D Food Printing: ...,The integration of 3D printers into food produ...,CC,Texturization methods,Texturization methods,End product formulation,The review focuses on 3D food printing as a ma...,True,True
3,pub.1184597489,Nutritional and Sensory Properties of Meat Ana...,"For centuries, meat has been a staple in the h...",CC,End product formulation,End product formulation,Health & nutrition,This review systematically compares the nutrit...,True,True
4,pub.1191849859,"The Good, the Bad, and the Unsustainable: eval...",Despite the proliferation of alternatives for ...,CC,Consumer & market research,Consumer & market research,Other,This paper uses survey data to study consumer ...,True,True
5,pub.1195111619,Algae Processing: Harnessing a Sustainable Pro...,Plant- and animal-based proteins play a signif...,CC,Ingredient optimisation,Ingredient optimisation,Other,The review focuses primarily on how processing...,True,True
6,pub.1194354565,What makes a food protein unsafe?,With a society increasingly demanding alternat...,CC,Food safety & quality,Food safety & quality,Other,This review focuses on protein safety assessme...,True,True
7,pub.1187276166,Foodomics: A lever to avoid the Darwinian boom...,"Background Since the 18th century, the industr...",CC,Other,Other,Health & nutrition,This broad review spans multiple categories (s...,True,True
8,pub.1187295059,Essential Amino Acids and Fatty Acids in Novel...,Essential amino acids and essential fatty acid...,CC,Health & nutrition,Health & nutrition,Impact assessments,The paper primarily evaluates and compares the...,True,True
9,pub.1196060665,Nutrient Equivalence of Plant-Based and Cultur...,Meat provides high-quality protein and essenti...,CC,Health & nutrition,Health & nutrition,End product formulation,The review's primary focus is on nutrient bioa...,True,True
10,pub.1195609701,Harmonised assessment of environmental impacts...,IntroductionImproving human and planetary heal...,CC,Impact assessments,Impact assessments,Health & nutrition,The paper quantitatively assesses environmenta...,True,True
11,pub.1187052760,"Nutritional Quality, Safety and Environmental ...",Protein is a fundamental macronutrient in the ...,CC,Other,Other,Health & nutrition,This review spans multiple categories equally ...,True,True
12,pub.1193643289,From sensory expectations to social influence:...,The growing interest in and continuous develop...,CC,Consumer & market research,Consumer & market research,Other,The study investigates determinants of consump...,True,True
13,pub.1191284655,Social Interactions for Sustainable Food Choic...,Background: Substantial shifts in contemporary...,CC,Impact assessments,Consumer & market research,Impact assessments,The paper models consumer dietary behavior cha...,False,True
14,pub.1190518754,Young Consumers’ Intention to Consume Innovati...,The contemporary food environment is experienc...,CC,Consumer & market research,Consumer & market research,Impact assessments,The study investigates psychological and attit...,True,True
15,pub.1187677686,Halal considerations that signpost a cellular ...,This commentary examines which halal requireme...,CC,Other,Other,Food safety & quality,"This commentary focuses on religious, ethical,...",True,True
16,pub.1191637476,Where are we now with meat alternatives? Globa...,Global efforts to improve food system sustaina...,CC,Other,Consumer & market research,Impact assessments,The paper synthesises global literature on con...,False,False
17,pub.1185255386,Alternative Protein-Based Meat and Fish Analog...,This study aimed to explore the extent of rese...,CC,Texturization methods,Texturization methods,End product formulation,The review systematically examines processing ...,True,True
18,pub.1194074326,Reshaping Meat Consumption: Meat Substitutes i...,With the rapid growth of the global population...,CC,Other,Other,Impact assessments,This review spans multiple categories equally ...,True,True
19,pub.1182396222,The dairy production system in the north of Sw...,Context The dairy production system fills an i...,CC,Impact assessments,Impact assessments,Other,The paper conducts a structured quantitative a...,True,True
20,pub.1186478980,Regulatory barriers and incentives for alterna...,Purpose This paper aims to discuss the innovat...,CC,Food safety & quality,Food safety & quality,Other,The paper's primary focus is a comparative leg...,True,True
21,pub.1194329838,Carbohydrate usage and protein density in meat...,Meat products are valued for their high-qualit...,CC,End product formulation,End product formulation,Consumer & market research,The paper systematically characterises the nut...,True,True
22,pub.1189349384,Comprehensive review of the digestibility of n...,"As the global population continues to rise, th...",CC,Health & nutrition,Health & nutrition,Ingredient optimisation,The review's primary focus is on protein diges...,True,True
23,pub.1184131962,Advancements in Research on Alternative Protei...,To ensure food security amid dwindling natural...,CC,End product formulation,End product formulation,Other,The review's dominant focus is on the incorpor...,True,True
24,pub.1184676351,Fermentation of a wine pomace and microalgae b...,This study aimed to generate new functional in...,CC,Ingredient optimisation,Ingredient optimisation,Health & nutrition,The paper focuses on improving functional prop...,True,True
25,pub.1192359115,Alternative proteins: How do retailers drive t...,"Purpose In evolving market dynamics, the growi...",CC,Consumer & market research,Consumer & market research,Impact assessments,The paper investigates retailer strategies and...,True,True
26,pub.1188715770,Shaping suspensions: Stabilizing anisotropy in...,An easy process to generate highly anisotropic...,CC,Texturization methods,Texturization methods,Ingredient optimisation,The paper investigates oscillatory flow-induce...,True,True
27,pub.1189679969,Emerging Trends in Sustainable Biological Reso...,The mounting global population and the challen...,CC,Other,Other,Impact assessments,This broad review spans multiple categories eq...,True,True
28,pub.1191584911,Reduced environmental footprint through novel ...,New ways to reduce the climate impact and land...,CC,Impact assessments,Impact assessments,Other,The paper conducts life cycle assessments (LCA...,True,True
29,pub.1184151966,"Emerging alternatives to coffee, cocoa and pal...",Despite increasing interest in cellular agricu...,CC,Other,Impact assessments,Other,The paper discusses environmental and socio-ec...,False,True
30,pub.1187075423,Mapping the research landscape of meat replace...,Meat replacers are gaining global relevance as...,CC,Other,Other,Consumer & market research,This is a bibliometric/systematic mapping stud...,True,True
31,pub.1188616435,Feeding the future: consumer willingness to tr...,Purpose This study aims to measure consumer wi...,CC,Consumer & market research,Consumer & market research,Other,The study directly measures consumer willingne...,True,True
32,pub.1188817720,The potential of deep eutectic solvents in the...,As the global demand for sustainable high-qual...,CC,Ingredient optimisation,Ingredient optimisation,Other,This review focuses on deep eutectic solvents ...,True,True
33,pub.1191993918,Impact of implicit biases on consumer behaviou...,"Growing concerns about the ethical, health, an...",CC,Consumer & market research,Consumer & market research,Other,The study directly investigates consumer behav...,True,True
34,pub.1175608755,Comparative study of interaction and complex f...,The electrostatic interactions and complex for...,CC,Ingredient optimisation,Ingredient optimisation,End product formulation,The paper primarily investigates the molecular...,True,True
35,pub.1194557570,From Curiosity to Consumption: Consumer Attitu...,Consumer interest in alternative protein sourc...,CC,Consumer & market research,Consumer & market research,Health & nutrition,The study uses a survey to investigate consume...,True,True
36,pub.1186732451,Allergenicity of Alternative Proteins: Reducti...,The increasing popularity of alternative prote...,CC,Food safety & quality,Food safety & quality,Ingredient optimisation,The paper primarily reviews allergenicity risk...,True,True
37,pub.1187944871,Addressing semantic ambiguity in biotechnology...,Driven by numerous scientific discoveries in b...,CC,Other,Other,Food safety & quality,This paper is a policy-oriented discussion pap...,True,True
38,pub.1195194673,Application of new approach methods (NAMs) in ...,As new sources of food emerge and technologies...,CC,Food safety & quality,Food safety & quality,Health & nutrition,The paper focuses on applying New Approach Met...,True,True
39,pub.1184274752,Postprandial Aminoacidemia Following the Inges...,There is a pressing need to expand the product...,CC,Health & nutrition,Health & nutrition,Consumer & market research,The paper focuses on postprandial amino acid k...,True,True
40,pub.1191954992,Exploring the Development of a Clean-Label Veg...,Haematococcus pluvialis and Porphyridium cruen...,CC,Ingredient optimisation,Ingredient optimisation,End product formulation,The study primarily focuses on improving micro...,True,True
41,pub.1195166812,Exploring the Potential of Haematococcus pluvi...,The search for sustainable and health-promotin...,CC,Ingredient optimisation,Ingredient optimisation,Health & nutrition,The review is primarily organised around impro...,True,True
42,pub.1189355597,In vitro fermentation potential of diet-derive...,Protein fermentation in the human gut is often...,CC,Health & nutrition,Health & nutrition,Ingredient optimisation,The study's primary focus is on protein fermen...,True,True
43,pub.1191996975,Evaluation of allergenicity of the alternative...,New food sources and unexplored by-products fr...,CC,Food safety & quality,Food safety & quality,Health & nutrition,The paper performs allergenicity and immunogen...,True,True
44,pub.1189656211,Changes in meat consumption can improve ground...,"Large-scale, centralized livestock production ...",CC,Impact assessments,Impact assessments,Consumer & market research,The paper quantitatively assesses the environm...,True,True
45,pub.1189269329,Molecular Strategies to Overcome Sensory Chall...,Increasing demand for protein diversity has pr...,CC,Ingredient optimisation,Ingredient optimisation,Texturization methods,The review's dominant focus is on molecular an...,True,True
46,pub.1189232977,"Plant-based fermented foods: General concepts,...",Plant-based fermented foods and beverages (FFB...,CC,Other,Ingredient optimisation,Health & nutrition,This review focuses primarily on how fermentat...,False,False
47,pub.1184282447,“Meat” as a Functional Concept Apt to Incorpor...,By introducing the possibility of producing me...,CC,Other,Other,Consumer & market research,This paper is a philosophical analysis of the ...,True,True
48,pub.1196201594,A Review on Recent Processing and Bioprocessin...,A lternative proteins (APs) are anticipated to...,CC,Ingredient optimisation,Ingredient optimisation,Other,The review's dominant focus is on modification...,True,True
49,pub.1192451356,Bioactive Food Proteins: Bridging Nutritional ...,Bioactive food proteins play multifunctional r...,CC,Other,Health & nutrition,Ingredient optimisation,The review's dominant focus is on the physiolo...,False,False
50,pub.1195165724,Never too late to try something new: attitudes...,Introduction: Nutrition in older adults requir...,CC,Consumer & market research,Consumer & market research,Health & nutrition,The study primarily investigates consumer atti...,True,True
51,pub.1191240521,Sustainable Nutrition and Food Allergy: A Stat...,"Alternative proteins denote non-traditional, h...",CC,Food safety & quality,Food safety & quality,Health & nutrition,The review's primary focus is on allergenicity...,True,True
52,pub.1185588959,How innovation-friendly is the EU novel food r...,The Novel Food Regulation provides the central...,CC,Food safety & quality,Food safety & quality,Impact assessments,The paper primarily analyzes the EU Novel Food...,True,True
53,pub.1185641099,Design and Operation of a Multifunctional Pilo...,The primary aim of this work was to share the ...,CC,Bioprocess design,Bioprocess design,Ingredient optimisation,The paper presents the engineering design and ...,True,True
54,pub.1185301096,“It's most likely gonna be the future”: A qual...,Alternative proteins offer promise as a sustai...,CC,Consumer & market research,Consumer & market research,Other,This qualitative study using focus groups and ...,True,True
55,pub.1196344309,Exploring Sustainable Diet Drivers: An Extende...,Background/Objectives: This study investigates...,CC,Consumer & market research,Consumer & market research,Impact assessments,The study uses survey data and PLS-SEM to inve...,True,True
56,pub.1193442920,Alternative proteins and gut health: balancing...,The need to nourish the increasing world popul...,CC,Health & nutrition,Health & nutrition,Consumer & market research,This review focuses on the health-relevant bio...,True,True
57,pub.1193813897,The Potential of Fermentation-Based Processing...,Proteins are fundamental to food systems due t...,CC,Ingredient optimisation,Ingredient optimisation,Health & nutrition,This review is primarily focused on how fermen...,True,True

### 10. Save to Excel for Prompt Debugging
To assess how well the prompt does at getting the LLM to assign scope and pillar, I need to save the comparison data, then manually review what went wrong and adjust the prompt.
None of this will make it into the final workflow.

Order of working:
1. Create a new version folder in the 1_prompt_debugging folder.
2. Copy in the previous prompt. Label it with the new version number. Make updates as required based on step 6.
3. Edit Step 10 output directory (this step) and Step 5 prompt selection and input data.
4. Run the script from steps 5-10.
5. Manually review the results. Includes both metrics and 
6. Write a text document about v1 results and what changes you want to make to the prompt. Repeat from step 1.

In [379]:
save_dir = Path(f"2_research_category/{AP_PILLAR}_{PROMPT_VERSION}")
save_dir.mkdir(parents=True, exist_ok=True)

summary_df = pd.DataFrame([
    {"metric": "top1_accuracy", "value": f"{comparison['primary_correct'].mean():.0%}", "n": n},
    {"metric": "top2_accuracy", "value": f"{comparison['either_correct'].mean():.0%}",  "n": n},
])

out_path = save_dir / f"{AP_PILLAR}_{PROMPT_VERSION}_{MODEL}_results.xlsx"
with pd.ExcelWriter(out_path) as writer:
    comparison[display_cols].to_excel(writer, sheet_name="results",     index=False)
    cat_stats.to_excel(             writer, sheet_name="by_category")
    summary_df.to_excel(            writer, sheet_name="summary",       index=False)

print(f"Saved to {out_path}")

Saved to 2_research_category\CC_v3\CC_v3_claude-sonnet-4-6_results.xlsx

In [324]:
# Records where primary_LLM did not match research_category — for re-run with modified prompt
incorrect_ids = comparison.loc[~comparison["primary_correct"], "id"]
incorrect_rescat_data = DATASET[DATASET["id"].isin(incorrect_ids)].reset_index(drop=True)
incorrect_rescat_data

,id,title,abstract,year,scope,pillar,research_category,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,pub.1187276166,Foodomics: A lever to avoid the Darwinian boom...,"Background Since the 18th century, the industr...",2025,in,CC,Health & nutrition,NaN,NaN,NaN
1,pub.1185255386,Alternative Protein-Based Meat and Fish Analog...,This study aimed to explore the extent of rese...,2025,in,CC,Texturization methods,NaN,NaN,NaN
2,pub.1186478980,Regulatory barriers and incentives for alterna...,Purpose This paper aims to discuss the innovat...,2025,in,CC,Food safety & quality,NaN,NaN,NaN
3,pub.1184131962,Advancements in Research on Alternative Protei...,To ensure food security amid dwindling natural...,2025,in,CC,End product formulation,NaN,NaN,NaN
4,pub.1184151966,"Emerging alternatives to coffee, cocoa and pal...",Despite increasing interest in cellular agricu...,2025,in,CC,Ingredient optimisation,NaN,NaN,NaN
5,pub.1191954992,Exploring the Development of a Clean-Label Veg...,Haematococcus pluvialis and Porphyridium cruen...,2025,in,CC,End product formulation,NaN,NaN,NaN
6,pub.1195166812,Exploring the Potential of Haematococcus pluvi...,The search for sustainable and health-promotin...,2025,in,CC,Ingredient optimisation,NaN,NaN,NaN
7,pub.1196201594,A Review on Recent Processing and Bioprocessin...,A lternative proteins (APs) are anticipated to...,2025,in,CC,Ingredient optimisation,NaN,NaN,NaN
8,pub.1192451356,Bioactive Food Proteins: Bridging Nutritional ...,Bioactive food proteins play multifunctional r...,2025,in,CC,Ingredient optimisation,NaN,NaN,NaN
9,pub.1185588959,How innovation-friendly is the EU novel food r...,The Novel Food Regulation provides the central...,2025,in,CC,Food safety & quality,NaN,NaN,NaN
10,pub.1193813897,The Potential of Fermentation-Based Processing...,Proteins are fundamental to food systems due t...,2025,in,CC,Ingredient optimisation,NaN,NaN,NaN