# GenAI Pipeline — Testing Notebook

LLM-based screening of publications for alternative protein relevance and pillar classification.
Uses Claude with prompt caching via the Anthropic Python SDK.

### 1. Imports and Configuration

In [1]:
import duckdb
import pandas as pd
import json
import random
import time
import anthropic
import os
from pathlib import Path
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from typing import Literal

load_dotenv()

DB_PATH = "../publications.db"
OUTPUT_DIR = Path(".")

### 2. Data Inspection

In [2]:
con = duckdb.connect(DB_PATH, read_only=True)
print("Tables:")
print(con.sql("SHOW TABLES").df()) # Check available tables

df = con.sql("SELECT * FROM publications_raw").df()
con.close()

print(f"\nShape: {df.shape}")
print(f"\nColumns: {list(df.columns)}")
print(f"\nScope distribution:")
print(df["scope"].value_counts())
print(f"\nPillar distribution:")
print(df["pillar"].value_counts())
df.head()

Tables:
               name
0  publications_raw

Shape: (4815, 7)

Columns: ['id', 'title', 'abstract', 'year', 'scope', 'pillar', 'research_category']

Scope distribution:
scope
out    3773
in     1042
Name: count, dtype: int64

Pillar distribution:
pillar
NA    3773
PB     695
F      151
CC      98
CM      98
Name: count, dtype: int64

,id,title,abstract,year,scope,pillar,research_category
0,pub.1192791591,Mushroom: an emerging source for next generati...,"Background: In recent years, plant-based and a...",2025,in,PB,Ingredient optimisation
1,pub.1187762379,Plant-Based Alternatives to Meat Products,Animal proteins have been used in the formulat...,2025,in,PB,Other
2,pub.1193391974,Influence of processing on protein quality and...,While meat is an established source of high-qu...,2025,in,PB,Ingredient optimisation
3,pub.1188899046,Solid State Fermentation—A Promising Approach ...,The increasing demand for sustainable dietary ...,2025,in,F,Other
4,pub.1193352421,"Physicochemical, Microbiological and Sensory E...",The bioactive properties of a phenolic extract...,2025,in,PB,End product formulation

### 3. Balanced Subset Creation

Two test sets with balanced representation across scope and pillar:
- `initial_test_data`: 14 records (6 out, 2 PB, 2 F, 2 cultivated, 2 cross-cutting)
- `test_data_100`: 110 records (40 out, 30 PB, 15 F, 15 cultivated, 10 cross-cutting)

In [40]:
def create_balanced_sample(df, n_out, n_pb, n_f, n_cultivated, n_cross, random_state=3): # Can change random_state for different samples - must be integer for reproducibility
    out_sample = df[df["scope"] == "out"].sample(n=n_out, random_state=random_state)
    pb_sample = df[df["pillar"] == "PB"].sample(n=n_pb, random_state=random_state)
    f_sample = df[df["pillar"] == "F"].sample(n=n_f, random_state=random_state)
    cult_sample = df[df["pillar"] == "CM"].sample(n=n_cultivated, random_state=random_state)
    cross_sample = df[df["pillar"] == "CC"].sample(n=n_cross, random_state=random_state)
    combined = pd.concat(
        [out_sample, pb_sample, f_sample, cult_sample, cross_sample], ignore_index=True
    )
    return combined.sample(frac=1, random_state=random_state).reset_index(drop=True)

In [40]:
initial_test_data = create_balanced_sample(df, n_out=6, n_pb=2, n_f=2, n_cultivated=2, n_cross=2)
print(f"initial_test_data: {initial_test_data.shape}")
# initial_test_data[["id", "title", "scope", "pillar"]]

initial_test_data: (14, 7)

In [41]:
PILLAR_ORDER = ["PB", "F", "CM", "CC", "NA"]

initial_test_data_review = initial_test_data.copy()
initial_test_data_review["pillar"] = pd.Categorical(
    initial_test_data_review["pillar"], categories=PILLAR_ORDER, ordered=True
)
initial_test_data_review.sort_values("pillar")[["id", "title", "scope", "pillar", "abstract"]]

,id,title,scope,pillar,abstract
0,pub.1186853899,Food Safety Aspects as Potential Impediment to...,in,PB,The emergence and use of alternative proteins ...
5,pub.1188879491,“I Have No Idea What's in It!”—A Qualitative S...,in,PB,This study aimed to analyze and compare adoles...
11,pub.1186337126,Advancements and challenges in microalgal prot...,in,F,The increasing global demand for sustainable p...
12,pub.1187847578,Selection and characterization of acid-toleran...,in,F,Microalgae are promising candidates for sustai...
8,pub.1191684816,Willingness to consume cultured meat: A meta-a...,in,CM,Background Cultured meat could be a sustainabl...
13,pub.1192380853,Low–intensity pulsed electromagnetic field sti...,in,CM,Pulsed electromagnetic field (PEMF) stimulatio...
4,pub.1189730538,Integrated Chemical and Biochemical Treatments...,in,CC,Pretreatment methods play a pivotal role in th...
9,pub.1190543844,Disruptive technologies and intra-value confli...,in,CC,Synthetic biology is a highly disruptive techn...
1,pub.1186201684,Oxidative stress‐induced changes in wooden bre...,out,NA,Wooden breast (WB) is a multifactorial muscula...
2,pub.1190881151,In Vitro Evaluation of the Potential Interacti...,out,NA,Zearalenone (ZEN) is a mycotoxin that is typic...
3,pub.1186242956,Effect of replacing gluten-free cereal flours ...,out,NA,Gryllus bimaculatus powder can be a sustainabl...
6,pub.1190132094,Reducing antinutritional compounds in Amaranth...,out,NA,"Amaranth (Amaranthus hypochondriacus), a glute..."
7,pub.1189101651,Comprehensive Quantification of (Poly)phenols ...,out,NA,"In the present study, a highly specific, accur..."
10,pub.1192890631,Electromethanogenesis with 3D printed carbon e...,out,NA,Electromethanogenesis offers a promising appro...

In [41]:
test_data_100 = create_balanced_sample(df, n_out=40, n_pb=30, n_f=15, n_cultivated=15, n_cross=10)
print(f"test_data_100: {test_data_100.shape}")
print(test_data_100[["scope", "pillar"]].value_counts())

test_data_100: (110, 7)
scope  pillar
out    NA        40
in     PB        30
       CM        15
       F         15
       CC        10
Name: count, dtype: int64

### 4. Save Subsets to Excel
Allows manual check of files selected. Consider whether those in the test sets are borderline cases or clear cut.

In [37]:
################################################################################################
# PLEASE CHANGE FILENAME TO THE RANDOM SEED USED IN create_balanced_sample() FOR REPRODUCIBILITY
################################################################################################
def save_subset(df, filename, output_dir=OUTPUT_DIR):
    path = output_dir / filename
    df.to_excel(path, index=False)
    print(f"Saved {len(df)} records to {path}")

#save_subset(initial_test_data, "initial_test_data_rand3.xlsx")
save_subset(test_data_100, "test_data_100_rand27.xlsx")

Saved 110 records to test_data_100_rand27.xlsx

### 3-4 B: Import Dave's Borderline Dataset

In [27]:
# Note, it doesn't matter that format is not correct, main thing is id renamed and title abstract lower case - those are the only columns used
def load_borderline_data(path="1_prompt_debugging/Dave_borderline/borderline.xlsx"):
    df = pd.read_excel(path)
    df = df.rename(columns={"Publication ID": "id"})
    df.columns = [c.lower().replace(" ", "_") for c in df.columns]
    df['scope'] = 'in'
    return df

borderline_data = load_borderline_data()
print(f"borderline_data: {borderline_data.shape}")
print(f"Columns: {list(borderline_data.columns)}")
borderline_data.head()

borderline_data: (35, 10)
Columns: ['id', 'doi', 'pmid', 'pmcid', 'isbn', 'title', 'abstract', 'pillar', 'research_category', 'scope']

,id,doi,pmid,pmcid,isbn,title,abstract,pillar,research_category,scope
0,pub.1193718255,10.1017/s0029665125101614,NaN,NaN,NaN,"Associations between the EAT-Lancet Index, foo...",The EAT-Lancet Commission’s “Planetary Health ...,PB,Consumer & market research,in
1,pub.1195208348,10.3389/fnut.2025.1677243,41346680.0,PMC12673664,NaN,Plant-based proteins for infant formula: findi...,This Review Article summarizes outcomes from t...,PB,Health & nutrition,in
2,pub.1193233825,10.1007/s44403-025-00038-9,NaN,NaN,NaN,Development of plant-based infant complementar...,Plant-based complementary foods offer a promis...,PB,End product formulation,in
3,pub.1191132017,10.6018/analesvet.634091,NaN,NaN,NaN,ELABORACIÓN DE ANÁLOGOS CÁRNICOS MEDIANTE EL P...,El interés por una alimentación saludable ha c...,PB,End product formulation,in
4,pub.1188951678,10.1016/j.foodchem.2025.144682,40570644.0,NaN,NaN,Modifications in lipids and storage proteins c...,Salvia hispanica L. (chia) is a plant of the L...,PB,Ingredient optimisation,in

#### Out of scope borderline data

In [51]:
# Note, it doesn't matter that format is not correct, main thing is id renamed and title abstract lower case - those are the only columns used
def load_OOS_borderline_data(path="1_prompt_debugging/Dave_borderline/out_scope_borderline.xlsx"):
    df = pd.read_excel(path)
    df = df.rename(columns={"Publication ID": "id"})
    df.columns = [c.lower().replace(" ", "_") for c in df.columns]
    df['scope'] = 'out'
    return df

out_borderline_data = load_OOS_borderline_data()
print(f"out_borderline_data: {out_borderline_data.shape}")
print(f"Columns: {list(out_borderline_data.columns)}")
out_borderline_data.head()

out_borderline_data: (4, 10)
Columns: ['id', 'doi', 'pmid', 'pmcid', 'isbn', 'title', 'abstract', 'pillar', 'research_category', 'scope']

,id,doi,pmid,pmcid,isbn,title,abstract,pillar,research_category,scope
0,pub.1185329350,NaN,NaN,NaN,NaN,Physical and Sensory Properties of Vegan Organ...,Market opportunities for microalgae pasta incr...,NaN,NaN,out
1,pub.1188406674,NaN,NaN,NaN,NaN,Development and Characterizing of Soy‐Sauce Li...,"Due to the chemical profile of yellow peas, co...",NaN,NaN,out
2,j.tifs.2018.04.006,j.tifs.2018.04.006,NaN,NaN,NaN,"Nutritional, functional and biological propert...",Background Consuming insects as an alternative...,NaN,NaN,out
3,j.ifset.2019.102272,j.ifset.2019.102272,NaN,NaN,NaN,The use of edible insect proteins in food: Cha...,"Over the past decade, the potential of edible ...",NaN,NaN,out

### 5. Load Prompt and Select Dataset

In [42]:
PROMPT_PATH = "1_prompt_debugging/v11/prompt_v11.md"

# ← CHANGE THIS to switch between datasets
# Options: initial_test_data (14 records), test_data_100 (110 records), 
# incorrect_scope_data (ONLY for re-run after testing and review), borderline_data (30 records)
DATASET = test_data_100

# ONLY USED AS REQUIRED FOR RE-RUN SPECIFIC PUBLICATIONS
#ids_to_test = ['pub.1190984789','pub.1190543844','pub.1190912480','pub.1184458384','pub.1191935176','pub.1187661745','pub.1184570405','pub.1196086614','pub.1188406674','pub.1185329350']
#ids_to_test = ['pub.1190984789','pub.1196086614']
#DATASET = DATASET[DATASET["id"].isin(ids_to_test)]
#DATASET.head()

In [43]:
def load_prompt(path=PROMPT_PATH):
    with open(path, "r", encoding="utf-8") as f:
        prompt_text = f.read()
    return prompt_text.strip()

system_prompt = load_prompt()
print(system_prompt)

You are an expert in alternative proteins and food science research.

Your task is to classify a research publication based on its title and abstract. First, determine whether the publication concerns research on alternative proteins intended for use in human food, applying the definitions, boundaries, and out of scope topics below. Provide a confidence score reflecting your certainty in the scope decision. Then, if in scope, assign the relevant alternative protein category label(s).

General Definition
Alternative proteins are plant-based, fermentation-derived, or cultivated alternatives to protein-rich animal-derived foods, including both novel ingredients (e.g. single-cell proteins) and direct analogues of meat, seafood, dairy, and egg products. Substitution may be at the ingredient level (e.g. a plant protein replacing whey) or the product level (e.g. plant-based dairy replacing conventional dairy), and protein need not be explicitly stated as a goal. Publications are in scope if they fall into either or both of the following two categories:
- Studies on the societal, policy, regulatory, consumer acceptance, environmental, safety, life-cycle, or techno-economic aspects of alternative proteins.
- Research that advances the development, characterisation, and understanding of alternative proteins or the processes used to produce them.

Category Definitions for Labels
Plant-based (including fermented plant-based products): Research on plant, whole mushroom, or macroalgal (algae) species either as sources of protein or as functional ingredients for alternative proteins, including studies of protein functionality, processing effects, crop or agronomic or strain optimisation, and plant-based alternatives to meat, dairy, egg, or seafood. Traditional fermentation (e.g. using yeast or lactic acid bacteria) used only as a processing method to modify a plant protein (fermented plant material) is classified as plant-based.
Fermentation (biomass and precision): Research where microbial, mycelium, single-cell, mycoprotein, or microalgae biomass is a protein source (biomass fermentation) or where microorganisms recombinantly produce specific proteins such as whey protein, heme, enzymes (precision fermentation), including the optimisation of strains, fermentation processes, and feedstocks for either route. Note: traditional fermentation (e.g. using yeast or lactic acid bacteria) used only as a processing method to modify a plant protein (fermented plant material) is classified as plant-based, not fermentation.
Cultivated meat: Research on the cultivation of animal cells, tissues, or fat in vitro for human food, including cell line development, cell culture media, scaffolding (including plant, algae, and fungal biomaterials for mammalian cell culture), and bioprocessing methods for cultivated meat, seafood, or dairy.
Cross-cutting: Only for publications that address alternative proteins and meat analogues broadly and dooes not focus on a single pillar (plant-based, fermentation, or cultivated) — typically societal, policy, regulatory, consumer acceptance, environmental, or food systems research.
Label based on the AP product being developed, not the ingredient source. An algae scaffold in cultivated meat is cultivated. A microalgae extract in a plant-based burger is plant-based. Only assign multiple labels when distinct AP production methods or products are each a focus of the paper.

Topics That Do Not Count As Alternative Proteins
The following are not relevant to alternative proteins and should not contribute to an in-scope classification.
- Non-human food applications (animal feed, aquafeed, fish food, seafood feed, pet food, biofuels, pharmaceuticals)
- Foods and alternative protein products that do not substitute animal products (e.g. bread, pasta, snacks, sauces)
- Dietary and health studies where alternative protein products or ingredients are not named or studied (e.g. only cover general plant-based diet, vegan, vegetarian, Mediterranean diet)
- General agronomic research on staple crops where protein is not the primary value (e.g. wheat, rice, maize)
- Medical nutrition or products targeting diagnosed medical conditions (nutraceuticals, bioactive peptides, therapeutic formulas)
- Meat analogues or hybrid products where the primary protein source is animal-derived
- Conventional animal-based products enriched with plant-derived or fermentation-derived ingredients or extracts, where the base product is not itself an alternative protein (e.g. plant extract added to dairy)
Where a publication covers in scope content as well as any of these topics, it is in scope.

In Scope Boundaries
- Technological research must concern alternative protein ingredients, products, or processes with a stated or intended application as human food. This may include non-protein components or functional ingredients (e.g. lipids, fibres, hydrocolloids, enzymes) intended for alternative protein products.
- Socioeconomic research (policy, regulation, consumer behaviour, market analysis, environmental impact, life-cycle assessment, techno-economic analysis, safety) is in scope if alternative proteins are explicitly named and meaningfully discussed, even if not the primary focus.
- Hybrid products combining alternative and animal proteins are only in scope when the research is relevant to alternative protein development, and not solely to improve conventional animal protein products.
- Comparisons of alternative proteins with animal proteins are in scope when alternative protein ingredients or products are explicitly named and studied (e.g. plant-based meat) — including sensory, functional, dietary, or health outcome publications.
- Biochemical properties (flavour, aroma, nutrition, allergenicity) are in scope only if the implied use case is substituting animal products.
- Enabling technologies (e.g. scaffolding materials and biomaterials for cultivated meat, cell culture components, extraction or processing methods, encapsulation systems) are in scope if alternative protein production is stated as an intended application.
- Agronomic research (e.g. crop yield, intercropping, organic farming practices, variety selection) is in scope when it concerns high-protein crops used as alternative protein feedstocks (e.g. pea, faba bean, soy, lupin, lentil, chickpea).
- General nutritional products for healthy populations (infant formula, products targeting children or adolescents) are in scope.

Confidence score guidance
Rate your confidence in the in/out scope decision on a scale of 1–5:
1 = clearly out of scope
2 = probably out of scope
3 = genuinely uncertain
4 = probably in scope
5 = clearly in scope

Output
Reasoning: 1 concise sentence explaining the scope decision.

### 6. API Call with Prompt Caching

In [47]:
# API config

# Anthropic model options — pricing as of 2026-06-10.
# Verify at https://www.anthropic.com/pricing if costs may have changed.
# Model                  Input $/1M   Output $/1M   Context
# claude-haiku-4-5         $1.00         $5.00       200K
# claude-sonnet-4-6        $3.00        $15.00       1M
# claude-opus-4-8          $5.00        $25.00       1M
MODELS = {
    "haiku":  "claude-haiku-4-5",
    "sonnet": "claude-sonnet-4-6",
    "opus":   "claude-opus-4-8",
}
MODEL = MODELS["sonnet"]  # ← change this to switch model

MAX_TOKENS = 512         # max tokens in response; adjust based on expected reasoning length and cost tolerance
TEMPERATURE = 0.0        # 0.0 = deterministic; raise to ~0.3 to sample variance across REPETITIONS
CALL_DELAY = 1.0         # seconds between API calls
REQUEST_TIMEOUT = 120    # seconds before giving up on a single API call
MAX_RETRIES = 6          # retry attempts on rate-limit / transient errors
RETRY_BASE_SECONDS = 5.0  # exponential backoff base
RETRY_MAX_SECONDS = 90.0  # cap on backoff sleep

REPETITIONS = 1  # number of full runs; increase to measure output variance across runs

# ================================================================
# CHECKPOINT CONFIG
# Saves progress after each record; a run interrupted mid-way can
# be resumed without re-processing completed records.
# Set RESUME_INCOMPLETE = False to always start from scratch.
# ================================================================
CHECKPOINT_DIR = Path("checkpoints")
RESUME_INCOMPLETE = True

# ================================================================
# REASONING TOGGLE
# Keep True during testing — reasoning shows WHY the model decides
# as it does, which is essential for evaluating prompt quality.
# Set to False for production runs once the prompt is validated,
# to reduce token usage.
# ================================================================
INCLUDE_REASONING = False

class _ClassificationBase(BaseModel):
    scope: Literal["in", "out"]
    confidence: int = Field(ge=1, le=5)
    plant_based: bool
    fermentation: bool
    cultivated: bool
    cross_cutting: bool

class _ClassificationWithReasoning(_ClassificationBase):
    reasoning: str

ClassificationSchema = _ClassificationWithReasoning if INCLUDE_REASONING else _ClassificationBase


client = anthropic.Anthropic(api_key=os.getenv("CLAUDE_API_KEY"))

def classify_publication(title, abstract, system_prompt):
    user_message = f"Title: {title}\n\nAbstract: {abstract}"
    response = client.messages.parse(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        temperature=TEMPERATURE,
        timeout=REQUEST_TIMEOUT,
        system=[ # Cache control only works for prompts of 1024+ tokens, so not currently useful. Batch API will be later though.
            {
                "type": "text",
                "text": system_prompt,
                "cache_control": {"type": "ephemeral"}
            }
        ],
        messages=[
            {"role": "user", "content": user_message}
        ],
        output_format=ClassificationSchema,
    )
    return response.parsed_output

In [48]:
def is_retryable_error(exc: Exception) -> bool:
    markers = ["503", "UNAVAILABLE", "RESOURCE_EXHAUSTED", "429",
               "TIMEOUT", "TIMED OUT", "READTIMEOUT", "CONNECTTIMEOUT"]
    return any(m in str(exc).upper() for m in markers)

def retry_sleep_seconds(attempt: int) -> float:
    sleep = min(RETRY_MAX_SECONDS, RETRY_BASE_SECONDS * (2 ** attempt))
    jitter = random.uniform(0.0, min(3.0, sleep * 0.2))
    return sleep + jitter

### 7. Error Handling with Retry

In [49]:
def classify_with_error_handling(row, system_prompt):
    pub_id = row["id"]
    last_error = None
    for attempt in range(MAX_RETRIES + 1):
        try:
            result = classify_publication(row["title"], row["abstract"], system_prompt)
            if result is None:
                print(f"  Parse failed for {pub_id}: model returned no structured output")
                return {"id": pub_id, "status": "parse_error", "error": "no structured output"}
            output = {f"{k}_LLM": v for k, v in result.model_dump().items()} # rename columns / keys to indicate LLM output
            output["id"] = pub_id
            output["status"] = "ok"
            return output
        except anthropic.APIError as e:
            last_error = e
            if attempt >= MAX_RETRIES:
                break
            if is_retryable_error(e):
                sleep_s = retry_sleep_seconds(attempt)
                print(f"  Retryable error (attempt {attempt + 1}/{MAX_RETRIES}): {e}. Sleeping {sleep_s:.1f}s.")
                time.sleep(sleep_s)
            else:
                break
    print(f"  API error for {pub_id}: {last_error}")
    return {"id": pub_id, "status": "api_error", "error": str(last_error)}

### 8. Checkpoint Helpers

In [50]:
def get_checkpoint_path(run_idx: int) -> Path:
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    return CHECKPOINT_DIR / f"run_{run_idx}_checkpoint.json"

def save_checkpoint(run_idx: int, completed_results: list) -> None:
    path = get_checkpoint_path(run_idx)
    payload = {
        "run_idx": run_idx,
        "completed_ids": [r["id"] for r in completed_results],
        "results": completed_results,
    }
    path.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")

def load_checkpoint(run_idx: int):
    path = get_checkpoint_path(run_idx)
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None

def delete_checkpoint(run_idx: int) -> None:
    path = get_checkpoint_path(run_idx)
    if path.exists():
        path.unlink()

### 9. Run on Test Data

In [51]:
all_results = []

for rep in range(REPETITIONS):
    run_idx = rep + 1
    print(f"\n{'='*50}\nRun {run_idx} / {REPETITIONS}\n{'='*50}")

    checkpoint = load_checkpoint(run_idx) if RESUME_INCOMPLETE else None
    if checkpoint:
        completed_results = checkpoint["results"]
        completed_ids = set(checkpoint["completed_ids"])
        print(f"  Resuming: {len(completed_ids)} records already processed.")
    else:
        completed_results, completed_ids = [], set()

    remaining = DATASET[~DATASET["id"].isin(completed_ids)]
    total = len(DATASET)

    for _, row in remaining.iterrows():
        n_done = len(completed_results)
        print(f"  [{n_done + 1}/{total}] {row['id']}")
        result = classify_with_error_handling(row, system_prompt)
        result["run"] = run_idx
        completed_results.append(result)
        save_checkpoint(run_idx, completed_results)
        if n_done + 1 < total:
            time.sleep(CALL_DELAY)

    delete_checkpoint(run_idx)
    all_results.extend(completed_results)

results_df = pd.DataFrame(all_results)
print(f"\nCompleted: {len(results_df)} records across {REPETITIONS} run(s)")
print(f"Successful: {(results_df['status'] == 'ok').sum()}")
print(f"Errors: {(results_df['status'] != 'ok').sum()}")
results_df

==================================================
Run 1 / 1
==================================================
  [1/110] pub.1185271743
  [2/110] pub.1191096085
  [3/110] pub.1192996596
  [4/110] pub.1190132094
  [5/110] pub.1190984789
  [6/110] pub.1188518301
  [7/110] pub.1188879491
  [8/110] pub.1188885823
  [9/110] pub.1184458384
  Parse failed for pub.1184458384: model returned no structured output
  [10/110] pub.1185768314
  [11/110] pub.1187075423
  [12/110] pub.1185662127
  [13/110] pub.1195438538
  [14/110] pub.1191737823
  [15/110] pub.1190543844
  [16/110] pub.1187308051
  [17/110] pub.1184596966
  [18/110] pub.1192717123
  [19/110] pub.1185119457
  [20/110] pub.1195616056
  [21/110] pub.1196356120
  [22/110] pub.1196657616
  [23/110] pub.1183212699
  [24/110] pub.1184068548
  [25/110] pub.1190912480
  [26/110] pub.1193543889
  [27/110] pub.1185889777
  [28/110] pub.1185850324
  [29/110] pub.1189730538
  [30/110] pub.1186201684
  [31/110] pub.1185512687
  [32/110] pub.1190464463
  [33/110] pub.1192041781
  [34/110] pub.1184995829
  [35/110] pub.1185641928
  [36/110] pub.1191684816
  [37/110] pub.1185265480
  [38/110] pub.1187735318
  [39/110] pub.1182137516
  [40/110] pub.1186003326
  [41/110] pub.1192807817
  [42/110] pub.1184410722
  [43/110] pub.1188419276
  [44/110] pub.1184210424
  [45/110] pub.1183559390
  [46/110] pub.1195478220
  [47/110] pub.1184790989
  [48/110] pub.1190518552
  [49/110] pub.1191107375
  [50/110] pub.1194604388
  [51/110] pub.1185739776
  [52/110] pub.1196249843
  [53/110] pub.1190999785
  [54/110] pub.1185798411
  [55/110] pub.1187847578
  [56/110] pub.1189159319
  [57/110] pub.1186337126
  [58/110] pub.1189157240
  [59/110] pub.1189321110
  [60/110] pub.1191558678
  [61/110] pub.1192387463
  [62/110] pub.1194405382
  [63/110] pub.1195452799
  [64/110] pub.1194448339
  [65/110] pub.1192380853
  [66/110] pub.1187862514
  [67/110] pub.1187030931
  [68/110] pub.1191935176
  [69/110] pub.1191954981
  [70/110] pub.1191685335
  [71/110] pub.1195231577
  [72/110] pub.1194503125
  [73/110] pub.1191309090
  [74/110] pub.1187052419
  [75/110] pub.1189155366
  [76/110] pub.1188411156
  [77/110] pub.1191308132
  [78/110] pub.1188840127
  [79/110] pub.1193136164
  [80/110] pub.1196344309
  [81/110] pub.1190411380
  [82/110] pub.1190075021
  [83/110] pub.1196316125
  [84/110] pub.1190881151
  [85/110] pub.1184291838
  [86/110] pub.1189350902
  [87/110] pub.1186242956
  [88/110] pub.1184899671
  [89/110] pub.1185853610
  [90/110] pub.1186522143
  [91/110] pub.1185329350
  [92/110] pub.1187158450
  [93/110] pub.1187661745
  Parse failed for pub.1187661745: model returned no structured output
  [94/110] pub.1196653689
  [95/110] pub.1188927658
  [96/110] pub.1194167969
  [97/110] pub.1195339063
  [98/110] pub.1196060350
  [99/110] pub.1193716339
  [100/110] pub.1192470719
  [101/110] pub.1186853899
  [102/110] pub.1196086614
  [103/110] pub.1193127218
  [104/110] pub.1184597721
  [105/110] pub.1189101651
  [106/110] pub.1196523072
  [107/110] pub.1184570405
  [108/110] pub.1192890631
  [109/110] pub.1188406674
  [110/110] pub.1195043228

Completed: 110 records across 1 run(s)
Successful: 108
Errors: 2

,scope_LLM,confidence_LLM,plant_based_LLM,fermentation_LLM,cultivated_LLM,cross_cutting_LLM,id,status,run,error
0,in,4.0,False,False,False,True,pub.1185271743,ok,1,NaN
1,in,5.0,True,False,True,True,pub.1191096085,ok,1,NaN
2,out,2.0,False,False,False,False,pub.1192996596,ok,1,NaN
3,in,4.0,True,False,False,False,pub.1190132094,ok,1,NaN
4,in,5.0,False,False,True,False,pub.1190984789,ok,1,NaN
...,...,...,...,...,...,...,...,...,...,...
105,in,5.0,False,True,False,False,pub.1196523072,ok,1,NaN
106,in,5.0,True,False,False,False,pub.1184570405,ok,1,NaN
107,out,1.0,False,False,False,False,pub.1192890631,ok,1,NaN
108,out,2.0,False,False,False,False,pub.1188406674,ok,1,NaN
109,out,2.0,False,False,False,False,pub.1195043228,ok,1,NaN

Note: there are two routes to receiving a CC label:
1. The LLM labels it as CC. This should only be for very general alt protein publications on socioeconomic type topics e.g. food systems transformation, consumer acceptance etc. 
2. The code below (under Derive pillar LLM from boolean flags) determines a CC label applies when more than one individual AP label has been applied by the LLM. This is for more scientific publications that explicitly measure / investigate more than one pillar.

In [53]:
# Compare LLM predictions against ground truth labels
result_cols = ["id", "run", "scope_LLM", "confidence_LLM", "plant_based_LLM", "fermentation_LLM", "cultivated_LLM", "cross_cutting_LLM", "status"]
if INCLUDE_REASONING:
    result_cols.insert(result_cols.index("confidence_LLM") + 1, "reasoning_LLM")

comparison = DATASET[["id", "title", "abstract", "scope", "pillar"]].merge(
    results_df[result_cols], on="id", how="left"
)
comparison["correct_scope"] = comparison["scope"] == comparison["scope_LLM"]

# Derive pillar_LLM from boolean flags:
# CC label if multiple pillar flags True OR if both cross_cutting_LLM and no other pillar flags True
# Then, every time only one pillar flag is True, assign that pillar; if none are True, assign NA
pillar_flags = ["plant_based_LLM", "fermentation_LLM", "cultivated_LLM"]
comparison["pillar_LLM"] = comparison[pillar_flags + ["cross_cutting_LLM"]].apply(
    lambda r: "CC" if r[pillar_flags].sum() > 1 or (r["cross_cutting_LLM"] and r[pillar_flags].sum() == 0)
              else "PB" if r["plant_based_LLM"]
              else "F"  if r["fermentation_LLM"]
              else "CM" if r["cultivated_LLM"]
              else "NA",
    axis=1
)
comparison["correct_pillar"] = comparison["pillar"] == comparison["pillar_LLM"]

# Summary metrics
print(f"Scope accuracy ({REPETITIONS} run(s)):  {comparison['correct_scope'].mean():.0%}  (n={len(comparison)})")
print(f"Pillar accuracy ({REPETITIONS} run(s)): {comparison['correct_pillar'].mean():.0%}  (n={len(comparison)})")

both_in = (comparison["scope"] == "in") & (comparison["scope_LLM"] == "in")
print(f"Pillar accuracy — both in-scope:   {comparison.loc[both_in, 'correct_pillar'].mean():.0%}  (n={both_in.sum()})")

if REPETITIONS > 1:
    per_run = comparison.groupby("run")[["correct_scope", "correct_pillar"]].mean()
    print(f"\nPer-run accuracy:\n{per_run.to_string()}")

display_cols = ["id", "title", "abstract", "scope", "scope_LLM", "confidence_LLM"]
if INCLUDE_REASONING:
    display_cols.append("reasoning_LLM")
display_cols += ["correct_scope", "pillar", "pillar_LLM", "correct_pillar", "plant_based_LLM", "fermentation_LLM", "cultivated_LLM", "cross_cutting_LLM"]
comparison[display_cols]

Scope accuracy (1 run(s)):  87%  (n=110)
Pillar accuracy (1 run(s)): 85%  (n=110)
Pillar accuracy — both in-scope:   97%  (n=61)

,id,title,abstract,scope,scope_LLM,confidence_LLM,correct_scope,pillar,pillar_LLM,correct_pillar,plant_based_LLM,fermentation_LLM,cultivated_LLM,cross_cutting_LLM
0,pub.1185271743,Toward consumer-focused food policies: a toolb...,In transitioning toward consuming more sustain...,in,in,4.0,True,CC,CC,True,False,False,False,True
1,pub.1191096085,Consumer acceptance of different protein sourc...,A wide variety of alternative proteins have be...,in,in,5.0,True,CC,CC,True,True,False,True,True
2,pub.1192996596,"Genetically modified Crops: Balancing safety, ...",The present review examines the safety assessm...,out,out,2.0,True,NA,NA,True,False,False,False,False
3,pub.1190132094,Reducing antinutritional compounds in Amaranth...,"Amaranth (Amaranthus hypochondriacus), a glute...",out,in,4.0,False,NA,PB,False,True,False,False,False
4,pub.1190984789,Mimicking the myoseptum in cultivated fish by ...,Cultivated fish can offer seafood with lower e...,in,in,5.0,True,CM,CM,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,pub.1196523072,Downstream Processing of Food Proteins from Pr...,Precision fermentation uses microorganisms (e....,in,in,5.0,True,F,F,True,False,True,False,False
106,pub.1184570405,Recent updates on plant protein-based dairy ch...,"In response to population growth, ethical cons...",in,in,5.0,True,PB,PB,True,True,False,False,False
107,pub.1192890631,Electromethanogenesis with 3D printed carbon e...,Electromethanogenesis offers a promising appro...,out,out,1.0,True,NA,NA,True,False,False,False,False
108,pub.1188406674,Development and Characterizing of Soy‐Sauce Li...,"Due to the chemical profile of yellow peas, co...",out,out,2.0,True,NA,NA,True,False,False,False,False
109,pub.1195043228,Fabrication and characterization of high inter...,This study investigated high internal phase Pi...,in,out,2.0,False,CC,NA,False,False,False,False,False

### 10. Save to Excel for Prompt Debugging
To assess how well the prompt does at getting the LLM to assign scope and pillar, I need to save the comparison data, then manually review what went wrong and adjust the prompt.
None of this will make it into the final workflow.

Order of working:
1. Create a new version folder in the 1_prompt_debugging folder.
2. Copy in the previous prompt. Label it with the new version number. Make updates as required based on step 6.
3. Edit Step 10 output directory (this step) and Step 5 prompt selection and input data.
4. Run the script from steps 5-10.
5. Manually review the results. Includes both metrics and 
6. Write a text document about v1 results and what changes you want to make to the prompt. Repeat from step 1.

In [54]:
save_dir = Path("1_prompt_debugging/v11") # CHANGE ME
save_dir.mkdir(parents=True, exist_ok=True)

metrics_df = pd.DataFrame([
    {"metric": "scope_accuracy",                "value": f"{comparison['correct_scope'].mean():.0%}",               "n": len(comparison)},
    {"metric": "pillar_accuracy",               "value": f"{comparison['correct_pillar'].mean():.0%}",              "n": len(comparison)},
    {"metric": "pillar_accuracy_both_in_scope", "value": f"{comparison.loc[both_in, 'correct_pillar'].mean():.0%}", "n": int(both_in.sum())},
])

with pd.ExcelWriter(save_dir / f"{MODEL}_results.xlsx") as writer:
    comparison[display_cols].to_excel(writer, sheet_name="comparison", index=False)
    metrics_df.to_excel(writer, sheet_name="metrics", index=False)

print(f"Saved to {save_dir / f'{MODEL}_results.xlsx'}")

Saved to 1_prompt_debugging\v11\claude-sonnet-4-6_results.xlsx

In [41]:
# Create dataset of only rows where LLM got scope wrong, for re-run with modified prompt
incorrect_ids = comparison.loc[~comparison["correct_scope"], "id"]
incorrect_scope_data = DATASET[DATASET["id"].isin(incorrect_ids)].reset_index(drop=True)
incorrect_scope_data

,id,title,abstract,year,scope,pillar,research_category
0,pub.1193443783,Proliferation and metabolic activity of the At...,Introduction: Fish cell lines represent a powe...,2025,in,CM,Cell culture media
1,pub.1189767013,Keeping an eye on alginate: innovations and op...,"Alginate is a biocompatible, biodegradable, br...",2025,in,CM,Scaffolding
2,pub.1193123540,Intercropping traditional pea varieties with f...,"Although being a historical farming practise, ...",2025,in,PB,Crop development
3,pub.1186250605,Changing Food in a Changing World: Assessing C...,"Background/Objectives: In recent decades, the ...",2025,in,CM,Consumer & market research
4,pub.1184676351,Fermentation of a wine pomace and microalgae b...,This study aimed to generate new functional in...,2025,in,CC,Ingredient optimisation
5,pub.1185271743,Toward consumer-focused food policies: a toolb...,In transitioning toward consuming more sustain...,2025,in,CC,Other
6,pub.1190672497,Consumer Insights Tracker End of Year Report (...,This report presents the findings from the Con...,2025,in,CM,Consumer & market research
7,pub.1192751374,Processing a maize germ side stream: de-oiling...,Maize grain processing usually starts with deg...,2025,in,PB,Ingredient optimisation
8,pub.1184367118,We are a family! Exploring flexitarian househo...,It is widely accepted that the (over)consumpti...,2025,in,PB,Consumer & market research
9,pub.1193249719,Evaluating Scale-Up Cultivation Modes for Aspe...,Organic-waste-derived volatile fatty acids (VF...,2025,in,F,Feedstocks
10,pub.1192827486,Transcriptome profiles for defining avian prim...,Avian biology has contributed to many research...,2025,in,CM,Cell line development
11,pub.1186661415,Environmental mitigation potential of waste-to...,Processing underutilized bioresidues (for exam...,2025,in,F,Impact assessments
12,pub.1191677996,An in vitro study exploring the role of mucin ...,"In the mouth, food flavors interact with saliv...",2025,in,PB,Ingredient optimisation
13,pub.1196064670,CIPROMED: building resilient and circular prot...,CIPROMED: building resilient and circular prot...,2025,in,CC,Other
14,pub.1184344359,Chitosan-zinc oxide thyme oil-based edible ant...,"Abstract Chitosan (CS), zinc oxide (ZnO), and ...",2025,in,PB,Ingredient optimisation
15,pub.1183660277,Use of a coaxial nozzle-assisted 3D printing a...,This work innovatively merges engineered food ...,2025,in,F,Texturization methods
16,pub.1186213546,Impact of Vegan and Vegetarian Diets on Neurol...,BACKGROUND/OBJECTIVES: The global shift toward...,2025,in,PB,Health & nutrition