In [3]:
import pandas as pd
import duckdb

In [13]:
# Read and display curated data csv for inspection
df = pd.read_csv('../publications_curated.csv')
df

,id,title,abstract,year,scope,pillar,research_category
0,pub.1192791591,Mushroom: an emerging source for next generati...,"Background: In recent years, plant-based and a...",2025,in,PB,Ingredient optimisation
1,pub.1187762379,Plant-Based Alternatives to Meat Products,Animal proteins have been used in the formulat...,2025,in,PB,Other
2,pub.1193391974,Influence of processing on protein quality and...,While meat is an established source of high-qu...,2025,in,PB,Ingredient optimisation
3,pub.1188899046,Solid State Fermentation—A Promising Approach ...,The increasing demand for sustainable dietary ...,2025,in,F,Other
4,pub.1193352421,"Physicochemical, Microbiological and Sensory E...",The bioactive properties of a phenolic extract...,2025,in,PB,End product formulation
...,...,...,...,...,...,...,...
4810,pub.1186543050,Enhancing Tomato Growth and Quality Under Defi...,This study aimed to evaluate the effect of two...,2025,out,NaN,NaN
4811,pub.1185481528,Exploring acorn shells: Phenolic composition a...,"Pedunculate (Quercus robur L.), holm (Quercus ...",2025,out,NaN,NaN
4812,pub.1185189092,Bioaccessibility Performance of Phenolic Compo...,"Red fruits are rich in phenolic compounds, par...",2025,out,NaN,NaN
4813,pub.1185127538,Phytochemical characterization and bioactive p...,Strawberry is one of the most consumed berries...,2025,out,NaN,NaN
4814,pub.1181768830,Closing the loop: exploring apple pomace as a ...,"Apple pomace (AP), the common designation of b...",2025,out,NaN,NaN

In [11]:
## Read database and show tables
con = duckdb.connect('../publications.db', read_only=True) # Open database in read-only mode
con.sql("SHOW TABLES").show() 
con.close()

┌──────────────────┐
│       name       │
│     varchar      │
├──────────────────┤
│ publications_raw │
└──────────────────┘

In [12]:
## Read and display curated database using SQL for inspection
con = duckdb.connect('../publications.db', read_only=True)
df_db = con.sql("SELECT * FROM publications_raw").df()
con.close()
df_db

,id,title,abstract,year,scope,pillar,research_category
0,pub.1192791591,Mushroom: an emerging source for next generati...,"Background: In recent years, plant-based and a...",2025,in,PB,Ingredient optimisation
1,pub.1187762379,Plant-Based Alternatives to Meat Products,Animal proteins have been used in the formulat...,2025,in,PB,Other
2,pub.1193391974,Influence of processing on protein quality and...,While meat is an established source of high-qu...,2025,in,PB,Ingredient optimisation
3,pub.1188899046,Solid State Fermentation—A Promising Approach ...,The increasing demand for sustainable dietary ...,2025,in,F,Other
4,pub.1193352421,"Physicochemical, Microbiological and Sensory E...",The bioactive properties of a phenolic extract...,2025,in,PB,End product formulation
...,...,...,...,...,...,...,...
4810,pub.1186543050,Enhancing Tomato Growth and Quality Under Defi...,This study aimed to evaluate the effect of two...,2025,out,NA,NA
4811,pub.1185481528,Exploring acorn shells: Phenolic composition a...,"Pedunculate (Quercus robur L.), holm (Quercus ...",2025,out,NA,NA
4812,pub.1185189092,Bioaccessibility Performance of Phenolic Compo...,"Red fruits are rich in phenolic compounds, par...",2025,out,NA,NA
4813,pub.1185127538,Phytochemical characterization and bioactive p...,Strawberry is one of the most consumed berries...,2025,out,NA,NA
4814,pub.1181768830,Closing the loop: exploring apple pomace as a ...,"Apple pomace (AP), the common designation of b...",2025,out,NA,NA