In [21]:
import duckdb
import dimcli
import pandas as pd

In [ ]:
# Connect to the database
con = duckdb.connect("publications.db")

In [ ]:
# Have a look at the data stored in the csv file
con.sql("SELECT PublicationID, Title, Abstract, Year, Pillar, Research_category  FROM 'publications_test_data.csv'").show()

┌────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────┬─────────┬──────────────────────────────┐
│ PublicationID  │                                                                      Title                                                                       │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Abstract                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  │ Year  │ Pillar  │      Research_category       │
│    varchar     │                                                                     varchar                                                                      │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  varchar                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  │ int64 │ varchar │           varchar            │
├────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────┼─────────┼──────────────────────────────┤
│ pub.1120937380 │ Carbon footprint and land use of oat and faba bean protein concentrates using a life cycle assessment approach                                   │ There is a need to find sustainable alternative protein sources in order to meet the increasing protein demand of the growing population. Legumes such as faba beans are underutilized protein rich sources and can be valorized as hybrid protein ingredient through dry fractionation technologies. Also, cereal side streams can be interesting sources towards multifunctional protein ingredients. The aim of this study was to assess the environmental impacts of the production of oat protein concentrate (OPC) and faba bean protein concentrate (FBC) using life cycle assessment (LCA) methodology and to compare the impact per kg protein to other relevant proteins. The OPC is obtained as a side stream of the beta glucan extraction process, which also produces valuable oat oil, while FBC is the only main product obtained from dehulled faba beans. Average European oat cultivation and faba bean cultivation with low and high yield were modelled. Data for protein concentrates production was from real factories who have suitable facilities, but are not currently producing concentrates commercially. The major hotspot in the carbon footprint of oat protein concentrate comes from energy consumption in processing. For faba bean protein concentrate, energy consumption in processing is lower and cultivation of faba bean is the main hotspot. The carbon footprint of oat protein concentrate is more than 50 percent lower, compared to dairy proteins per kg protein, while the carbon footprint of faba bean concentrate protein is 80–90 percent lower. Compared to legume protein sources, OPC has four times higher impacts. This is mainly due to the lower amount of processing steps needed to reach high protein content concentrates from faba beans resulting mainly from relatively lower level of lipids, which enables more energy-efficient dry separation, and high initial protein content of legumes compared to cereals. Moreover, legume cultivation requires very little nitrogen fertilizers due to symbiotic N2 fixation. This study shows that OPC and FBC have lower carbon footprints than animal protein sources. However, it should be remembered, that the environmental impacts of OPC are very sensitive to the allocation method and allocation basis. In this study economic allocation was used and prices of the different products (OPC, oat oil and beta glucan) play a key role in defining the climate impacts of OPC. │  2020 │ PB      │ Env/impact assessments       │
│ pub.1121194480 │ Mock meat in the butchery: Nudging consumers toward meat substitutes                                                                             │ Is it possible to nudge consumers to swap their chicken sandwich for a meat substitute? A field study tests whether adapting the choice architecture of a large retail store increases the purchase of meat substitutes among nonusers. Instead of offering meat substitutes exclusively in a separate, vegetarian section, this study places them next to similar meat products in the butchery. As such, we (1) increase the meat substitutes’ visibility and (2) offer them in pairs with their meat-based counterparts. Doing so enhances sales of meat substitutes, relative to both past sales in the experimental store and sales in eight other control stores that serve as benchmarks. No backfire effect was observed as meat product sales did not increase significantly. A follow-up study disentangles the effect of product visibility and pairwise presentation. Both product visibility and pairwise presentation increase sales of meat substitutes. However, when visibility is high, fewer meat substitutes were sold in a pairwise presentation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    │  2021 │ CC      │ Consumer and market research │
│ pub.1121428913 │ Consumer responses to novel and unfamiliar foods                                                                                                 │ The demand for sustainable foods and an increased consciousness of health and well-being, as well as other societal changes, create opportunities to develop novel foods. However, consumers are programmed from early childhood to prefer familiar foods. We now know that individual variations in disposition determine responses to novelty. Disgust, along with food neophobia and related traits, has been identified as a major barrier to accepting novel food alternatives. In this paper, we present two novel foods trends (meat alternatives and products for health and well-being) as examples of current research. We conclude that successfully launching novel foods require a deep understanding of product perception and the consumer traits that determine rejection or acceptance.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  │  2020 │ CC      │ Consumer and market research │

In [ ]:
# This would be a way to create the table and load the data in one step, but it doesn't allow us to set the PublicationID as the primary key
# con.sql("CREATE TABLE publications_raw AS SELECT PublicationID, Title, Abstract, Pillar, Research_category FROM 'publications_data.csv'")

# This line deletes the created table
# con.sql("DROP TABLE IF EXISTS publications_raw")

In [ ]:
# In order to have the Publication ID as the primary key, we need to create the table in two steps:
# Step 1: create the table with the schema
con.sql("""
    CREATE TABLE publications_raw (
        id VARCHAR PRIMARY KEY,
        title VARCHAR,
        abstract VARCHAR,
        year INT,
        pillar VARCHAR,
        research_category VARCHAR
    )
""")

# Step 2: load the CSV into it
con.sql("INSERT INTO publications_raw SELECT PublicationID, Title, Abstract, Year, Pillar, Research_category FROM 'publications_test_data.csv'")

In [31]:
con.sql("DESCRIBE publications_raw").show()

┌───────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│    column_name    │ column_type │  null   │   key   │ default │  extra  │
│      varchar      │   varchar   │ varchar │ varchar │ varchar │ varchar │
├───────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id                │ VARCHAR     │ NO      │ PRI     │ NULL    │ NULL    │
│ title             │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ abstract          │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ year              │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ pillar            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ research_category │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└───────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

In [ ]:
# Dimensions API login using dsl.ini file
dimcli.login()

Searching config file credentials for default 'live' instance..

Dimcli - Dimensions API Client (v1.7)
Connected to: <https://app.dimensions.ai/api/dsl> - DSL v2.15
Method: dsl.ini file

In [ ]:
# Make query
%%dsldf
search publications
for """("meat substitute" OR "meat analogue")"""
where year in [2020:2025]
return publications[id+title+abstract+year]
limit 100

Returned Publications: 100 (total = 16616)
Time: 1.86s

,id,title,abstract,year
0,pub.1187231244,Plant-proteins based 3D meat analog printing: ...,This review summarizes and critically analyze ...,2025
1,pub.1182395108,Market Status of Meat Analogs and Their Impact...,"The alternative meat industry, which aims to r...",2024
2,pub.1182772853,Plant Taxa as Raw Material in Plant-Based Meat...,<b>Background/Objectives</b>: The environmenta...,2024
3,pub.1192791591,Mushroom: an emerging source for next generati...,"Background: In recent years, plant-based and a...",2025
4,pub.1176097424,Plant-based Meat Analogs: Perspectives on Thei...,Purpose of ReviewPlant-based meat analogs (PBM...,2024
...,...,...,...,...
95,pub.1176270921,Spirulina platensis protein-based emulsion gel...,"In this paper, Spirulina platensis protein-bas...",2024
96,pub.1190536409,A Dimensionless Empirical Model to Predict Hea...,An empirical dimensionless relationship useful...,2025
97,pub.1169992045,Construction of a soybean protein isolate/poly...,A growing interest has arisen in recreating re...,2024
98,pub.1195785564,Aggregation mechanism of soybean protein isola...,The aggregation behavior and interaction mecha...,2025
99,pub.1173139999,Protein transition: focus on protein quality i...,"The current consumption trends, combined with ...",2024

In [ ]:
# Create new table within database for query results
con.sql("""
    CREATE TABLE publications_query (
        id VARCHAR PRIMARY KEY, 
        title VARCHAR, 
        abstract VARCHAR, 
        year INT)
    """)

In [ ]:
# Insert query results into database
con.sql("INSERT INTO publications_query SELECT * FROM dsl_last_results")

In [63]:
# Extract query results that had not been present in the database yet
con.sql("""
    SELECT COUNT(*)
    FROM publications_raw
    WHERE id IN (SELECT id FROM publications_query)
""").show()

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│           23 │
└──────────────┘

In [58]:
# Add a column for in/out of scope
con.sql("ALTER TABLE publications_raw ADD COLUMN scope TEXT DEFAULT 'out'")

# Update a value
con.sql("UPDATE publications_raw SET scope = 'in' WHERE id IN (SELECT id FROM publications_query)")

In [59]:
# Convert to pandas dataframe
df = con.sql("SELECT * FROM publications_raw").df()

In [ ]:
# Filter for in scope publications
df[df['scope'] == 'in']

,id,title,abstract,year,pillar,research_category,scope
1955,pub.1167674511,Structural and mechanical anisotropy in plant-...,The rising demand for plant-based meat analogu...,2024,PB,Manufacturing (incl Texturization methods),in
2087,pub.1169358163,Influence of Lowering the pH Value on the Gene...,High-moisture extrusion of plant proteins to c...,2024,PB,Manufacturing (incl Texturization methods),in
2137,pub.1170440622,In vitro digestibility and solubility of phosp...,Interest in plant-based meat analogues has inc...,2024,PB,End product formulation,in
2171,pub.1171008316,Exploring the Role and Functionality of Ingred...,The development of plant-based meat analogues ...,2024,PB,End product formulation,in
2305,pub.1173139999,Protein transition: focus on protein quality i...,"The current consumption trends, combined with ...",2024,CC,Food safety & quality,in
2381,pub.1174056169,Plant-Based Meat Analogues: Exploring Proteins...,As the lack of resources required to meet the ...,2024,PB,End product formulation,in
2482,pub.1175387236,Meat substitutes in Swedish school meals: nutr...,This study provides an overview of the ingredi...,2024,PB,Health /nutrition,in
2547,pub.1181205352,Alternative proteins; A path to sustainable di...,With a growing global population and the resul...,2024,CC,End product formulation,in
2578,pub.1181632383,Comparing the nutritional value and prices of ...,Since overconsumption of animal-sourced foods ...,2024,CC,Consumer and market research,in
2663,pub.1182670243,Is it still meat? The effects of replacing mea...,Consumer interest in a shift toward moderating...,2024,CC,No sector assigned,in
2666,pub.1182680189,Sensory and hedonic perception of meat versus ...,"Nowadays, consumption habits are changing for ...",2024,PB,End product formulation,in
2680,pub.1182772853,Plant Taxa as Raw Material in Plant-Based Meat...,Background/Objectives: The environmental probl...,2024,PB,Ingredient optimisation,in
2694,pub.1182960931,Substitution patterns and price response for p...,Efforts to promote sustainable resource use th...,2024,PB,Consumer and market research,in
2723,pub.1183400910,Are Argentinians ready for plant-based meat al...,Meat alternatives' popularity is increasing wo...,2024,PB,Consumer and market research,in
2801,pub.1184367118,We are a family! Exploring flexitarian househo...,It is widely accepted that the (over)consumpti...,2025,PB,Consumer & market research,in
2876,pub.1185255386,Alternative Protein-Based Meat and Fish Analog...,This study aimed to explore the extent of rese...,2025,CC,Manufacturing (incl Texturization methods),in
3102,pub.1187762379,Plant-Based Alternatives to Meat Products,Animal proteins have been used in the formulat...,2025,PB,No sector assigned,in
3202,pub.1188899046,Solid State Fermentation—A Promising Approach ...,The increasing demand for sustainable dietary ...,2025,F,No sector assigned,in
3392,pub.1191329219,The amino acid composition of commercially ava...,Plant-based meat and dairy analogues contain l...,2025,PB,Health /nutrition,in
3490,pub.1192791591,Mushroom: an emerging source for next generati...,"Background: In recent years, plant-based and a...",2025,PB,Ingredient optimisation,in
3647,pub.1194474852,A Nutritional Evaluation of Plant-Based Meat a...,Plant-based meat and sausage analogues (PBMAs)...,2025,PB,Health & nutrition,in
3648,pub.1194494932,Engineering Processes for Plant‐Based Meat Ana...,Plant-based meat analogs (PBMAs) have emerged ...,2025,PB,Manufacturing (incl Texturization methods),in
3755,pub.1196060665,Nutrient Equivalence of Plant-Based and Cultur...,Meat provides high-quality protein and essenti...,2025,CC,Health & nutrition,in

In [64]:
con.close()